import { execFile } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { promisify } from 'node:util';

import { describe, expect, it, vi } from 'vitest';

import {
  runGuidanceCli,
  type GuidanceCliDependencies,
  type GuidanceCliIo,
} from '../../src/transcript/coding-session-handoff/guidance-cli.js';

const execFileAsync = promisify(execFile);

function harness() {
  const stdout: string[] = [];
  const stderr: string[] = [];
  const io: GuidanceCliIo = {
    stdout: (value) => stdout.push(value),
    stderr: (value) => stderr.push(value),
  };
  const dependencies: GuidanceCliDependencies = {
    discover: vi.fn(async () => []),
    preview: vi.fn(async () => []),
    prepare: vi.fn(async () => ({ status: 'experimental-not-released' })),
  };
  return { io, dependencies, stdout, stderr };
}

describe('experimental guidance CLI', () => {
  it('exposes only discover, preview, and prepare', async () => {
    const test = harness();
    expect(await runGuidanceCli(['--help'], test.dependencies, test.io)).toBe(
      0,
    );
    const help = test.stdout.join('');
    expect(help).toContain('discover --source');
    expect(help).toContain('preview --source');
    expect(help).toContain('prepare --source');
    expect(help).toContain('EXPERIMENTAL / NOT RELEASED');
    expect(help).not.toMatch(
      /\bexecute\b|behavior-verify|reconcile|behavior-plan/,
    );
  });

  it('routes discovery for all providers without inferring current identity', async () => {
    const test = harness();
    expect(
      await runGuidanceCli(
        ['discover', '--source', '/repo/source', '--provider', 'all', '--json'],
        test.dependencies,
        test.io,
      ),
    ).toBe(0);
    expect(test.dependencies.discover).toHaveBeenCalledWith(
      '/repo/source',
      'all',
    );
    expect(JSON.parse(test.stdout[0])).toMatchObject({
      ok: true,
      command: 'discover',
      status: 'experimental-not-released',
      currentSelection: 'explicit-required',
    });
  });

  it('requires an explicit qualified source for preview and prepare', async () => {
    const preview = harness();
    expect(
      await runGuidanceCli(
        [
          'preview',
          '--source',
          '/repo/source',
          '--session',
          'codex:cli:source-id',
          '--json',
        ],
        preview.dependencies,
        preview.io,
      ),
    ).toBe(0);
    expect(preview.dependencies.preview).toHaveBeenCalledWith(
      '/repo/source',
      'codex:cli:source-id',
    );

    const prepare = harness();
    expect(
      await runGuidanceCli(
        [
          'prepare',
          '--source',
          '/repo/source',
          '--target',
          '/repo/target',
          '--session',
          'claude:cli:source-id',
          '--entry-point',
          'destination-fresh',
          '--json',
        ],
        prepare.dependencies,
        prepare.io,
      ),
    ).toBe(0);
    expect(prepare.dependencies.prepare).toHaveBeenCalledWith(
      '/repo/source',
      '/repo/target',
      'claude:cli:source-id',
      'destination-fresh',
    );
  });

  it.each(['execute', 'reconcile', 'behavior-plan', 'behavior-verify'])(
    'rejects old automation command %s',
    async (command) => {
      const test = harness();
      expect(
        await runGuidanceCli([command, '--json'], test.dependencies, test.io),
      ).toBe(2);
      expect(test.dependencies.discover).not.toHaveBeenCalled();
      expect(test.dependencies.preview).not.toHaveBeenCalled();
      expect(test.dependencies.prepare).not.toHaveBeenCalled();
    },
  );

  it('ships a dependency-free generated bundle isolated from the old executor', async () => {
    const source = await readFile(
      new URL(
        '../../src/transcript/coding-session-handoff/guidance-cli.ts',
        import.meta.url,
      ),
      'utf8',
    );
    expect(source).not.toMatch(
      /\.\/cli\.js|behavior-gate|\.\/handoff\.js|\.\/providers\.js/,
    );

    const bundleUrl = new URL(
      '../../skills/coding-session-handoff/scripts/coding-session-handoff.mjs',
      import.meta.url,
    );
    const bundle = await readFile(bundleUrl, 'utf8');
    expect(bundle).toContain(
      '// GENERATED by scripts/build-generated.mjs. Do not edit directly.',
    );
    expect(bundle).not.toMatch(/from\s+['"](?:\.\.\/|\.\/).*\.js['"]/);
    expect(bundle).not.toContain('behavior-verify');
    expect(bundle).not.toContain('executeHandoffPlan');

    const result = await execFileAsync(
      process.execPath,
      [bundleUrl.pathname, '--help'],
      {
        encoding: 'utf8',
      },
    );
    expect(result.stdout).toContain('EXPERIMENTAL / NOT RELEASED');
  });
});
