// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/consensus/core/consensus-loop.ts
import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import {
  mkdir,
  open,
  readFile,
  rename,
  unlink,
  writeFile
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  VERDICT_CAPS,
  SYNTHESIS_CAPS,
  LOOP_SCHEMA_VERSION,
  SUBPROCESS_OUTPUT_CAP_BYTES,
  PROVIDER_CLI_KILL_GRACE_MS,
  PROVIDER_CLI_FINAL_RESOLUTION_MS,
  EXIT_CODES,
  ConsensusError,
  ITERATION_MODES,
  COLD_START_MODES,
  callsPerRound,
  invalidIterationModeError,
  parallelSchemaPath,
  peerSchemaPathForMode,
  synthesisSchemaPath,
  exitCodeForError,
  normalizeForHash,
  hashArtifact,
  validateVerdictShape,
  normalizeVerdict,
  validateSynthesisShape,
  validateSynthesisCaps,
  validateVerdictCaps,
  isJsonRecord,
  asErrorLike,
  validationErrors,
  validationMetadata,
  hashOptionsForAgency,
  convergenceOptionsForAgency,
  verdictDecision,
  roundCount,
  required,
  schemaPath,
  hardErrorMessage,
  recordHash,
  formatArtifactHash,
  PARALLEL_MODES
} from './loop-validation.mjs';
import {
  createRecordsWriter,
  peerRecords,
  peerTurnCount,
  readExistingRecords,
  synthesisRecordCount,
  syncFileIfAvailable,
  withRecordMetadata,
  writeLoopStatus
} from './loop-records.mjs';
import {
  CONSENSUS_SHARED_CLI_RELATIVE_PATH,
  consensusProviderCliMissingError,
  consensusSharedCliPath,
  invokeConsensusProviderCli,
  invokeProviderCliWithRetry,
  invokeValidatedPeer,
  providerAuditFields,
  providerCliSpawnTarget,
  requireConsensusCliPath,
  resolveConsensusCliPath,
  resolveConsensusCliPathDetails,
  runProviderCliCommand
} from './loop-provider.mjs';
import { parseLoopArgs } from './loop-args.mjs';
import {
  buildParallelTurnPrompt,
  buildSynthesisPrompt,
  buildTurnPrompt,
  resolvePromptProfile,
  verdictForPrompt
} from './loop-prompts.mjs';
async function writeSectionOutput(outputPath, artifact) {
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, artifact);
  await syncFileIfAvailable(outputPath);
}
async function writeTerminalArtifacts(options, status, artifact, records) {
  await writeSectionOutput(options.outputSection, artifact);
  const normalizedStatus = await writeLoopStatus(options.outputStatus, status);
  return {
    status: normalizedStatus,
    output: artifact,
    records
  };
}
function resultStatus(status, terminationReason, records, options, extra = {}) {
  const peerCalls = peerRecords(records).filter(
    (record) => record?.record_type !== "synthesis"
  ).length;
  const synthesisCalls = synthesisRecordCount(records);
  const turns = peerCalls;
  return {
    status,
    termination_reason: terminationReason,
    turns,
    rounds: roundCount(turns, options.peers.length),
    agency: options.agency,
    iteration_mode: options.iteration,
    cold_start: options.coldStart,
    peer_calls: peerCalls,
    synthesis_calls: synthesisCalls,
    ...extra
  };
}
async function seedRecordsFile(recordsPath, records, options = {}) {
  const seedRecords = Array.isArray(records) ? records : [];
  const existingRecords = await readExistingRecords(recordsPath);
  if (existingRecords.length > 0 || seedRecords.length === 0) {
    return existingRecords;
  }
  const normalizedRecords = seedRecords.map(
    (record) => withRecordMetadata(record, options)
  );
  await mkdir(path.dirname(recordsPath), { recursive: true });
  await writeFile(
    recordsPath,
    `${JSON.stringify(normalizedRecords, null, 2)}
`
  );
  await syncFileIfAvailable(recordsPath);
  return normalizedRecords;
}
async function appendIntervention({
  writer,
  records,
  options,
  currentArtifact,
  intervention
}) {
  if (!intervention) return null;
  const isHost = intervention.agent === "host-orchestrator";
  const nextRound = Math.max(0, ...records.map((record2) => Number(record2.round_index) || 0)) + 1;
  const payload = {
    turn_index: records.length + 1,
    round_index: nextRound,
    agent: isHost ? "host-orchestrator" : "user",
    verdict: isHost ? "HOST_DECISION" : "USER_INTERVENTION",
    reasoning: intervention.direction,
    artifact_hash: hashArtifact(
      currentArtifact,
      hashOptionsForAgency(options.agency)
    ),
    iteration_mode: options.iteration
  };
  if (isHost) {
    if (intervention.decisionKind)
      payload.decision_kind = intervention.decisionKind;
    if (intervention.escalationTrigger)
      payload.escalation_trigger = intervention.escalationTrigger;
  } else {
    payload.user_direction = intervention.direction;
  }
  const record = await writer.append(payload);
  records.push(record);
  return record;
}
function resolveIntervention(runOptions, options) {
  const userDirection = runOptions.userDirection ?? options.userDirection;
  const hostDirection = runOptions.hostDirection ?? options.hostDirection;
  if (hostDirection) {
    return {
      agent: "host-orchestrator",
      direction: hostDirection,
      decisionKind: runOptions.hostDecisionKind ?? options.hostDecisionKind ?? "direct",
      escalationTrigger: runOptions.escalationTrigger ?? options.escalationTrigger ?? null
    };
  }
  if (userDirection) {
    return { agent: "user", direction: userDirection };
  }
  return null;
}
async function executeAlternatingTurn({
  turnIndex,
  options,
  records,
  currentArtifact,
  invokePeer,
  prompts = resolvePromptProfile()
}) {
  const peerIndex = turnIndex % options.peers.length;
  const provider = options.peers[peerIndex];
  const turn = turnIndex + 1;
  const round = Math.floor(turnIndex / options.peers.length) + 1;
  const prompt = prompts.buildTurnPrompt({
    provider,
    peerIndex,
    coldStart: options.coldStart,
    round,
    turn,
    goal: options.goal,
    artifact: currentArtifact,
    previousVerdict: verdictForPrompt(records.at(-1)),
    priorRecords: records
  });
  const peerResult = await invokePeer({
    provider,
    peerIndex,
    round,
    turn,
    prompt,
    artifact: currentArtifact
  });
  const verdict = normalizeVerdict(
    peerResult.json,
    options.iteration
  );
  const shape = validateVerdictShape(verdict, { mode: options.iteration });
  if (!shape.ok) {
    throw new ConsensusError(
      `invalid verdict shape: ${validationErrors(shape).join("; ")}`,
      {
        code: "INVALID_VERDICT_SHAPE",
        exitCode: EXIT_CODES.DATA,
        details: { errors: validationErrors(shape) }
      }
    );
  }
  const caps = validateVerdictCaps(verdict, { mode: options.iteration });
  if (!caps.ok) {
    throw new ConsensusError(
      `invalid verdict caps: ${JSON.stringify(validationMetadata(caps))}`,
      {
        code: "INVALID_VERDICT_CAPS",
        exitCode: EXIT_CODES.DATA,
        details: validationMetadata(caps)
      }
    );
  }
  let nextArtifact = currentArtifact;
  if (verdict.verdict === "REVISE") {
    nextArtifact = verdict.proposed_artifact;
  }
  const recordPayload = {
    turn_index: turn,
    round_index: round,
    agent: provider,
    verdict: verdict.verdict,
    reasoning: verdict.reasoning,
    artifact_hash: hashArtifact(
      nextArtifact,
      hashOptionsForAgency(options.agency)
    ),
    iteration_mode: options.iteration,
    ...providerAuditFields(peerResult)
  };
  if (typeof verdict.proposed_artifact === "string") {
    recordPayload.proposed_artifact = verdict.proposed_artifact;
  }
  if (Array.isArray(verdict.concerns)) {
    recordPayload.concerns = verdict.concerns;
  }
  return { verdict, recordPayload, nextArtifact };
}
function lastRoundPeerRecords(records, peers) {
  const peers0 = peers[0];
  const peers1 = peers[1];
  let own = null;
  let peer = null;
  for (let index = records.length - 1; index >= 0; index -= 1) {
    const record = records[index];
    if (record?.agent === peers0 && !own) own = record;
    if (record?.agent === peers1 && !peer) peer = record;
    if (own && peer) break;
  }
  return { [peers0]: own, [peers1]: peer };
}
function revisionTextFor(record) {
  if (!record) return null;
  if (typeof record.proposed_artifact === "string")
    return record.proposed_artifact;
  return null;
}
function critiqueFor(record) {
  if (record && record.critique && typeof record.critique === "object")
    return record.critique;
  return null;
}
function validatePeerVerdict(verdict, mode, provider) {
  const shape = validateVerdictShape(verdict, { mode });
  if (!shape.ok) {
    throw new ConsensusError(
      `invalid verdict shape from ${provider}: ${validationErrors(shape).join("; ")}`,
      {
        code: "INVALID_VERDICT_SHAPE",
        exitCode: EXIT_CODES.DATA,
        details: { peer: provider, errors: validationErrors(shape) }
      }
    );
  }
  const caps = validateVerdictCaps(verdict, { mode });
  if (!caps.ok) {
    throw new ConsensusError(
      `invalid verdict caps from ${provider}: ${JSON.stringify(validationMetadata(caps))}`,
      {
        code: "INVALID_VERDICT_CAPS",
        exitCode: EXIT_CODES.DATA,
        details: { peer: provider, ...validationMetadata(caps) }
      }
    );
  }
}
async function executeParallelRound(context) {
  const {
    options,
    records,
    currentArtifact,
    invokePeer,
    prompts = resolvePromptProfile()
  } = context;
  const mode = options.iteration;
  const peers = options.peers;
  const priorPeerTurns = peerTurnCount(records);
  const round = Math.floor(priorPeerTurns / peers.length) + 1;
  const baseTurn = priorPeerTurns;
  const previous = lastRoundPeerRecords(records, peers);
  const invocations = peers.map((provider, peerIndex) => {
    const ownRecord = previous[provider];
    const peerRecord = previous[peers[peerIndex === 0 ? 1 : 0]];
    const prompt = prompts.buildParallelTurnPrompt({
      provider,
      mode,
      coldStart: options.coldStart,
      round,
      turn: baseTurn + peerIndex + 1,
      goal: options.goal,
      artifact: currentArtifact,
      ownPreviousRevision: revisionTextFor(ownRecord),
      peerPreviousRevision: revisionTextFor(peerRecord),
      ownPreviousCritique: critiqueFor(ownRecord),
      peerPreviousCritique: critiqueFor(peerRecord)
    });
    return Promise.resolve(
      invokePeer({
        provider,
        peerIndex,
        round,
        turn: baseTurn + peerIndex + 1,
        prompt,
        artifact: currentArtifact
      })
    );
  });
  const settled = await Promise.allSettled(invocations);
  const failedIndex = settled.findIndex(
    (result) => result.status === "rejected"
  );
  if (failedIndex !== -1) {
    const failedPeer = peers[failedIndex];
    const cause = settled[failedIndex].reason;
    throw new ConsensusError(
      `peer subround failed: ${failedPeer} (${hardErrorMessage(cause)})`,
      {
        code: "PEER_SUBROUND_FAILED",
        exitCode: EXIT_CODES.CONFIG,
        cause,
        details: { failed_peer: failedPeer, round }
      }
    );
  }
  const peerResults = settled.map(
    (result) => result.value
  );
  const normalizedVerdicts = peerResults.map(
    (peerResult) => normalizeVerdict(peerResult.json, mode)
  );
  normalizedVerdicts.forEach((verdict, peerIndex) => {
    validatePeerVerdict(verdict, mode, peers[peerIndex]);
  });
  const recordsOut = peerResults.map((peerResult, peerIndex) => {
    const provider = peers[peerIndex];
    const verdict = normalizedVerdicts[peerIndex];
    const proposed = "proposed_artifact" in verdict ? verdict.proposed_artifact : currentArtifact;
    const recordPayload = {
      turn_index: baseTurn + peerIndex + 1,
      round_index: round,
      agent: provider,
      verdict: verdict.verdict,
      reasoning: verdict.reasoning,
      critique: verdict.critique,
      artifact_hash: hashArtifact(
        proposed,
        hashOptionsForAgency(options.agency)
      ),
      iteration_mode: mode,
      ...providerAuditFields(peerResult)
    };
    if (typeof verdict.proposed_artifact === "string") {
      recordPayload.proposed_artifact = verdict.proposed_artifact;
    }
    if (Array.isArray(verdict.concerns)) {
      recordPayload.concerns = verdict.concerns;
    }
    return recordPayload;
  });
  const nextArtifact = revisionTextFor(recordsOut.at(-1)) ?? currentArtifact;
  return {
    records: recordsOut,
    nextArtifact,
    verdicts: peerResults.map((result) => result.json)
  };
}
function priorUnresolvedDisagreements(records) {
  for (let index = records.length - 1; index >= 0; index -= 1) {
    const record = records[index];
    if (record?.record_type === "synthesis") {
      return Array.isArray(record.unresolved_disagreements) ? record.unresolved_disagreements.map(String) : [];
    }
  }
  return [];
}
function classifySynthesisFailure(synthesis, synthesizer) {
  const shape = validateSynthesisShape(synthesis);
  if (!shape.ok) {
    return {
      code: "INVALID_SYNTHESIS_SHAPE",
      message: `invalid synthesis shape from ${synthesizer}: ${validationErrors(shape).join("; ")}`,
      details: { synthesizer, errors: validationErrors(shape) },
      metadata: {
        code: "INVALID_SYNTHESIS_SHAPE",
        errors: validationErrors(shape)
      }
    };
  }
  const caps = validateSynthesisCaps(synthesis);
  if (!caps.ok) {
    return {
      code: "INVALID_SYNTHESIS_CAPS",
      message: `invalid synthesis caps from ${synthesizer}: ${JSON.stringify(validationMetadata(caps))}`,
      details: { synthesizer, ...validationMetadata(caps) },
      metadata: validationMetadata(caps)
    };
  }
  return null;
}
async function executeSynthesis({
  options,
  records,
  pairRecords,
  round,
  invokeSynthesizer,
  prompts = resolvePromptProfile()
}) {
  const synthesizer = options.synthesizer ?? options.peers[0];
  const [recordA, recordB] = pairRecords;
  const prompt = prompts.buildSynthesisPrompt({
    provider: synthesizer,
    round,
    goal: options.goal,
    revisionA: { agent: recordA.agent, text: revisionTextFor(recordA) },
    revisionB: { agent: recordB.agent, text: revisionTextFor(recordB) },
    critiqueA: critiqueFor(recordA),
    critiqueB: critiqueFor(recordB),
    priorUnresolved: priorUnresolvedDisagreements(records)
  });
  const synthResult = await invokeSynthesizer({
    provider: synthesizer,
    schemaPath: synthesisSchemaPath(),
    round,
    prompt
  });
  const synthesis = synthResult.json;
  const failure = classifySynthesisFailure(synthesis, synthesizer);
  if (failure) {
    const errorRecord = {
      record_type: "synthesis-error",
      round_index: round,
      synthesizer,
      code: failure.code,
      metadata: failure.metadata,
      iteration_mode: options.iteration
    };
    return {
      synthesisError: {
        record: errorRecord,
        error: new ConsensusError(failure.message, {
          code: failure.code,
          exitCode: EXIT_CODES.DATA,
          details: failure.details
        })
      }
    };
  }
  const synthesizedArtifact = synthesis.synthesized_artifact;
  const recordPayload = {
    record_type: "synthesis",
    round_index: round,
    synthesizer,
    synthesized_artifact: synthesizedArtifact,
    synthesis_reasoning: synthesis.synthesis_reasoning,
    unresolved_disagreements: synthesis.unresolved_disagreements,
    artifact_hash: hashArtifact(
      synthesizedArtifact,
      hashOptionsForAgency(options.agency)
    ),
    iteration_mode: options.iteration,
    ...providerAuditFields(synthResult)
  };
  return { synthesis: recordPayload, nextArtifact: synthesizedArtifact };
}
async function executeRound(context) {
  const { mode } = context;
  if (mode && PARALLEL_MODES.has(mode)) {
    const parallel = await executeParallelRound(context);
    if (mode === "parallel_synthesized") {
      const round = parallel.records[0]?.round_index;
      const synthesisResult = await executeSynthesis({
        options: context.options,
        records: context.records,
        pairRecords: parallel.records,
        round: Number(round),
        invokeSynthesizer: context.invokeSynthesizer,
        prompts: context.prompts
      });
      if (synthesisResult.synthesisError) {
        return { ...parallel, synthesisError: synthesisResult.synthesisError };
      }
      return {
        ...parallel,
        synthesis: synthesisResult.synthesis,
        nextArtifact: synthesisResult.nextArtifact
      };
    }
    return parallel;
  }
  const { verdict, recordPayload, nextArtifact } = await executeAlternatingTurn(
    context
  );
  return { records: [recordPayload], nextArtifact, verdicts: [verdict] };
}
const LEGACY_USER_STATUS = Object.freeze({
  oscillation: {
    status: "oscillation",
    termination_reason: "oscillation_detected"
  },
  budget_exhausted: {
    status: "max-rounds",
    termination_reason: "max_rounds_exhausted"
  }
});
function escalationTerminal({
  trigger,
  detected,
  options,
  records,
  artifact
}) {
  const route = routeEscalation(trigger, options.agency, records);
  const finalHash = hashArtifact(
    artifact,
    hashOptionsForAgency(options.agency)
  );
  if (route.decide_via === "auto") {
    const agencyDecision = trigger === ESCALATION_TRIGGERS.budget_exhausted ? "maximum_declared_done_at_max_rounds" : "maximum_near_match";
    const reason = trigger === ESCALATION_TRIGGERS.budget_exhausted ? "max_rounds_exhausted" : "near_done_drift";
    return {
      status: resultStatus("converged", reason, records, options, {
        final_artifact_hash: finalHash,
        agency_decision: agencyDecision
      }),
      artifact
    };
  }
  if (route.decide_via === "user" && trigger in LEGACY_USER_STATUS) {
    const legacy = LEGACY_USER_STATUS[trigger];
    return {
      status: resultStatus(
        legacy.status,
        legacy.termination_reason,
        records,
        options,
        {
          final_artifact_hash: finalHash
        }
      ),
      artifact
    };
  }
  const escalation = {
    trigger,
    decide_via: route.decide_via,
    decision_kinds: route.decision_kinds
  };
  if (route.promoted_from) {
    escalation.promoted_from = route.promoted_from;
  }
  if (detected?.divergent) {
    escalation.divergent = detected.divergent;
  }
  return {
    status: resultStatus(
      "escalation",
      `escalation_${trigger}`,
      records,
      options,
      {
        final_artifact_hash: finalHash,
        escalation
      }
    ),
    artifact
  };
}
function pendingSynthesisRound(records, peers) {
  const peerOnly = peerRecords(records).filter(
    (record) => record?.record_type !== "synthesis"
  );
  if (peerOnly.length === 0) return null;
  const latestRound = Math.max(
    ...peerOnly.map((record) => Number(record.round_index) || 0)
  );
  if (latestRound < 1) return null;
  const pairRecords = peerOnly.filter(
    (record) => Number(record.round_index) === latestRound
  );
  if (pairRecords.length < peers.length) return null;
  const hasSynthesis = records.some(
    (record) => record?.record_type === "synthesis" && Number(record.round_index) === latestRound
  );
  if (hasSynthesis) return null;
  return { round: latestRound, pairRecords: pairRecords.slice(-peers.length) };
}
function evaluateParallelTerminal({
  records,
  options,
  artifact
}) {
  const lastTwoPeers = peerRecords(records).filter((record) => record?.record_type !== "synthesis").slice(-2);
  const verdicts = lastTwoPeers.map((record) => verdictDecision(record));
  if (verdicts.includes("IMPASSE")) {
    return {
      status: resultStatus("impasse", "explicit_impasse", records, options, {
        final_artifact_hash: hashArtifact(
          artifact,
          hashOptionsForAgency(options.agency)
        )
      }),
      artifact
    };
  }
  const convergence = options.iteration === "parallel_synthesized" ? detectSynthesisStability(
    records,
    convergenceOptionsForAgency(options.agency)
  ) : detectParallelConvergence(
    records,
    convergenceOptionsForAgency(options.agency)
  );
  if (convergence.converged) {
    const statusExtra = {
      final_artifact_hash: convergence.artifact_hash
    };
    if (convergence.agency_decision) {
      statusExtra.agency_decision = convergence.agency_decision;
    }
    return {
      status: resultStatus(
        "converged",
        convergence.reason,
        records,
        options,
        statusExtra
      ),
      artifact
    };
  }
  const detected = detectEscalation(records, {
    mode: options.iteration,
    agency: options.agency
  });
  if (detected) {
    return escalationTerminal({
      trigger: detected.trigger,
      detected,
      options,
      records,
      artifact
    });
  }
  return null;
}
async function runParallelRounds({
  options,
  records,
  writer,
  currentArtifact,
  invokePeer,
  invokeSynthesizer,
  prompts = resolvePromptProfile(),
  budgetRefreshed = false
}) {
  let artifact = currentArtifact;
  if (options.iteration === "parallel_synthesized") {
    const pending = pendingSynthesisRound(records, options.peers);
    if (pending) {
      const synthesisResult = await executeSynthesis({
        options,
        records,
        pairRecords: pending.pairRecords,
        round: pending.round,
        invokeSynthesizer,
        prompts
      });
      if (synthesisResult.synthesisError) {
        const errorRecord = await writer.append({
          ...synthesisResult.synthesisError.record
        });
        records.push(errorRecord);
        throw synthesisResult.synthesisError.error;
      }
      const synthesisRecord = await writer.append({
        ...synthesisResult.synthesis
      });
      records.push(synthesisRecord);
      artifact = synthesisResult.nextArtifact;
      const terminal = evaluateParallelTerminal({ records, options, artifact });
      if (terminal) return terminal;
    }
  }
  const startRound = Math.floor(peerTurnCount(records) / options.peers.length);
  const roundBudget = budgetRefreshed ? startRound + options.maxRounds : options.maxRounds;
  for (let roundOffset = startRound; roundOffset < roundBudget; roundOffset += 1) {
    const { records: pair } = await executeParallelRound({
      mode: options.iteration,
      options,
      records,
      currentArtifact: artifact,
      invokePeer,
      prompts
    });
    const committedPair = [];
    for (const payload of pair) {
      const record = await writer.append({ ...payload });
      records.push(record);
      committedPair.push(record);
    }
    artifact = revisionTextFor(committedPair.at(-1)) ?? artifact;
    if (options.iteration === "parallel_synthesized") {
      const round = committedPair[0]?.round_index;
      const synthesisResult = await executeSynthesis({
        options,
        records,
        pairRecords: committedPair,
        round: Number(round),
        invokeSynthesizer,
        prompts
      });
      if (synthesisResult.synthesisError) {
        const errorRecord = await writer.append({
          ...synthesisResult.synthesisError.record
        });
        records.push(errorRecord);
        throw synthesisResult.synthesisError.error;
      }
      const synthesisRecord = await writer.append({
        ...synthesisResult.synthesis
      });
      records.push(synthesisRecord);
      artifact = synthesisResult.nextArtifact;
    }
    const terminal = evaluateParallelTerminal({ records, options, artifact });
    if (terminal) return terminal;
  }
  const budgetDetected = detectEscalation(records, {
    mode: options.iteration,
    agency: options.agency,
    budgetExhausted: true
  });
  return escalationTerminal({
    trigger: budgetDetected?.trigger ?? ESCALATION_TRIGGERS.budget_exhausted,
    detected: budgetDetected,
    options,
    records,
    artifact
  });
}
async function runConsensusLoop(argv, runOptions = {}) {
  const options = Array.isArray(argv) ? parseLoopArgs(argv) : argv;
  const initialRecords = runOptions.initialRecords ?? options.initialRecords ?? [];
  const records = await seedRecordsFile(
    options.outputRecords,
    initialRecords,
    runOptions
  );
  const writer = await createRecordsWriter(options.outputRecords, runOptions);
  let currentArtifact = runOptions.initialArtifact ?? options.initialArtifact ?? await readFile(options.sectionFile, "utf8");
  const initialPeerTurns = peerTurnCount(records);
  const intervention = await appendIntervention({
    writer,
    records,
    options,
    currentArtifact,
    intervention: resolveIntervention(runOptions, options)
  });
  const turnBudget = options.maxRounds * options.peers.length;
  const maxTurns = intervention ? initialPeerTurns + turnBudget : turnBudget;
  const env = runOptions.env ?? process.env;
  const cwd = runOptions.cwd ?? process.cwd();
  const invokePeer = runOptions.invokePeer ?? ((turn) => invokeProviderCliWithRetry(
    {
      provider: turn.provider,
      schemaPath: peerSchemaPathForMode(options.iteration),
      prompt: turn.prompt,
      env,
      cwd
    },
    { mode: options.iteration }
  ));
  const invokeSynthesizer = runOptions.invokeSynthesizer ?? ((call) => invokeConsensusProviderCli({
    provider: call.provider,
    schemaPath: call.schemaPath,
    prompt: call.prompt,
    env,
    cwd
  }));
  const prompts = resolvePromptProfile(runOptions.promptProfile);
  try {
    if (PARALLEL_MODES.has(options.iteration)) {
      const terminal = await runParallelRounds({
        options,
        records,
        writer,
        currentArtifact,
        invokePeer,
        invokeSynthesizer,
        prompts,
        budgetRefreshed: Boolean(intervention)
      });
      return await writeTerminalArtifacts(
        options,
        terminal.status,
        terminal.artifact,
        records
      );
    }
    for (let turnIndex = peerTurnCount(records); turnIndex < maxTurns; turnIndex += 1) {
      const { verdict, recordPayload, nextArtifact } = await executeAlternatingTurn({
        turnIndex,
        options,
        records,
        currentArtifact,
        invokePeer,
        prompts
      });
      currentArtifact = nextArtifact;
      const record = await writer.append({
        ...recordPayload
      });
      records.push(record);
      if (verdict.verdict === "IMPASSE") {
        const status = resultStatus(
          "impasse",
          "explicit_impasse",
          records,
          options,
          {
            final_artifact_hash: hashArtifact(
              currentArtifact,
              hashOptionsForAgency(options.agency)
            )
          }
        );
        return await writeTerminalArtifacts(
          options,
          status,
          currentArtifact,
          records
        );
      }
      const convergence = detectConvergence(
        records,
        convergenceOptionsForAgency(options.agency)
      );
      if (convergence.converged) {
        const statusExtra = {
          final_artifact_hash: convergence.artifact_hash
        };
        if (convergence.agency_decision) {
          statusExtra.agency_decision = convergence.agency_decision;
        }
        const status = resultStatus(
          "converged",
          convergence.reason,
          records,
          options,
          statusExtra
        );
        return await writeTerminalArtifacts(
          options,
          status,
          currentArtifact,
          records
        );
      }
      const oscillation = detectOscillation(
        records,
        convergenceOptionsForAgency(options.agency)
      );
      if (oscillation.oscillating) {
        const status = resultStatus(
          "oscillation",
          "oscillation_detected",
          records,
          options,
          {
            final_artifact_hash: hashArtifact(
              currentArtifact,
              hashOptionsForAgency(options.agency)
            )
          }
        );
        return await writeTerminalArtifacts(
          options,
          status,
          currentArtifact,
          records
        );
      }
    }
    const maxRoundsStatus = options.agency === "maximum" ? resultStatus("converged", "max_rounds_exhausted", records, options, {
      final_artifact_hash: hashArtifact(
        currentArtifact,
        hashOptionsForAgency(options.agency)
      ),
      agency_decision: "maximum_declared_done_at_max_rounds"
    }) : resultStatus("max-rounds", "max_rounds_exhausted", records, options, {
      final_artifact_hash: hashArtifact(
        currentArtifact,
        hashOptionsForAgency(options.agency)
      )
    });
    return await writeTerminalArtifacts(
      options,
      maxRoundsStatus,
      currentArtifact,
      records
    );
  } catch (error) {
    const status = resultStatus("error", "hard_error", records, options, {
      final_artifact_hash: hashArtifact(
        currentArtifact,
        hashOptionsForAgency(options.agency)
      ),
      error: hardErrorMessage(error)
    });
    await writeLoopStatus(options.outputStatus, status);
    throw error;
  } finally {
    await writer.close();
  }
}
function detectConvergence(records, options = {}) {
  if (!Array.isArray(records) || records.length < 2) {
    return { converged: false, reason: null };
  }
  const rightIndex = records.length - 1;
  const leftIndex = records.length - 2;
  const left = records[leftIndex];
  const right = records[rightIndex];
  const leftHash = recordHash(left, options);
  const rightHash = recordHash(right, options);
  const leftDecision = verdictDecision(left);
  const rightDecision = verdictDecision(right);
  const doubleAccept = leftDecision === "ACCEPT" && rightDecision === "ACCEPT";
  if (!leftHash || !rightHash) {
    return { converged: false, reason: null };
  }
  if (leftHash !== rightHash) {
    if (options.agency === "maximum" && doubleAccept) {
      return {
        converged: true,
        reason: "double_accept",
        record_indexes: [leftIndex, rightIndex],
        artifact_hash: rightHash,
        agency_decision: "maximum_double_accept_near_match"
      };
    }
    return { converged: false, reason: null };
  }
  const reason = doubleAccept ? "double_accept" : "hash_match";
  return {
    converged: true,
    reason,
    record_indexes: [leftIndex, rightIndex],
    artifact_hash: rightHash
  };
}
function detectOscillation(records, options = {}) {
  if (!Array.isArray(records) || records.length < 4) {
    return { oscillating: false, reason: null };
  }
  for (let end = records.length; end >= 4; end -= 1) {
    const window = records.slice(end - 4, end);
    const hashes = window.map((record) => recordHash(record, options));
    if (hashes.every(Boolean) && hashes[0] === hashes[2] && hashes[1] === hashes[3] && hashes[0] !== hashes[1]) {
      return {
        oscillating: true,
        reason: "oscillation_detected",
        record_indexes: [end - 4, end - 3, end - 2, end - 1],
        hashes: [hashes[0], hashes[1]]
      };
    }
  }
  return { oscillating: false, reason: null };
}
function parallelRevisionHash(record, options = {}) {
  const hashOptions = options.hashOptions ?? hashOptionsForAgency(options.agency);
  if (typeof record?.proposed_artifact === "string") {
    return hashArtifact(record.proposed_artifact, hashOptions);
  }
  return recordHash(record, options);
}
function detectParallelConvergence(records, options = {}) {
  if (!Array.isArray(records) || records.length < 2) {
    return { converged: false, reason: null };
  }
  const rightIndex = records.length - 1;
  const leftIndex = records.length - 2;
  const left = records[leftIndex];
  const right = records[rightIndex];
  const agency = options.agency ?? "moderate";
  const leftDecision = verdictDecision(left);
  const rightDecision = verdictDecision(right);
  const leftHash = parallelRevisionHash(left, options);
  const rightHash = parallelRevisionHash(right, options);
  const hashMatch = Boolean(leftHash) && leftHash === rightHash;
  const mutualAcceptPeer = leftDecision === "ACCEPT_PEER" && rightDecision === "ACCEPT_PEER";
  if (mutualAcceptPeer) {
    if (hashMatch) {
      return {
        converged: true,
        reason: "mutual_accept_peer",
        record_indexes: [leftIndex, rightIndex],
        artifact_hash: rightHash
      };
    }
    return { converged: false, reason: null };
  }
  if (hashMatch) {
    return {
      converged: true,
      reason: "parallel_hash_match",
      record_indexes: [leftIndex, rightIndex],
      artifact_hash: rightHash
    };
  }
  if (leftDecision === "CONVERGED" && rightDecision === "CONVERGED") {
    if (agency === "moderate" || agency === "maximum") {
      return {
        converged: true,
        reason: "mutual_converged",
        record_indexes: [leftIndex, rightIndex],
        artifact_hash: rightHash
      };
    }
    return { converged: false, reason: null };
  }
  return { converged: false, reason: null };
}
function detectSynthesisStability(records, options = {}) {
  if (!Array.isArray(records) || records.length < 2) {
    return { converged: false, reason: null };
  }
  const isPeer = (record) => record?.record_type !== "synthesis" && record?.agent !== "user" && record?.agent !== "host-orchestrator";
  let latestPeerRound = null;
  for (let index = records.length - 1; index >= 0; index -= 1) {
    if (isPeer(records[index]) && Number.isInteger(Number(records[index].round_index))) {
      latestPeerRound = Number(records[index].round_index);
      break;
    }
  }
  if (latestPeerRound === null || latestPeerRound < 2) {
    return { converged: false, reason: null };
  }
  const currentPeers = records.filter(
    (record) => isPeer(record) && Number(record.round_index) === latestPeerRound
  );
  if (currentPeers.length < 2) {
    return { converged: false, reason: null };
  }
  const priorSynthesis = records.find(
    (record) => record?.record_type === "synthesis" && Number(record.round_index) === latestPeerRound - 1
  );
  if (!priorSynthesis) {
    return { converged: false, reason: null };
  }
  const synthHash = parallelRevisionHash(priorSynthesis, options);
  if (!synthHash) {
    return { converged: false, reason: null };
  }
  const allMatch = currentPeers.every(
    (record) => parallelRevisionHash(record, options) === synthHash
  );
  if (!allMatch) {
    return { converged: false, reason: null };
  }
  return {
    converged: true,
    reason: "synthesis_stability",
    synthesis_round: latestPeerRound - 1,
    artifact_hash: synthHash
  };
}
function parallelRoundPairs(records, options = {}) {
  const byRound = /* @__PURE__ */ new Map();
  for (const record of records) {
    if (record?.agent === "user" || record?.agent === "host-orchestrator")
      continue;
    if (record?.record_type === "synthesis") continue;
    const round = Number(record?.round_index);
    if (!Number.isInteger(round)) continue;
    if (!byRound.has(round)) byRound.set(round, []);
    byRound.get(round)?.push(parallelRevisionHash(record, options));
  }
  return [...byRound.keys()].toSorted((a, b) => a - b).map((round) => {
    const hashes = (byRound.get(round) ?? []).filter(Boolean).toSorted();
    return hashes.length > 0 ? hashes.join("|") : null;
  });
}
function detectParallelOscillation(records, options = {}) {
  if (!Array.isArray(records)) {
    return { oscillating: false, reason: null };
  }
  const pairs = parallelRoundPairs(records, options);
  for (let end = pairs.length; end >= 4; end -= 1) {
    const window = pairs.slice(end - 4, end);
    if (window.every(Boolean) && window[0] === window[2] && window[1] === window[3] && window[0] !== window[1]) {
      return {
        oscillating: true,
        reason: "oscillation_detected",
        round_indexes: [end - 4, end - 3, end - 2, end - 1],
        pairs: [window[0], window[1]]
      };
    }
  }
  return { oscillating: false, reason: null };
}
const ESCALATION_TRIGGERS = Object.freeze({
  persistent_disagreement: "persistent_disagreement",
  oscillation: "oscillation",
  budget_exhausted: "budget_exhausted",
  near_done_drift: "near_done_drift"
});
const PERSISTENT_DISAGREEMENT_WINDOW = 3;
function synthesisRecords(records) {
  return records.filter((record) => record?.record_type === "synthesis");
}
function normalizedDisagreementSet(record) {
  const list = Array.isArray(record?.unresolved_disagreements) ? record.unresolved_disagreements : [];
  return new Set(
    list.map((entry) => String(entry).trim()).filter(Boolean)
  );
}
function sameDisagreementSet(a, b) {
  if (a.size !== b.size) return false;
  for (const value of a) {
    if (!b.has(value)) return false;
  }
  return true;
}
function detectPersistentDisagreement(records) {
  const synth = synthesisRecords(records);
  if (synth.length < PERSISTENT_DISAGREEMENT_WINDOW) return null;
  const window = synth.slice(-PERSISTENT_DISAGREEMENT_WINDOW);
  const sets = window.map(normalizedDisagreementSet);
  if (sets.some((set) => set.size === 0)) return null;
  for (let index = 1; index < sets.length; index += 1) {
    if (!sameDisagreementSet(sets[0], sets[index])) return null;
  }
  const latest = window.at(-1);
  if (!latest) return null;
  return {
    trigger: ESCALATION_TRIGGERS.persistent_disagreement,
    disagreements: [...sets[0]],
    synthesis_round: latest.round_index ?? null,
    divergent: {
      synthesis: {
        artifact_hash: recordHash(latest),
        unresolved_disagreements: Array.isArray(latest.unresolved_disagreements) ? latest.unresolved_disagreements : []
      }
    }
  };
}
function lastTwoParallelPeers(records) {
  const peers = records.filter(
    (record) => record?.agent !== "user" && record?.agent !== "host-orchestrator" && record?.verdict !== "USER_INTERVENTION" && record?.verdict !== "HOST_DECISION" && record?.record_type !== "synthesis" && record?.record_type !== "synthesis-error"
  );
  return peers.slice(-2);
}
function divergentPairRefs(left, right, options = {}) {
  return {
    a: { agent: left?.agent ?? null, artifact_hash: recordHash(left, options) },
    b: {
      agent: right?.agent ?? null,
      artifact_hash: recordHash(right, options)
    }
  };
}
function detectNearDoneDrift(records, options = {}) {
  const [left, right] = lastTwoParallelPeers(records);
  if (!left || !right) return null;
  const leftDecision = verdictDecision(left);
  const rightDecision = verdictDecision(right);
  const doubleAccept = leftDecision === "ACCEPT" && rightDecision === "ACCEPT";
  const mutualConverged = leftDecision === "CONVERGED" && rightDecision === "CONVERGED";
  if (!doubleAccept && !mutualConverged) return null;
  const leftHash = recordHash(left, options);
  const rightHash = recordHash(right, options);
  if (!leftHash || !rightHash || leftHash === rightHash) return null;
  return {
    trigger: ESCALATION_TRIGGERS.near_done_drift,
    divergent: divergentPairRefs(left, right, options)
  };
}
function detectBudgetExhausted(records, options = {}) {
  const [left, right] = lastTwoParallelPeers(records);
  return {
    trigger: ESCALATION_TRIGGERS.budget_exhausted,
    divergent: left && right ? divergentPairRefs(left, right, options) : void 0
  };
}
function detectOscillationTrigger(records, mode, options = {}) {
  const oscillation = PARALLEL_MODES.has(mode) ? detectParallelOscillation(records, options) : detectOscillation(records, options);
  if (!oscillation.oscillating) return null;
  const [left, right] = lastTwoParallelPeers(records);
  return {
    trigger: ESCALATION_TRIGGERS.oscillation,
    divergent: left && right ? divergentPairRefs(left, right, options) : void 0
  };
}
function detectEscalation(records, {
  mode = "alternating",
  agency = "moderate",
  budgetExhausted = false
} = {}) {
  if (!Array.isArray(records) || records.length === 0) return null;
  const options = convergenceOptionsForAgency(agency);
  if (mode === "parallel_synthesized") {
    const persistent = detectPersistentDisagreement(records);
    if (persistent) return persistent;
  }
  const oscillation = detectOscillationTrigger(records, mode, options);
  if (oscillation) return oscillation;
  const nearDone = detectNearDoneDrift(records, options);
  if (nearDone) return nearDone;
  if (budgetExhausted) {
    return detectBudgetExhausted(records, options);
  }
  return null;
}
const ESCALATION_ROUTING_TABLE = Object.freeze({
  [ESCALATION_TRIGGERS.persistent_disagreement]: {
    minimal: "user",
    moderate: "host",
    maximum: "host"
  },
  [ESCALATION_TRIGGERS.oscillation]: {
    minimal: "user",
    moderate: "user",
    maximum: "host"
  },
  [ESCALATION_TRIGGERS.budget_exhausted]: {
    minimal: "user",
    moderate: "user",
    maximum: "auto"
  },
  [ESCALATION_TRIGGERS.near_done_drift]: {
    minimal: "user",
    moderate: "host",
    maximum: "auto"
  }
});
const BASE_DECISION_KINDS = Object.freeze([
  "pick_a",
  "pick_b",
  "blend",
  "direct",
  "accept_impasse",
  "extend_budget"
]);
function decisionKindsFor(decideVia) {
  return decideVia === "host" ? [...BASE_DECISION_KINDS, "defer_to_user"] : [...BASE_DECISION_KINDS];
}
function priorHostDecisionForTrigger(records, trigger) {
  if (!Array.isArray(records)) return null;
  for (let index = records.length - 1; index >= 0; index -= 1) {
    const record = records[index];
    if (record?.verdict === "HOST_DECISION" && record?.escalation_trigger === trigger) {
      return record;
    }
  }
  return null;
}
function routeEscalation(trigger, agency = "moderate", records = []) {
  const row = ESCALATION_ROUTING_TABLE[trigger];
  if (!row) {
    throw new ConsensusError(`unknown escalation trigger: ${trigger}`, {
      code: "ESCALATION_ROUTING",
      exitCode: EXIT_CODES.CONFIG,
      details: { trigger, agency }
    });
  }
  const baseDecideVia = row[agency] ?? "user";
  if (baseDecideVia === "auto") {
    const route = {
      trigger,
      agency,
      decide_via: "auto",
      decision_kinds: []
    };
    if (trigger === ESCALATION_TRIGGERS.budget_exhausted) {
      route.auto_resolution = "declare_done";
    } else if (trigger === ESCALATION_TRIGGERS.near_done_drift) {
      route.auto_resolution = "near_match";
    }
    return route;
  }
  if (baseDecideVia === "host") {
    const priorHostDecision = priorHostDecisionForTrigger(records, trigger);
    const deferred = priorHostDecision?.decision_kind === "defer_to_user";
    if (priorHostDecision) {
      return {
        trigger,
        agency,
        decide_via: "user",
        promoted_from: "host",
        promotion_reason: deferred ? "defer_to_user" : "repeat_fire",
        decision_kinds: decisionKindsFor("user")
      };
    }
    return {
      trigger,
      agency,
      decide_via: "host",
      decision_kinds: decisionKindsFor("host")
    };
  }
  return {
    trigger,
    agency,
    decide_via: "user",
    decision_kinds: decisionKindsFor("user")
  };
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  runConsensusLoop(process.argv.slice(2)).catch((error) => {
    process.stderr.write(`${hardErrorMessage(error)}
`);
    process.exitCode = exitCodeForError(error);
  });
}
export {
  COLD_START_MODES,
  CONSENSUS_SHARED_CLI_RELATIVE_PATH,
  ConsensusError,
  ESCALATION_TRIGGERS,
  EXIT_CODES,
  ITERATION_MODES,
  LOOP_SCHEMA_VERSION,
  PROVIDER_CLI_FINAL_RESOLUTION_MS,
  PROVIDER_CLI_KILL_GRACE_MS,
  SUBPROCESS_OUTPUT_CAP_BYTES,
  SYNTHESIS_CAPS,
  VERDICT_CAPS,
  buildParallelTurnPrompt,
  buildSynthesisPrompt,
  buildTurnPrompt,
  callsPerRound,
  consensusProviderCliMissingError,
  consensusSharedCliPath,
  createRecordsWriter,
  detectConvergence,
  detectEscalation,
  detectOscillation,
  detectParallelConvergence,
  detectParallelOscillation,
  detectSynthesisStability,
  executeRound,
  exitCodeForError,
  hashArtifact,
  invalidIterationModeError,
  invokeConsensusProviderCli,
  invokeProviderCliWithRetry,
  invokeValidatedPeer,
  normalizeForHash,
  normalizeVerdict,
  parallelSchemaPath,
  parseLoopArgs,
  peerSchemaPathForMode,
  providerCliSpawnTarget,
  requireConsensusCliPath,
  resolveConsensusCliPath,
  resolveConsensusCliPathDetails,
  routeEscalation,
  runConsensusLoop,
  runProviderCliCommand,
  synthesisSchemaPath,
  validateSynthesisCaps,
  validateSynthesisShape,
  validateVerdictCaps,
  validateVerdictShape,
  writeLoopStatus
};
