#!/usr/bin/env node
// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/consensus/provider-cli/cli.ts

// src/consensus/provider-cli/cli.ts
import { readFile } from "node:fs/promises";

// src/consensus/provider-cli/args.ts
var ConsensusCliUsageError = class extends Error {
  code = "CONSENSUS_CLI_USAGE";
  details;
  constructor(message, details) {
    super(message);
    this.name = "ConsensusCliUsageError";
    this.details = details;
  }
};
function parseConsensusCliArgs(argv) {
  const tokens = [...argv];
  const command = tokens.shift();
  if (!command || command === "--help" || command === "-h") {
    requireNoExtraTokens(tokens);
    return { kind: "help" };
  }
  if (command === "provider") {
    return parseProviderCommand(tokens);
  }
  if (command === "preflight") {
    return parsePreflightCommand(tokens);
  }
  if (command === "run") {
    return parseRunCommand(tokens);
  }
  throw new ConsensusCliUsageError(`Unknown command: ${command}`);
}
function parseProviderCommand(tokens) {
  const [subcommand, ...rest] = tokens;
  if (subcommand !== "ls") {
    throw new ConsensusCliUsageError(
      "Expected provider subcommand: provider ls --json"
    );
  }
  const parsed = parseOptionTokens(rest, {
    allowedFlags: /* @__PURE__ */ new Set(["--json"]),
    valueFlags: /* @__PURE__ */ new Set()
  });
  requireJson(parsed.flags);
  requireNoPositionals(parsed.positionals);
  return { kind: "provider-list", json: true };
}
function parsePreflightCommand(tokens) {
  const parsed = parseOptionTokens(tokens, {
    allowedFlags: /* @__PURE__ */ new Set(["--json", "--provider", "--max-depth"]),
    valueFlags: /* @__PURE__ */ new Set(["--provider", "--max-depth"])
  });
  requireJson(parsed.flags);
  requireNoPositionals(parsed.positionals);
  const command = {
    kind: "preflight",
    json: true
  };
  const provider = singleValue(parsed.flags, "--provider");
  if (provider) command.provider = provider;
  const maxDepth = singleValue(parsed.flags, "--max-depth");
  if (maxDepth) {
    command.maxDepth = parsePositiveInteger("--max-depth", maxDepth);
  }
  return command;
}
function parseRunCommand(tokens) {
  const parsed = parseOptionTokens(tokens, {
    allowedFlags: /* @__PURE__ */ new Set([
      "--json",
      "--provider",
      "--schema",
      "--prompt",
      "--prompt-file",
      "--request-json",
      "--max-attempts",
      "--timeout-sec",
      "--max-output-bytes",
      "--model",
      "--effort",
      "--cwd"
    ]),
    valueFlags: /* @__PURE__ */ new Set([
      "--provider",
      "--schema",
      "--prompt",
      "--prompt-file",
      "--request-json",
      "--max-attempts",
      "--timeout-sec",
      "--max-output-bytes",
      "--model",
      "--effort",
      "--cwd"
    ])
  });
  requireJson(parsed.flags);
  const command = {
    kind: "run",
    json: true
  };
  command.provider = singleValue(parsed.flags, "--provider");
  command.schemaPath = singleValue(parsed.flags, "--schema");
  command.requestJson = singleValue(parsed.flags, "--request-json");
  command.model = singleValue(parsed.flags, "--model");
  command.effort = singleValue(parsed.flags, "--effort");
  command.cwd = singleValue(parsed.flags, "--cwd");
  const prompt = singleValue(parsed.flags, "--prompt");
  const promptFile = singleValue(parsed.flags, "--prompt-file");
  const stdinMarkers = parsed.positionals.filter((value) => value === "-");
  const unknownPositionals = parsed.positionals.filter((value) => value !== "-");
  if (unknownPositionals.length > 0) {
    throw new ConsensusCliUsageError(
      `Unexpected positional argument: ${unknownPositionals[0]}`
    );
  }
  const promptSources = [
    prompt === void 0 ? void 0 : { kind: "prompt", value: prompt },
    promptFile === void 0 ? void 0 : { kind: "file", path: promptFile },
    ...stdinMarkers.map(() => ({ kind: "stdin" }))
  ].filter((source) => source !== void 0);
  if (promptSources.length > 1) {
    throw new ConsensusCliUsageError("Use only one prompt source");
  }
  command.promptSource = promptSources[0];
  const maxAttempts = singleValue(parsed.flags, "--max-attempts");
  if (maxAttempts) {
    command.maxAttempts = parsePositiveInteger("--max-attempts", maxAttempts);
  }
  const timeoutSec = singleValue(parsed.flags, "--timeout-sec");
  if (timeoutSec) {
    command.timeoutSec = parsePositiveInteger("--timeout-sec", timeoutSec);
  }
  const maxOutputBytes = singleValue(parsed.flags, "--max-output-bytes");
  if (maxOutputBytes) {
    command.maxOutputBytes = parsePositiveInteger(
      "--max-output-bytes",
      maxOutputBytes
    );
  }
  if (command.requestJson) {
    assertNoRequestJsonConflicts(command, parsed.positionals.length);
  }
  return command;
}
function assertNoRequestJsonConflicts(command, positionalCount) {
  const conflicts = [
    command.provider ? "--provider" : void 0,
    command.schemaPath ? "--schema" : void 0,
    command.promptSource ? "prompt source" : void 0,
    command.maxAttempts !== void 0 ? "--max-attempts" : void 0,
    command.timeoutSec !== void 0 ? "--timeout-sec" : void 0,
    command.maxOutputBytes !== void 0 ? "--max-output-bytes" : void 0,
    command.model ? "--model" : void 0,
    command.effort ? "--effort" : void 0,
    command.cwd ? "--cwd" : void 0,
    positionalCount > 0 ? "positional prompt" : void 0
  ].filter(Boolean);
  if (conflicts.length > 0) {
    throw new ConsensusCliUsageError(
      `--request-json cannot be combined with request-shaping flags: ${conflicts.join(", ")}`
    );
  }
}
function parseOptionTokens(tokens, spec) {
  const flags = /* @__PURE__ */ new Map();
  const positionals = [];
  for (let index = 0; index < tokens.length; index += 1) {
    const token = tokens[index];
    if (!token.startsWith("--")) {
      positionals.push(token);
      continue;
    }
    const [flag, inlineValue] = splitFlag(token);
    if (!spec.allowedFlags.has(flag)) {
      throw new ConsensusCliUsageError(`Unknown flag: ${flag}`);
    }
    if (!spec.valueFlags.has(flag)) {
      if (inlineValue !== void 0) {
        throw new ConsensusCliUsageError(`${flag} does not accept a value`);
      }
      pushFlag(flags, flag, "true");
      continue;
    }
    const value = inlineValue ?? tokens[index + 1];
    if (value === void 0 || value.startsWith("--")) {
      throw new ConsensusCliUsageError(`${flag} requires a value`);
    }
    if (inlineValue === void 0) index += 1;
    pushFlag(flags, flag, value);
  }
  return { flags, positionals };
}
function splitFlag(token) {
  const equalsIndex = token.indexOf("=");
  if (equalsIndex === -1) return [token, void 0];
  return [token.slice(0, equalsIndex), token.slice(equalsIndex + 1)];
}
function pushFlag(flags, flag, value) {
  const values = flags.get(flag) ?? [];
  values.push(value);
  flags.set(flag, values);
}
function singleValue(flags, flag) {
  const values = flags.get(flag);
  if (!values || values.length === 0) return void 0;
  if (values.length > 1) {
    throw new ConsensusCliUsageError(`${flag} can only be provided once`);
  }
  return values[0];
}
function requireJson(flags) {
  if (!flags.has("--json")) {
    throw new ConsensusCliUsageError("Missing required --json flag");
  }
}
function requireNoPositionals(positionals) {
  if (positionals.length > 0) {
    throw new ConsensusCliUsageError(
      `Unexpected positional argument: ${positionals[0]}`
    );
  }
}
function requireNoExtraTokens(tokens) {
  if (tokens.length > 0) {
    throw new ConsensusCliUsageError(`Unexpected argument: ${tokens[0]}`);
  }
}
function parsePositiveInteger(flag, value) {
  if (!/^[1-9]\d*$/.test(value)) {
    throw new ConsensusCliUsageError(`${flag} must be a positive integer`);
  }
  return Number(value);
}

// src/consensus/provider-cli/envelope.ts
function failureEnvelope(input) {
  const envelope = {
    schema_version: "v1",
    ok: false,
    code: input.code,
    message: input.message,
    retryable: input.retryable,
    attempts: buildAttemptSummary(
      {
        ...input.attempts,
        terminal_reason: input.terminal_reason ?? input.attempts?.terminal_reason
      },
      input.retryable
    )
  };
  if (input.provider) envelope.provider = input.provider;
  if (input.stdout !== void 0) envelope.stdout = input.stdout;
  if (input.stderr !== void 0) envelope.stderr = input.stderr;
  if (input.diagnostics) envelope.diagnostics = input.diagnostics;
  return envelope;
}
function usageFailure(message, details) {
  const diagnostics = details === void 0 ? void 0 : { warnings: [JSON.stringify(details)] };
  return failureEnvelope({
    code: "CONSENSUS_CLI_USAGE",
    message,
    retryable: false,
    attempts: {
      cli_attempts: 0,
      terminal_reason: "usage"
    },
    diagnostics
  });
}
function processExitForEnvelope(envelope) {
  if (envelope.ok) return 0;
  if (envelope.code === "CONSENSUS_CLI_USAGE") return 2;
  return 0;
}
function buildAttemptSummary(attempts, retryable) {
  return {
    cli_attempts: attempts?.cli_attempts ?? 1,
    ...attempts?.provider_internal_attempts === void 0 ? {} : { provider_internal_attempts: attempts.provider_internal_attempts },
    ...attempts?.terminal_reason === void 0 ? {} : { terminal_reason: attempts.terminal_reason },
    retryable
  };
}

// src/consensus/provider-cli/cli.ts
function helpText() {
  return `Usage: consensus <command> --json

Commands:
  provider ls --json
  preflight --json [--provider <id>] [--max-depth <n>]
  run --provider <id> --schema <path> --json [-|--prompt <text>|--prompt-file <path>]
  run --request-json <path|-> --json
`;
}
async function runConsensusCli(argv = process.argv.slice(2), io = nodeIo()) {
  try {
    const command = parseConsensusCliArgs(argv);
    if (command.kind === "help") {
      io.stdout.write(helpText());
      return 0;
    }
    const envelope = usageFailure(
      `Command is not implemented yet: ${command.kind}`
    );
    writeEnvelope(io, envelope);
    return processExitForEnvelope(envelope);
  } catch (error) {
    if (error instanceof ConsensusCliUsageError) {
      const envelope = usageFailure(error.message, error.details);
      writeEnvelope(io, envelope);
      return processExitForEnvelope(envelope);
    }
    io.stderr.write(
      `${error instanceof Error ? error.message : String(error)}
`
    );
    return 1;
  }
}
function writeEnvelope(io, envelope) {
  io.stdout.write(`${JSON.stringify(envelope)}
`);
}
function nodeIo() {
  return {
    stdout: process.stdout,
    stderr: process.stderr,
    stdin: process.stdin,
    cwd: process.cwd(),
    readFile: (filePath) => readFile(filePath, "utf8"),
    readStdin: () => readAllStdin(process.stdin)
  };
}
function readAllStdin(stdin) {
  stdin.setEncoding("utf8");
  return new Promise((resolve, reject) => {
    let value = "";
    stdin.on("data", (chunk) => {
      value += chunk;
    });
    stdin.on("error", reject);
    stdin.on("end", () => {
      resolve(value);
    });
    stdin.resume();
  });
}
if (process.argv[1] && import.meta.url === new URL(process.argv[1], "file:").href) {
  runConsensusCli().then((code) => {
    process.exitCode = code;
  });
}
export {
  helpText,
  runConsensusCli,
  writeEnvelope
};
