// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/consensus/core/loop-records.ts
import {
  mkdir,
  open,
  readFile,
  rename,
  unlink,
  writeFile
} from "node:fs/promises";
import path from "node:path";
import {
  asErrorLike,
  formatArtifactHash,
  LOOP_SCHEMA_VERSION
} from './loop-validation.mjs';
function timestamp(options = {}) {
  return options.now?.() ?? (/* @__PURE__ */ new Date()).toISOString();
}
function withRecordMetadata(record, options = {}) {
  const entry = {
    schema_version: LOOP_SCHEMA_VERSION,
    ...record
  };
  if (!entry.timestamp) {
    entry.timestamp = timestamp(options);
  }
  return entry;
}
async function readExistingRecords(recordsPath) {
  try {
    const parsed = JSON.parse(await readFile(recordsPath, "utf8"));
    if (!Array.isArray(parsed)) {
      throw new Error("records file must contain a JSON array");
    }
    return parsed;
  } catch (error) {
    if (asErrorLike(error).code === "ENOENT") return [];
    throw error;
  }
}
async function syncFileIfAvailable(filePath) {
  let handle;
  try {
    handle = await open(filePath, "r");
    await handle.sync();
  } finally {
    await handle?.close();
  }
}
async function atomicWriteFile(targetPath, data) {
  const tmpPath = `${targetPath}.${process.pid}.tmp`;
  try {
    await writeFile(tmpPath, data);
    await syncFileIfAvailable(tmpPath);
    await rename(tmpPath, targetPath);
  } catch (error) {
    try {
      await unlink(tmpPath);
    } catch {
    }
    throw error;
  }
}
function normalizeCost(status) {
  const source = status.cost_source ?? status.cost?.source ?? "unavailable";
  const normalized = ["provider_cli", "estimated", "unavailable"].includes(
    source
  ) ? source : "unavailable";
  const costUsd = status.approximate_cost_usd ?? status.cost_usd ?? status.cost?.usd;
  if (normalized === "unavailable" || typeof costUsd !== "number") {
    return { cost_source: normalized };
  }
  return { cost_source: normalized, approximate_cost_usd: costUsd };
}
async function createRecordsWriter(recordsPath, options = {}) {
  await mkdir(path.dirname(recordsPath), { recursive: true });
  const records = await readExistingRecords(recordsPath);
  async function flush() {
    await atomicWriteFile(recordsPath, `${JSON.stringify(records, null, 2)}
`);
  }
  if (records.length === 0) {
    await flush();
  }
  return {
    path: recordsPath,
    async append(record) {
      const entry = withRecordMetadata(record, options);
      records.push(entry);
      await flush();
      return entry;
    },
    async close() {
      await flush();
    }
  };
}
async function writeLoopStatus(statusPath, status, _options = {}) {
  await mkdir(path.dirname(statusPath), { recursive: true });
  const reserved = /* @__PURE__ */ new Set([
    "schema_version",
    "status",
    "termination_reason",
    "turns",
    "rounds",
    "final_artifact_hash",
    "artifact_hash",
    "cost",
    "cost_source",
    "cost_usd",
    "approximate_cost_usd"
  ]);
  const normalizedStatus = {
    schema_version: LOOP_SCHEMA_VERSION,
    status: status.status,
    termination_reason: status.termination_reason ?? null,
    turns: status.turns ?? 0,
    rounds: status.rounds ?? 0,
    final_artifact_hash: formatArtifactHash(
      status.final_artifact_hash ?? status.artifact_hash
    )
  };
  for (const [key, value] of Object.entries(status)) {
    if (!reserved.has(key)) {
      normalizedStatus[key] = value;
    }
  }
  Object.assign(normalizedStatus, normalizeCost(status));
  await atomicWriteFile(
    statusPath,
    `${JSON.stringify(normalizedStatus, null, 2)}
`
  );
  return normalizedStatus;
}
function peerRecords(records) {
  return records.filter(
    (record) => record?.agent !== "user" && record?.verdict !== "USER_INTERVENTION" && record?.record_type !== "synthesis-error"
  );
}
function peerTurnCount(records) {
  return peerRecords(records).length;
}
function synthesisRecordCount(records) {
  return records.filter((record) => record?.record_type === "synthesis").length;
}
export {
  createRecordsWriter,
  peerRecords,
  peerTurnCount,
  readExistingRecords,
  syncFileIfAvailable,
  synthesisRecordCount,
  withRecordMetadata,
  writeLoopStatus
};
