// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/transcript/session-observer/lib/locate.ts
import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import {
  opendir,
  stat,
  mkdir,
  readFile,
  realpath,
  rename,
  open,
  unlink
} from "node:fs/promises";
import { homedir } from "node:os";
import { join, basename, isAbsolute, relative, resolve } from "node:path";
import { promisify } from "node:util";
import {
  discoverPaths,
  encodeCwdVariants,
  extractClaudeRecordedCwdFromRecords,
  extractMeta,
  extractMetaFromRecords,
  readMetadataRecordsBounded,
  readRecords
} from './runtimes.mjs';
import {
  classifyTranscriptRecords,
  engagementCandidateFields
} from './session-classifier.mjs';
const execFileAsync = promisify(execFile);
const LOOKBACK_DAYS = 7;
const EXACT_ALL_DISCOVERY_BUDGET = {
  maxEntries: 5e4,
  maxAggregateBytes: 512 * 1024 * 1024,
  maxMetadataBytesPerEntry: 256 * 1024,
  deadlineMs: 3e4
};
const EXACT_ALL_METADATA_MAX_RECORDS = 128;
const CURSOR_IDENTITY_INDEX_MAX_ENTRIES = 2e4;
const CURSOR_IDENTITY_INDEX_MAX_ELAPSED_MS = 2e3;
const CURSOR_DISCOVERY_MAX_ENTRIES = 2e4;
const CURSOR_DISCOVERY_MAX_ELAPSED_MS = 2e3;
const CURSOR_DISCOVERY_MAX_BYTES = 64 * 1024 * 1024;
const CURSOR_DISCOVERY_MAX_RETAINED_CANDIDATES = 5e3;
class SessionDiscoveryError extends Error {
  code;
  constructor(code) {
    super(code);
    this.name = "SessionDiscoveryError";
    this.code = code;
  }
}
class ExactAllDiscoveryBudget {
  constructor(limits, runtime, diagnostic) {
    this.limits = limits;
    this.runtime = runtime;
    this.diagnostic = diagnostic;
  }
  limits;
  runtime;
  diagnostic;
  startedAt = Date.now();
  entries = 0;
  aggregateBytes = 0;
  emit(code) {
    this.diagnostic?.({ code, runtime: this.runtime });
  }
  checkDeadline() {
    if (Date.now() - this.startedAt >= this.limits.deadlineMs) {
      this.emit("deadline-exceeded");
      throw new SessionDiscoveryError("DISCOVERY_DEADLINE_EXCEEDED");
    }
  }
  consumeEntry() {
    this.checkDeadline();
    this.entries += 1;
    if (this.entries > this.limits.maxEntries) {
      this.emit("budget-exceeded");
      throw new SessionDiscoveryError("DISCOVERY_ENTRY_BUDGET_EXCEEDED");
    }
  }
  consumeBytes(bytes) {
    this.checkDeadline();
    this.aggregateBytes += bytes;
    if (this.aggregateBytes > this.limits.maxAggregateBytes) {
      this.emit("budget-exceeded");
      throw new SessionDiscoveryError("DISCOVERY_BYTE_BUDGET_EXCEEDED");
    }
  }
  remainingMs() {
    this.checkDeadline();
    return Math.max(1, this.limits.deadlineMs - (Date.now() - this.startedAt));
  }
}
function exactAllBudget(runtime, options) {
  if (options?.recency !== "exact-all") return null;
  return new ExactAllDiscoveryBudget(
    options.budget ?? EXACT_ALL_DISCOVERY_BUDGET,
    runtime,
    options.diagnostic
  );
}
class CursorDiscoveryError extends Error {
  code;
  constructor(code) {
    super(code);
    this.name = "CursorDiscoveryError";
    this.code = code;
  }
}
let cursorDiscoveryTestOptions;
function configureCursorDiscoveryForTest(options) {
  cursorDiscoveryTestOptions = options;
}
class CursorDiscoveryBudget {
  maxEntries;
  maxElapsedMs;
  maxBytes;
  maxRetainedCandidates;
  now;
  startedAt;
  entries = 0;
  bytes = 0;
  retainedCandidates = 0;
  constructor(options = {}) {
    this.maxEntries = options.maxEntries ?? CURSOR_DISCOVERY_MAX_ENTRIES;
    this.maxElapsedMs = options.maxElapsedMs ?? CURSOR_DISCOVERY_MAX_ELAPSED_MS;
    this.maxBytes = options.maxBytes ?? CURSOR_DISCOVERY_MAX_BYTES;
    this.maxRetainedCandidates = options.maxRetainedCandidates ?? CURSOR_DISCOVERY_MAX_RETAINED_CANDIDATES;
    this.now = options.now ?? Date.now;
    this.startedAt = this.now();
  }
  checkTime() {
    if (this.now() - this.startedAt > this.maxElapsedMs) {
      throw new CursorDiscoveryError("CURSOR_DISCOVERY_TIME_BUDGET_EXCEEDED");
    }
  }
  consumeEntry() {
    this.checkTime();
    this.entries += 1;
    if (this.entries > this.maxEntries) {
      throw new CursorDiscoveryError("CURSOR_DISCOVERY_ENTRY_BUDGET_EXCEEDED");
    }
  }
  retainCandidate() {
    this.checkTime();
    this.retainedCandidates += 1;
    if (this.retainedCandidates > this.maxRetainedCandidates) {
      throw new CursorDiscoveryError(
        "CURSOR_DISCOVERY_RETAINED_CANDIDATE_BUDGET_EXCEEDED"
      );
    }
  }
  reserveBytes(bytes) {
    this.checkTime();
    this.bytes += bytes;
    if (this.bytes > this.maxBytes) {
      throw new CursorDiscoveryError("CURSOR_DISCOVERY_BYTE_BUDGET_EXCEEDED");
    }
  }
}
const DEFAULT_CLASSIFICATION_CACHE_MAX_ENTRIES = 5e3;
class ClassificationCache {
  maxEntries;
  entries = /* @__PURE__ */ new Map();
  constructor(maxEntries = DEFAULT_CLASSIFICATION_CACHE_MAX_ENTRIES) {
    this.maxEntries = maxEntries;
  }
  get(transcriptPath, mtimeMs, size, derivation = "default") {
    const key = JSON.stringify([derivation, transcriptPath]);
    const entry = this.entries.get(key);
    if (!entry) return void 0;
    if (entry.mtimeMs !== mtimeMs || entry.size !== size) {
      this.entries.delete(key);
      return void 0;
    }
    this.entries.delete(key);
    this.entries.set(key, entry);
    return entry.result;
  }
  set(transcriptPath, mtimeMs, size, result, derivation = "default") {
    const key = JSON.stringify([derivation, transcriptPath]);
    this.entries.delete(key);
    this.entries.set(key, { mtimeMs, size, result });
    if (this.entries.size > this.maxEntries) {
      const oldestKey = this.entries.keys().next().value;
      if (oldestKey !== void 0) this.entries.delete(oldestKey);
    }
  }
  get size() {
    return this.entries.size;
  }
}
const UNKNOWN_CLASSIFICATION = {
  status: "unknown",
  engaged: true,
  recordCount: null,
  genuineUserMessages: 0,
  operatorAskUserAnswers: 0,
  syntheticUserMessages: 0,
  assistantMessages: 0,
  realMessageCount: 0,
  hasAssistantAndUser: false,
  bootstrapRecordIndexes: [],
  bootstrapRecordCount: 0
};
function compactClassificationForCache(classification) {
  if (classification.bootstrapRecordIndexes.length === 0) return classification;
  return { ...classification, bootstrapRecordIndexes: [] };
}
async function candidateDerivedFields(runtime, transcriptPath, signature, cache) {
  const cached = cache.get(transcriptPath, signature.mtimeMs, signature.size);
  if (cached) return cached;
  try {
    const records = await readRecords(transcriptPath);
    const classification = compactClassificationForCache(
      classifyTranscriptRecords(runtime, records)
    );
    const meta = extractMetaFromRecords(runtime, records, transcriptPath);
    const result = { meta, classification };
    cache.set(transcriptPath, signature.mtimeMs, signature.size, result);
    return result;
  } catch {
    return { meta: null, classification: UNKNOWN_CLASSIFICATION };
  }
}
async function candidateDerivedFieldsBounded(runtime, transcriptPath, signature, cache, budget, diagnostic) {
  const derivation = `bounded-prefix:${budget.limits.maxMetadataBytesPerEntry}:${EXACT_ALL_METADATA_MAX_RECORDS}`;
  const cached = cache.get(
    transcriptPath,
    signature.mtimeMs,
    signature.size,
    derivation
  );
  if (cached) return cached;
  let deadlineExceeded = false;
  const read = await readMetadataRecordsBounded(transcriptPath, {
    maxBytes: budget.limits.maxMetadataBytesPerEntry,
    maxRecords: EXACT_ALL_METADATA_MAX_RECORDS,
    deadlineMs: budget.remainingMs(),
    diagnostic: ({ code }) => {
      deadlineExceeded = code === "deadline-exceeded";
      diagnostic?.({ code, runtime });
    }
  });
  budget.checkDeadline();
  if (deadlineExceeded) {
    throw new SessionDiscoveryError("DISCOVERY_DEADLINE_EXCEEDED");
  }
  if (read.incomplete) {
    throw new SessionDiscoveryError("DISCOVERY_TRANSCRIPT_INCOMPLETE");
  }
  const records = read.records;
  const classification = compactClassificationForCache(
    classifyTranscriptRecords(runtime, records)
  );
  let meta = extractMetaFromRecords(runtime, records, transcriptPath);
  if (runtime === "claude-code") {
    const recordedCwd = extractClaudeRecordedCwdFromRecords(records);
    if (!meta || recordedCwd === null) {
      throw new SessionDiscoveryError("DISCOVERY_TRANSCRIPT_INCOMPLETE");
    }
    meta = { ...meta, recordedCwd };
  }
  if (runtime === "codex" && (!meta || meta.recordedCwd === null)) {
    throw new SessionDiscoveryError("DISCOVERY_TRANSCRIPT_INCOMPLETE");
  }
  const result = { meta, classification };
  cache.set(
    transcriptPath,
    signature.mtimeMs,
    signature.size,
    result,
    derivation
  );
  return result;
}
async function candidateEngagementFields(runtime, transcriptPath, signature, cache) {
  const { classification } = await candidateDerivedFields(
    runtime,
    transcriptPath,
    signature,
    cache
  );
  return engagementCandidateFields(classification);
}
function cwdCachePath() {
  const stateDir = process.env.STATE_DIR ?? join(homedir(), ".local", "state", "session-observer");
  return join(stateDir, "codex-cwd-cache.json");
}
async function loadCwdCache() {
  try {
    const raw = await readFile(cwdCachePath(), "utf8");
    return JSON.parse(raw);
  } catch {
    return {};
  }
}
async function saveCwdCache(cache) {
  try {
    const path = cwdCachePath();
    const dir = path.replace(/\/[^/]+$/, "");
    await mkdir(dir, { recursive: true });
    const tmp = join(
      dir,
      `codex-cwd-cache.${process.pid}.${Date.now()}.${randomUUID()}.tmp`
    );
    let fh;
    try {
      fh = await open(tmp, "w");
      await fh.write(JSON.stringify(cache, null, 2));
      await fh.datasync();
      await fh.close();
      fh = null;
      await rename(tmp, path);
    } finally {
      if (fh) {
        try {
          await fh.close();
        } catch {
        }
      }
      try {
        await unlink(tmp);
      } catch {
      }
    }
  } catch {
  }
}
function cwdCacheKey(transcriptPath, mtimeSec) {
  return `${transcriptPath}:${mtimeSec}`;
}
async function discoverClaudeCode(targetCwd, cache, options) {
  const [projectsRoot] = discoverPaths("claude-code");
  const budget = exactAllBudget("claude-code", options);
  const encodedVariants = encodeCwdVariants("claude-code", targetCwd);
  const now = Date.now() / 1e3;
  const candidates = [];
  const seenTranscripts = /* @__PURE__ */ new Set();
  let directHit = false;
  for (const encoded of encodedVariants) {
    budget?.checkDeadline();
    const encodedDir = join(projectsRoot, encoded);
    try {
      const entries = await opendir(encodedDir);
      for await (const entry of entries) {
        budget?.consumeEntry();
        if (!entry.name.endsWith(".jsonl")) continue;
        const transcriptPath = join(encodedDir, entry.name);
        if (seenTranscripts.has(transcriptPath)) continue;
        seenTranscripts.add(transcriptPath);
        let fileStat;
        try {
          fileStat = await stat(transcriptPath);
        } catch {
          if (budget) {
            throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
          }
          continue;
        }
        budget?.consumeBytes(fileStat.size);
        const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
        const ageSec = now - mtime;
        const derived = budget ? await candidateDerivedFieldsBounded(
          "claude-code",
          transcriptPath,
          fileStat,
          cache,
          budget,
          options?.diagnostic
        ) : await candidateDerivedFields(
          "claude-code",
          transcriptPath,
          fileStat,
          cache
        );
        const sessionId = derived.meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
        candidates.push({
          runtime: "claude-code",
          transcriptPath,
          sessionId,
          recordedCwd: budget ? derived.meta?.recordedCwd ?? null : targetCwd,
          cwdSlug: encoded,
          cwdEvidence: budget ? "transcript-record" : "direct-parent-dir",
          mtime,
          size: fileStat.size,
          ageSec,
          ...engagementCandidateFields(derived.classification)
        });
      }
      directHit = true;
    } catch (error) {
      if (error instanceof SessionDiscoveryError) throw error;
      if (budget && !isMissingPathError(error)) {
        throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
      }
    }
  }
  if (!directHit || budget !== null) {
    let projectDirs;
    try {
      projectDirs = await opendir(projectsRoot);
    } catch (error) {
      if (budget && !isMissingPathError(error)) {
        throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
      }
      return candidates;
    }
    for await (const projectEntry of projectDirs) {
      budget?.consumeEntry();
      if (!projectEntry.isDirectory()) continue;
      const dirName = projectEntry.name;
      if (encodedVariants.includes(dirName)) continue;
      const projectDir = join(projectsRoot, dirName);
      let dirEntries;
      try {
        dirEntries = await opendir(projectDir);
      } catch {
        if (budget) {
          throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
        }
        continue;
      }
      for await (const entry of dirEntries) {
        budget?.consumeEntry();
        if (!entry.name.endsWith(".jsonl")) continue;
        const transcriptPath = join(projectDir, entry.name);
        if (seenTranscripts.has(transcriptPath)) continue;
        seenTranscripts.add(transcriptPath);
        let fileStat;
        try {
          fileStat = await stat(transcriptPath);
        } catch {
          if (budget) {
            throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
          }
          continue;
        }
        budget?.consumeBytes(fileStat.size);
        const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
        const ageSec = now - mtime;
        const derived = budget ? await candidateDerivedFieldsBounded(
          "claude-code",
          transcriptPath,
          fileStat,
          cache,
          budget,
          options?.diagnostic
        ) : await candidateDerivedFields(
          "claude-code",
          transcriptPath,
          fileStat,
          cache
        );
        const sessionId = derived.meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
        const recordedCwd = derived.meta?.recordedCwd ?? null;
        candidates.push({
          runtime: "claude-code",
          transcriptPath,
          sessionId,
          recordedCwd,
          cwdSlug: dirName,
          cwdEvidence: budget ? "transcript-record" : "decoded-parent-dir",
          mtime,
          size: fileStat.size,
          ageSec,
          ...engagementCandidateFields(derived.classification)
        });
      }
    }
  }
  return candidates;
}
async function claudeCodeLookupDiagnostics(targetCwd) {
  const [projectsRoot] = discoverPaths("claude-code");
  const diagnostics = [];
  for (const encoded of encodeCwdVariants("claude-code", targetCwd)) {
    const path = join(projectsRoot, encoded);
    let exists = false;
    try {
      const s = await stat(path);
      exists = s.isDirectory();
    } catch {
      exists = false;
    }
    diagnostics.push({ encoded, path, exists });
  }
  return diagnostics;
}
async function collectJsonlFiles(dir, budget = null) {
  const results = [];
  let entries;
  try {
    entries = await opendir(dir);
  } catch (error) {
    if (budget && !isMissingPathError(error)) {
      throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
    }
    return results;
  }
  try {
    for await (const entry of entries) {
      budget?.consumeEntry();
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        const nested = await collectJsonlFiles(fullPath, budget);
        results.push(...nested);
      } else if (entry.isFile() && entry.name.endsWith(".jsonl")) {
        results.push(fullPath);
      }
    }
  } catch (error) {
    if (error instanceof SessionDiscoveryError) throw error;
    if (budget) {
      throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
    }
  }
  return results;
}
async function discoverCodex(_targetCwd, classificationCache, options) {
  const [sessionsRoot] = discoverPaths("codex");
  const budget = exactAllBudget("codex", options);
  const now = Date.now() / 1e3;
  const cutoffSec = now - LOOKBACK_DAYS * 86400;
  const allFiles = await collectJsonlFiles(sessionsRoot, budget);
  if (budget) allFiles.sort((left, right) => left.localeCompare(right));
  const persistentCacheAllowed = options?.persistence !== "forbid";
  const cwdCache = persistentCacheAllowed ? await loadCwdCache() : {};
  let cacheModified = false;
  const candidates = [];
  for (const transcriptPath of allFiles) {
    budget?.checkDeadline();
    let fileStat;
    try {
      fileStat = await stat(transcriptPath);
    } catch {
      if (budget) {
        throw new SessionDiscoveryError("DISCOVERY_ENUMERATION_INCOMPLETE");
      }
      continue;
    }
    budget?.consumeBytes(fileStat.size);
    const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
    if (options?.recency !== "exact-all" && mtime < cutoffSec) continue;
    const ageSec = now - mtime;
    const key = cwdCacheKey(transcriptPath, mtime);
    let recordedCwd;
    let sessionId;
    let boundedDerived = null;
    if (budget) {
      boundedDerived = await candidateDerivedFieldsBounded(
        "codex",
        transcriptPath,
        fileStat,
        classificationCache,
        budget,
        options?.diagnostic
      );
    }
    if (persistentCacheAllowed && cwdCache[key] && cwdCache[key].sessionId !== void 0) {
      recordedCwd = cwdCache[key].recordedCwd;
      sessionId = cwdCache[key].sessionId;
    } else {
      let meta = boundedDerived?.meta;
      if (!budget) {
        try {
          meta = await extractMeta("codex", transcriptPath);
        } catch {
          meta = null;
        }
      }
      recordedCwd = meta?.recordedCwd ?? null;
      sessionId = meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
      if (persistentCacheAllowed) {
        cwdCache[key] = { recordedCwd, sessionId };
        cacheModified = true;
      }
    }
    candidates.push({
      runtime: "codex",
      transcriptPath,
      sessionId,
      recordedCwd,
      mtime,
      size: fileStat.size,
      ageSec,
      ...boundedDerived ? engagementCandidateFields(boundedDerived.classification) : await candidateEngagementFields(
        "codex",
        transcriptPath,
        fileStat,
        classificationCache
      )
    });
  }
  if (persistentCacheAllowed && cacheModified) {
    await saveCwdCache(cwdCache);
  }
  return candidates;
}
async function* collectCursorAgentTranscripts(transcriptsRoot, budget, expectedSessionId, failOnIncomplete = false) {
  let sessionDirs;
  try {
    sessionDirs = await opendir(transcriptsRoot);
  } catch (error) {
    if (failOnIncomplete && !isMissingPathError(error)) {
      throw new CursorDiscoveryError("IDENTITY_INDEX_INCOMPLETE");
    }
    return;
  }
  try {
    for await (const sessionDir of sessionDirs) {
      budget.consumeEntry();
      if (!sessionDir.isDirectory()) continue;
      const sessionPath = join(transcriptsRoot, sessionDir.name);
      let entries;
      try {
        entries = await opendir(sessionPath);
      } catch (error) {
        if (failOnIncomplete && !isMissingPathError(error)) {
          throw new CursorDiscoveryError("IDENTITY_INDEX_INCOMPLETE");
        }
        continue;
      }
      for await (const entry of entries) {
        budget.consumeEntry();
        if (entry.isFile() && entry.name.endsWith(".jsonl")) {
          const transcriptPath = join(sessionPath, entry.name);
          if (expectedSessionId === void 0 || cursorSessionIdFromTranscriptPath(transcriptPath) === expectedSessionId) {
            yield transcriptPath;
          }
        }
      }
    }
  } catch (error) {
    if (error instanceof CursorDiscoveryError) throw error;
    if (failOnIncomplete) {
      throw new CursorDiscoveryError("IDENTITY_INDEX_INCOMPLETE");
    }
  }
}
async function cursorCandidate(transcriptPath, now, evidence, fileStat, cache, budget) {
  let resolvedStat = fileStat;
  if (!resolvedStat) {
    try {
      resolvedStat = await stat(transcriptPath);
    } catch {
      return null;
    }
  }
  const mtime = Math.floor(resolvedStat.mtime.getTime() / 1e3);
  const ageSec = now - mtime;
  budget.reserveBytes(resolvedStat.size);
  const derived = await candidateDerivedFields(
    "cursor",
    transcriptPath,
    resolvedStat,
    cache
  );
  budget.checkTime();
  return {
    runtime: "cursor",
    transcriptPath,
    sessionId: derived.meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, ""),
    recordedCwd: evidence.recordedCwd,
    cwdSlug: evidence.cwdSlug,
    cwdEvidence: evidence.cwdEvidence,
    mtime,
    size: resolvedStat.size,
    ageSec,
    ...engagementCandidateFields(derived.classification)
  };
}
async function discoverCursor(targetCwd, cache) {
  const [projectsRoot] = discoverPaths("cursor");
  const normalizedTargetCwd = resolve(targetCwd);
  const canonicalTargetCwd = await canonicalPath(normalizedTargetCwd) ?? normalizedTargetCwd;
  const canonicalEncodedVariants = new Set(
    encodeCwdVariants("cursor", canonicalTargetCwd)
  );
  const rawEncodedVariants = new Set(
    encodeCwdVariants("cursor", normalizedTargetCwd)
  );
  const suppliedCwdIsAlias = normalizedTargetCwd !== canonicalTargetCwd;
  const directVariants = [
    ...[...canonicalEncodedVariants].map((encoded) => ({
      encoded,
      cwdEvidence: "direct-parent-dir"
    })),
    ...[...rawEncodedVariants].filter((encoded) => !canonicalEncodedVariants.has(encoded)).map((encoded) => ({
      encoded,
      cwdEvidence: suppliedCwdIsAlias ? "raw-cwd-alias" : "direct-parent-dir"
    }))
  ];
  const encodedVariants = directVariants.map(({ encoded }) => encoded);
  const now = Date.now() / 1e3;
  const cutoffSec = now - LOOKBACK_DAYS * 86400;
  const candidates = [];
  const seenTranscripts = /* @__PURE__ */ new Set();
  const budget = new CursorDiscoveryBudget(cursorDiscoveryTestOptions);
  for (const { encoded, cwdEvidence } of directVariants) {
    const transcriptsRoot = join(projectsRoot, encoded, "agent-transcripts");
    for await (const transcriptPath of collectCursorAgentTranscripts(
      transcriptsRoot,
      budget
    )) {
      const canonicalTranscriptPath = await canonicalPath(transcriptPath) ?? transcriptPath;
      if (seenTranscripts.has(canonicalTranscriptPath)) continue;
      budget.retainCandidate();
      seenTranscripts.add(canonicalTranscriptPath);
      const candidate = await cursorCandidate(
        transcriptPath,
        now,
        {
          recordedCwd: targetCwd,
          cwdSlug: encoded,
          cwdEvidence
        },
        null,
        cache,
        budget
      );
      if (candidate) candidates.push(candidate);
    }
  }
  let projectDirs;
  try {
    projectDirs = await opendir(projectsRoot);
  } catch {
    return candidates;
  }
  for await (const projectDir of projectDirs) {
    budget.consumeEntry();
    if (!projectDir.isDirectory()) continue;
    if (encodedVariants.includes(projectDir.name)) continue;
    const transcriptsRoot = join(
      projectsRoot,
      projectDir.name,
      "agent-transcripts"
    );
    for await (const transcriptPath of collectCursorAgentTranscripts(
      transcriptsRoot,
      budget
    )) {
      const canonicalTranscriptPath = await canonicalPath(transcriptPath) ?? transcriptPath;
      if (seenTranscripts.has(canonicalTranscriptPath)) continue;
      budget.retainCandidate();
      seenTranscripts.add(canonicalTranscriptPath);
      let fileStat;
      try {
        fileStat = await stat(transcriptPath);
      } catch {
        continue;
      }
      const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
      if (mtime < cutoffSec) continue;
      const candidate = await cursorCandidate(
        transcriptPath,
        now,
        {
          recordedCwd: null,
          cwdSlug: projectDir.name,
          cwdEvidence: "project-dir-slug"
        },
        fileStat,
        cache,
        budget
      );
      if (candidate) candidates.push(candidate);
    }
  }
  return candidates;
}
async function findCursorSessionCandidates(targetCwd, sessionId, cache) {
  const [projectsRoot] = discoverPaths("cursor");
  const normalizedTargetCwd = resolve(targetCwd);
  const canonicalTargetCwd = await canonicalPath(normalizedTargetCwd) ?? normalizedTargetCwd;
  const canonicalEncodedVariants = new Set(
    encodeCwdVariants("cursor", canonicalTargetCwd)
  );
  const rawEncodedVariants = new Set(
    encodeCwdVariants("cursor", normalizedTargetCwd)
  );
  const suppliedCwdIsAlias = normalizedTargetCwd !== canonicalTargetCwd;
  const directVariants = [
    ...[...canonicalEncodedVariants].map((encoded) => ({
      encoded,
      cwdEvidence: "direct-parent-dir"
    })),
    ...[...rawEncodedVariants].filter((encoded) => !canonicalEncodedVariants.has(encoded)).map((encoded) => ({
      encoded,
      cwdEvidence: suppliedCwdIsAlias ? "raw-cwd-alias" : "direct-parent-dir"
    }))
  ];
  const directEvidence = new Map(
    directVariants.map(({ encoded, cwdEvidence }) => [encoded, cwdEvidence])
  );
  const now = Date.now() / 1e3;
  const cutoffSec = now - LOOKBACK_DAYS * 86400;
  const candidates = [];
  const seenTranscripts = /* @__PURE__ */ new Set();
  const pinnedBudget = new CursorDiscoveryBudget({
    maxEntries: cursorDiscoveryTestOptions?.maxEntries ?? CURSOR_IDENTITY_INDEX_MAX_ENTRIES,
    maxElapsedMs: cursorDiscoveryTestOptions?.maxElapsedMs ?? CURSOR_IDENTITY_INDEX_MAX_ELAPSED_MS,
    maxBytes: Number.MAX_SAFE_INTEGER,
    maxRetainedCandidates: Number.MAX_SAFE_INTEGER,
    now: cursorDiscoveryTestOptions?.now
  });
  let projectDirs;
  try {
    projectDirs = await opendir(projectsRoot);
  } catch (error) {
    if (!isMissingPathError(error)) {
      throw new CursorDiscoveryError("IDENTITY_INDEX_INCOMPLETE");
    }
    return candidates;
  }
  try {
    for await (const projectDir of projectDirs) {
      pinnedBudget.consumeEntry();
      if (!projectDir.isDirectory()) continue;
      const cwdEvidence = directEvidence.get(projectDir.name);
      const transcriptsRoot = join(
        projectsRoot,
        projectDir.name,
        "agent-transcripts"
      );
      for await (const transcriptPath of collectCursorAgentTranscripts(
        transcriptsRoot,
        // Pinned lookup filters by path before classification. Its aggregate
        // metadata walk is finite and fails visibly if uniqueness cannot be
        // established within the same entry/time envelope as identity indexing.
        pinnedBudget,
        sessionId,
        true
      )) {
        const canonicalTranscriptPath = await canonicalPath(transcriptPath) ?? transcriptPath;
        if (seenTranscripts.has(canonicalTranscriptPath)) continue;
        seenTranscripts.add(canonicalTranscriptPath);
        let fileStat;
        try {
          fileStat = await stat(transcriptPath);
        } catch (error) {
          if (isMissingPathError(error)) continue;
          throw new CursorDiscoveryError("IDENTITY_INDEX_INCOMPLETE");
        }
        const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
        if (cwdEvidence === void 0 && mtime < cutoffSec) continue;
        const candidate = await cursorCandidate(
          transcriptPath,
          now,
          {
            recordedCwd: cwdEvidence === void 0 ? null : targetCwd,
            cwdSlug: projectDir.name,
            cwdEvidence: cwdEvidence ?? "project-dir-slug"
          },
          fileStat,
          cache,
          pinnedBudget
        );
        if (candidate?.sessionId === sessionId) candidates.push(candidate);
      }
    }
  } catch (error) {
    if (error instanceof CursorDiscoveryError) throw error;
    throw new CursorDiscoveryError("IDENTITY_INDEX_INCOMPLETE");
  }
  return candidates;
}
function cursorCwdEvidence(candidate) {
  if (candidate.cwdEvidence === "store-metadata") return "store-metadata";
  if (candidate.cwdEvidence === "harness-environment") {
    return "harness-environment";
  }
  if (candidate.cwdEvidence === "direct-parent-dir") {
    return "direct-project-root";
  }
  return "fallback-slug";
}
function pathIsWithin(root, candidate) {
  const relativePath = relative(root, candidate);
  return relativePath === "" || !relativePath.startsWith(
    `..${process.platform === "win32" ? "\\" : "/"}`
  ) && relativePath !== ".." && !isAbsolute(relativePath);
}
async function canonicalPath(path) {
  try {
    return await realpath(path);
  } catch {
    return null;
  }
}
function isMissingPathError(error) {
  return typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT";
}
function cursorSessionIdFromTranscriptPath(transcriptPath) {
  const transcriptBase = basename(transcriptPath).replace(/\.jsonl$/u, "");
  return transcriptBase && !["transcript", "conversation", "messages"].includes(transcriptBase) ? transcriptBase : basename(join(transcriptPath, ".."));
}
async function cursorSessionCanonicalPaths(sessionId, options = {}) {
  const [projectsRoot] = discoverPaths("cursor");
  const canonicalPaths = /* @__PURE__ */ new Set();
  const maxEntries = options.maxEntries ?? CURSOR_IDENTITY_INDEX_MAX_ENTRIES;
  const maxElapsedMs = options.maxElapsedMs ?? CURSOR_IDENTITY_INDEX_MAX_ELAPSED_MS;
  const now = options.now ?? Date.now;
  const startedAt = now();
  let entryCount = 0;
  const budgetFailure = (consumeEntry = false) => {
    if (now() - startedAt > maxElapsedMs) {
      return "IDENTITY_INDEX_TIME_BUDGET_EXCEEDED";
    }
    if (consumeEntry) {
      entryCount += 1;
      if (entryCount > maxEntries) {
        return "IDENTITY_INDEX_ENTRY_BUDGET_EXCEEDED";
      }
    }
    return null;
  };
  let projects;
  try {
    projects = await opendir(projectsRoot);
  } catch (error) {
    return {
      canonicalPaths,
      failure: isMissingPathError(error) ? null : "IDENTITY_INDEX_INCOMPLETE"
    };
  }
  try {
    for await (const projectDir of projects) {
      let failure = budgetFailure(true);
      if (failure) return { canonicalPaths, failure };
      if (!projectDir.isDirectory()) continue;
      let sessions;
      try {
        sessions = await opendir(
          join(projectsRoot, projectDir.name, "agent-transcripts")
        );
      } catch (error) {
        if (isMissingPathError(error)) continue;
        return {
          canonicalPaths,
          failure: "IDENTITY_INDEX_INCOMPLETE"
        };
      }
      failure = budgetFailure();
      if (failure) return { canonicalPaths, failure };
      for await (const sessionDir of sessions) {
        failure = budgetFailure(true);
        if (failure) return { canonicalPaths, failure };
        if (!sessionDir.isDirectory()) continue;
        let transcripts;
        try {
          transcripts = await opendir(
            join(
              projectsRoot,
              projectDir.name,
              "agent-transcripts",
              sessionDir.name
            )
          );
        } catch (error) {
          if (isMissingPathError(error)) continue;
          return {
            canonicalPaths,
            failure: "IDENTITY_INDEX_INCOMPLETE"
          };
        }
        failure = budgetFailure();
        if (failure) return { canonicalPaths, failure };
        for await (const entry of transcripts) {
          failure = budgetFailure(true);
          if (failure) return { canonicalPaths, failure };
          if (!entry.isFile() || !entry.name.endsWith(".jsonl")) continue;
          const transcriptPath = join(
            projectsRoot,
            projectDir.name,
            "agent-transcripts",
            sessionDir.name,
            entry.name
          );
          if (cursorSessionIdFromTranscriptPath(transcriptPath) !== sessionId) {
            continue;
          }
          let canonicalTranscriptPath;
          try {
            canonicalTranscriptPath = await realpath(transcriptPath);
          } catch (error) {
            if (isMissingPathError(error)) continue;
            return {
              canonicalPaths,
              failure: "IDENTITY_INDEX_INCOMPLETE"
            };
          }
          canonicalPaths.add(canonicalTranscriptPath);
          failure = budgetFailure();
          if (failure) return { canonicalPaths, failure };
        }
      }
    }
  } catch {
    return { canonicalPaths, failure: "IDENTITY_INDEX_INCOMPLETE" };
  }
  return { canonicalPaths, failure: null };
}
async function resolveCursorIdentity(candidate, requestedCwd, expectedSessionId, indexOptions) {
  if (candidate.runtime !== "cursor") {
    throw new TypeError("resolveCursorIdentity requires a Cursor candidate");
  }
  const cwdEvidence = [cursorCwdEvidence(candidate)];
  const sessionEvidence = ["transcript-path"];
  const reasons = [];
  const requestedCanonicalCwd = await canonicalPath(requestedCwd);
  const resolvedTranscriptPath = await canonicalPath(candidate.transcriptPath);
  const storeRoot = join(homedir(), ".cursor", "projects");
  const resolvedStoreRoot = await canonicalPath(storeRoot);
  const canonicalCwd = requestedCanonicalCwd ?? requestedCwd.replace(/\/+$/u, "");
  const canonicalTranscriptPath = resolvedTranscriptPath ?? candidate.transcriptPath;
  const canonicalStoreRoot = resolvedStoreRoot ?? storeRoot;
  if (requestedCanonicalCwd === null) {
    reasons.push("CWD_CANONICALIZATION_FAILED");
  }
  if (resolvedTranscriptPath === null) {
    reasons.push("TRANSCRIPT_CANONICALIZATION_FAILED");
  }
  if (resolvedStoreRoot === null) {
    reasons.push("STORE_ROOT_CANONICALIZATION_FAILED");
  }
  if (resolvedStoreRoot !== null && resolvedTranscriptPath !== null && !pathIsWithin(canonicalStoreRoot, canonicalTranscriptPath)) {
    reasons.push("PATH_OUTSIDE_SUPPORTED_ROOT");
  }
  const canonicalRecordedCwd = candidate.recordedCwd ? await canonicalPath(candidate.recordedCwd) : null;
  if (candidate.recordedCwd && canonicalRecordedCwd === null) {
    reasons.push("RECORDED_CWD_CANONICALIZATION_FAILED");
  }
  if (candidate.cwdEvidence === "raw-cwd-alias") {
    reasons.push("RAW_CWD_ALIAS_DIAGNOSTIC_ONLY");
  }
  if (canonicalRecordedCwd !== null && canonicalRecordedCwd !== canonicalCwd) {
    reasons.push("CANDIDATE_CWD_MISMATCH");
  }
  if (expectedSessionId !== void 0) {
    sessionEvidence.unshift("explicit-pin");
    if (expectedSessionId !== candidate.sessionId) {
      reasons.push("IDENTITY_MISMATCH");
    }
  }
  const harnessSessionId = process.env.CURSOR_SESSION_ID?.trim();
  if (harnessSessionId) {
    sessionEvidence.splice(
      expectedSessionId === void 0 ? 0 : 1,
      0,
      "harness-environment"
    );
    cwdEvidence.push("harness-environment");
    if (harnessSessionId !== candidate.sessionId) {
      reasons.push("HARNESS_SESSION_MISMATCH");
    }
  }
  const identityIndex = await cursorSessionCanonicalPaths(
    candidate.sessionId,
    indexOptions
  );
  const distinctPaths = identityIndex.canonicalPaths;
  distinctPaths.add(canonicalTranscriptPath);
  if (identityIndex.failure) reasons.push(identityIndex.failure);
  if (distinctPaths.size > 1) {
    reasons.push("DUPLICATE_SESSION_CANDIDATES");
  }
  const cwdSource = cwdEvidence[0];
  const cwdMatches = canonicalRecordedCwd === canonicalCwd && cwdSource !== "fallback-slug";
  const independentStoreCwd = cwdSource === "store-metadata";
  const exactSessionSignal = expectedSessionId !== void 0 && expectedSessionId === candidate.sessionId || harnessSessionId === candidate.sessionId || independentStoreCwd;
  const hardFailure = reasons.some(
    (reason) => [
      "PATH_OUTSIDE_SUPPORTED_ROOT",
      "CANDIDATE_CWD_MISMATCH",
      "IDENTITY_MISMATCH",
      "HARNESS_SESSION_MISMATCH",
      "DUPLICATE_SESSION_CANDIDATES",
      "IDENTITY_INDEX_ENTRY_BUDGET_EXCEEDED",
      "IDENTITY_INDEX_TIME_BUDGET_EXCEEDED",
      "IDENTITY_INDEX_INCOMPLETE"
    ].includes(reason)
  );
  const canonicalIdentityReady = requestedCanonicalCwd !== null && resolvedTranscriptPath !== null && resolvedStoreRoot !== null && (candidate.recordedCwd === null || canonicalRecordedCwd !== null);
  let strength;
  if (hardFailure) {
    strength = "ambiguous";
  } else if (canonicalIdentityReady && cwdMatches && exactSessionSignal) {
    strength = "exact";
  } else {
    strength = "diagnostic";
    if (!cwdMatches) reasons.push("WEAK_CWD_EVIDENCE");
    if (!exactSessionSignal) reasons.push("SESSION_SIGNAL_REQUIRED");
  }
  return {
    runtime: "cursor",
    sessionId: candidate.sessionId,
    projectCwd: canonicalCwd,
    canonicalCwd,
    canonicalTranscriptPath,
    cwdEvidence,
    sessionEvidence,
    strength,
    reasons
  };
}
async function discover(runtime, targetCwd, cache = new ClassificationCache(), options) {
  if (runtime === "claude-code") {
    return discoverClaudeCode(targetCwd, cache, options);
  }
  if (runtime === "codex") return discoverCodex(targetCwd, cache, options);
  if (runtime === "cursor") return discoverCursor(targetCwd, cache);
  throw new Error(`Unknown runtime: ${runtime}`);
}
async function findSessionCandidate(runtime, targetCwd, sessionId, options) {
  const cache = new ClassificationCache();
  const candidates = runtime === "cursor" ? await findCursorSessionCandidates(targetCwd, sessionId, cache) : await discover(runtime, targetCwd, cache, options);
  const matches = candidates.filter(
    (candidate) => candidate.recordedCwd === targetCwd && candidate.sessionId === sessionId
  );
  return matches.length === 1 ? matches[0] : null;
}
async function findNewerSameCwdCandidates(runtime, targetCwd, watched, cache = new ClassificationCache()) {
  const candidates = await discover(runtime, targetCwd, cache);
  return candidates.filter(
    (candidate) => candidate.recordedCwd === targetCwd && candidate.sessionId !== watched.sessionId && candidate.transcriptPath !== watched.transcriptPath && candidate.mtime > watched.mtime
  ).toSorted(
    (left, right) => right.mtime - left.mtime || left.transcriptPath.localeCompare(right.transcriptPath)
  );
}
async function gitWorktrees(cwd) {
  try {
    const { stdout } = await execFileAsync(
      "git",
      ["-C", cwd, "worktree", "list", "--porcelain"],
      {
        timeout: 5e3
      }
    );
    const paths = [];
    for (const line of stdout.split("\n")) {
      if (line.startsWith("worktree ")) {
        paths.push(line.slice("worktree ".length).trim());
      }
    }
    return paths;
  } catch {
    return [];
  }
}
export {
  ClassificationCache,
  CursorDiscoveryError,
  SessionDiscoveryError,
  claudeCodeLookupDiagnostics,
  configureCursorDiscoveryForTest,
  discover,
  findNewerSameCwdCandidates,
  findSessionCandidate,
  gitWorktrees,
  resolveCursorIdentity
};
