// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/transcript/session-observer/lib/locate.ts
import { execFile } from "node:child_process";
import {
  readdir,
  stat,
  mkdir,
  readFile,
  realpath,
  writeFile
} from "node:fs/promises";
import { homedir } from "node:os";
import { join, basename, isAbsolute, relative } from "node:path";
import { promisify } from "node:util";
import {
  discoverPaths,
  encodeCwdVariants,
  extractMeta
} from './runtimes.mjs';
import {
  classifyTranscript,
  engagementCandidateFields
} from './session-classifier.mjs';
const execFileAsync = promisify(execFile);
const LOOKBACK_DAYS = 7;
async function candidateEngagementFields(runtime, transcriptPath) {
  try {
    return engagementCandidateFields(
      await classifyTranscript(runtime, transcriptPath)
    );
  } catch {
    return engagementCandidateFields({
      status: "unknown",
      engaged: true,
      recordCount: null,
      genuineUserMessages: 0,
      syntheticUserMessages: 0,
      assistantMessages: 0,
      realMessageCount: 0,
      hasAssistantAndUser: false,
      bootstrapRecordIndexes: [],
      bootstrapRecordCount: 0
    });
  }
}
function cwdCachePath() {
  const stateDir = process.env.STATE_DIR ?? join(homedir(), ".local", "state", "session-observer");
  return join(stateDir, "codex-cwd-cache.json");
}
async function loadCwdCache() {
  try {
    const raw = await readFile(cwdCachePath(), "utf8");
    return JSON.parse(raw);
  } catch {
    return {};
  }
}
async function saveCwdCache(cache) {
  try {
    const path = cwdCachePath();
    const stateDir = path.replace(/\/[^/]+$/, "");
    await mkdir(stateDir, { recursive: true });
    await writeFile(path, JSON.stringify(cache, null, 2), "utf8");
  } catch {
  }
}
function cwdCacheKey(transcriptPath, mtimeSec) {
  return `${transcriptPath}:${mtimeSec}`;
}
async function discoverClaudeCode(targetCwd) {
  const [projectsRoot] = discoverPaths("claude-code");
  const encodedVariants = encodeCwdVariants("claude-code", targetCwd);
  const now = Date.now() / 1e3;
  const candidates = [];
  const seenTranscripts = /* @__PURE__ */ new Set();
  let directHit = false;
  for (const encoded of encodedVariants) {
    const encodedDir = join(projectsRoot, encoded);
    try {
      const entries = await readdir(encodedDir);
      const jsonlFiles = entries.filter((e) => e.endsWith(".jsonl"));
      for (const file of jsonlFiles) {
        const transcriptPath = join(encodedDir, file);
        if (seenTranscripts.has(transcriptPath)) continue;
        seenTranscripts.add(transcriptPath);
        let fileStat;
        try {
          fileStat = await stat(transcriptPath);
        } catch {
          continue;
        }
        const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
        const ageSec = now - mtime;
        let meta;
        try {
          meta = await extractMeta("claude-code", transcriptPath);
        } catch {
          meta = null;
        }
        const sessionId = meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
        candidates.push({
          runtime: "claude-code",
          transcriptPath,
          sessionId,
          // Guaranteed exact match: do NOT use decodeCwdDirName (lossy).
          recordedCwd: targetCwd,
          cwdSlug: encoded,
          cwdEvidence: "direct-parent-dir",
          mtime,
          size: fileStat.size,
          ageSec,
          ...await candidateEngagementFields("claude-code", transcriptPath)
        });
      }
      directHit = true;
    } catch {
    }
  }
  if (!directHit) {
    let projectDirs = [];
    try {
      projectDirs = await readdir(projectsRoot);
    } catch {
      return candidates;
    }
    for (const dirName of projectDirs) {
      if (encodedVariants.includes(dirName)) continue;
      const projectDir = join(projectsRoot, dirName);
      let dirEntries;
      try {
        dirEntries = await readdir(projectDir);
      } catch {
        continue;
      }
      const jsonlFiles = dirEntries.filter((e) => e.endsWith(".jsonl"));
      for (const file of jsonlFiles) {
        const transcriptPath = join(projectDir, file);
        if (seenTranscripts.has(transcriptPath)) continue;
        seenTranscripts.add(transcriptPath);
        let fileStat;
        try {
          fileStat = await stat(transcriptPath);
        } catch {
          continue;
        }
        const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
        const ageSec = now - mtime;
        let meta;
        try {
          meta = await extractMeta("claude-code", transcriptPath);
        } catch {
          meta = null;
        }
        const sessionId = meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
        const recordedCwd = meta?.recordedCwd ?? null;
        candidates.push({
          runtime: "claude-code",
          transcriptPath,
          sessionId,
          recordedCwd,
          cwdSlug: dirName,
          cwdEvidence: "decoded-parent-dir",
          mtime,
          size: fileStat.size,
          ageSec,
          ...await candidateEngagementFields("claude-code", transcriptPath)
        });
      }
    }
  }
  return candidates;
}
async function claudeCodeLookupDiagnostics(targetCwd) {
  const [projectsRoot] = discoverPaths("claude-code");
  const diagnostics = [];
  for (const encoded of encodeCwdVariants("claude-code", targetCwd)) {
    const path = join(projectsRoot, encoded);
    let exists = false;
    try {
      const s = await stat(path);
      exists = s.isDirectory();
    } catch {
      exists = false;
    }
    diagnostics.push({ encoded, path, exists });
  }
  return diagnostics;
}
async function collectJsonlFiles(dir) {
  const results = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      const nested = await collectJsonlFiles(fullPath);
      results.push(...nested);
    } else if (entry.isFile() && entry.name.endsWith(".jsonl")) {
      results.push(fullPath);
    }
  }
  return results;
}
async function discoverCodex(_targetCwd) {
  const [sessionsRoot] = discoverPaths("codex");
  const now = Date.now() / 1e3;
  const cutoffSec = now - LOOKBACK_DAYS * 86400;
  const allFiles = await collectJsonlFiles(sessionsRoot);
  const cache = await loadCwdCache();
  let cacheModified = false;
  const candidates = [];
  for (const transcriptPath of allFiles) {
    let fileStat;
    try {
      fileStat = await stat(transcriptPath);
    } catch {
      continue;
    }
    const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
    if (mtime < cutoffSec) continue;
    const ageSec = now - mtime;
    const key = cwdCacheKey(transcriptPath, mtime);
    let recordedCwd;
    let sessionId;
    if (cache[key] && cache[key].sessionId !== void 0) {
      recordedCwd = cache[key].recordedCwd;
      sessionId = cache[key].sessionId;
    } else {
      let meta;
      try {
        meta = await extractMeta("codex", transcriptPath);
      } catch {
        meta = null;
      }
      recordedCwd = meta?.recordedCwd ?? null;
      sessionId = meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
      cache[key] = { recordedCwd, sessionId };
      cacheModified = true;
    }
    candidates.push({
      runtime: "codex",
      transcriptPath,
      sessionId,
      recordedCwd,
      mtime,
      size: fileStat.size,
      ageSec,
      ...await candidateEngagementFields("codex", transcriptPath)
    });
  }
  if (cacheModified) {
    await saveCwdCache(cache);
  }
  return candidates;
}
async function collectCursorAgentTranscripts(transcriptsRoot) {
  const results = [];
  let sessionDirs;
  try {
    sessionDirs = await readdir(transcriptsRoot, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const sessionDir of sessionDirs) {
    if (!sessionDir.isDirectory()) continue;
    const sessionPath = join(transcriptsRoot, sessionDir.name);
    let entries;
    try {
      entries = await readdir(sessionPath, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith(".jsonl")) {
        results.push(join(sessionPath, entry.name));
      }
    }
  }
  return results;
}
async function cursorCandidate(transcriptPath, now, evidence, fileStat = null) {
  let resolvedStat = fileStat;
  if (!resolvedStat) {
    try {
      resolvedStat = await stat(transcriptPath);
    } catch {
      return null;
    }
  }
  const mtime = Math.floor(resolvedStat.mtime.getTime() / 1e3);
  const ageSec = now - mtime;
  let meta;
  try {
    meta = await extractMeta("cursor", transcriptPath);
  } catch {
    meta = null;
  }
  return {
    runtime: "cursor",
    transcriptPath,
    sessionId: meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, ""),
    recordedCwd: evidence.recordedCwd,
    cwdSlug: evidence.cwdSlug,
    cwdEvidence: evidence.cwdEvidence,
    mtime,
    size: resolvedStat.size,
    ageSec,
    ...await candidateEngagementFields("cursor", transcriptPath)
  };
}
async function discoverCursor(targetCwd) {
  const [projectsRoot] = discoverPaths("cursor");
  const encodedVariants = encodeCwdVariants("cursor", targetCwd);
  const now = Date.now() / 1e3;
  const cutoffSec = now - LOOKBACK_DAYS * 86400;
  const candidates = [];
  const seenTranscripts = /* @__PURE__ */ new Set();
  let directHit = false;
  for (const encoded of encodedVariants) {
    const transcriptsRoot = join(projectsRoot, encoded, "agent-transcripts");
    const transcriptPaths = await collectCursorAgentTranscripts(transcriptsRoot);
    if (transcriptPaths.length === 0) continue;
    directHit = true;
    for (const transcriptPath of transcriptPaths) {
      if (seenTranscripts.has(transcriptPath)) continue;
      seenTranscripts.add(transcriptPath);
      const candidate = await cursorCandidate(transcriptPath, now, {
        recordedCwd: targetCwd,
        cwdSlug: encoded,
        cwdEvidence: "direct-parent-dir"
      });
      if (candidate) candidates.push(candidate);
    }
  }
  if (directHit) return candidates;
  let projectDirs = [];
  try {
    projectDirs = await readdir(projectsRoot, { withFileTypes: true });
  } catch {
    return candidates;
  }
  for (const projectDir of projectDirs) {
    if (!projectDir.isDirectory()) continue;
    if (encodedVariants.includes(projectDir.name)) continue;
    const transcriptsRoot = join(
      projectsRoot,
      projectDir.name,
      "agent-transcripts"
    );
    const transcriptPaths = await collectCursorAgentTranscripts(transcriptsRoot);
    for (const transcriptPath of transcriptPaths) {
      if (seenTranscripts.has(transcriptPath)) continue;
      seenTranscripts.add(transcriptPath);
      let fileStat;
      try {
        fileStat = await stat(transcriptPath);
      } catch {
        continue;
      }
      const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
      if (mtime < cutoffSec) continue;
      const candidate = await cursorCandidate(
        transcriptPath,
        now,
        {
          recordedCwd: null,
          cwdSlug: projectDir.name,
          cwdEvidence: "project-dir-slug"
        },
        fileStat
      );
      if (candidate) candidates.push(candidate);
    }
  }
  return candidates;
}
function cursorCwdEvidence(candidate) {
  if (candidate.cwdEvidence === "store-metadata") return "store-metadata";
  if (candidate.cwdEvidence === "harness-environment") {
    return "harness-environment";
  }
  if (candidate.cwdEvidence === "direct-parent-dir") {
    return "direct-project-root";
  }
  return "fallback-slug";
}
function pathIsWithin(root, candidate) {
  const relativePath = relative(root, candidate);
  return relativePath === "" || !relativePath.startsWith(
    `..${process.platform === "win32" ? "\\" : "/"}`
  ) && relativePath !== ".." && !isAbsolute(relativePath);
}
async function canonicalPath(path) {
  try {
    return await realpath(path);
  } catch {
    return null;
  }
}
async function resolveCursorIdentity(candidate, requestedCwd, expectedSessionId) {
  if (candidate.runtime !== "cursor") {
    throw new TypeError("resolveCursorIdentity requires a Cursor candidate");
  }
  const cwdEvidence = [cursorCwdEvidence(candidate)];
  const sessionEvidence = ["transcript-path"];
  const reasons = [];
  const canonicalCwd = await canonicalPath(requestedCwd) ?? requestedCwd.replace(/\/+$/u, "");
  const canonicalTranscriptPath = await canonicalPath(candidate.transcriptPath) ?? candidate.transcriptPath;
  const canonicalStoreRoot = await canonicalPath(join(homedir(), ".cursor", "projects")) ?? join(homedir(), ".cursor", "projects");
  if (!pathIsWithin(canonicalStoreRoot, canonicalTranscriptPath)) {
    reasons.push("PATH_OUTSIDE_SUPPORTED_ROOT");
  }
  const canonicalRecordedCwd = candidate.recordedCwd ? await canonicalPath(candidate.recordedCwd) : null;
  if (canonicalRecordedCwd !== null && canonicalRecordedCwd !== canonicalCwd) {
    reasons.push("CANDIDATE_CWD_MISMATCH");
  }
  if (expectedSessionId !== void 0) {
    sessionEvidence.unshift("explicit-pin");
    if (expectedSessionId !== candidate.sessionId) {
      reasons.push("IDENTITY_MISMATCH");
    }
  }
  const harnessSessionId = process.env.CURSOR_SESSION_ID?.trim();
  if (harnessSessionId) {
    sessionEvidence.splice(
      expectedSessionId === void 0 ? 0 : 1,
      0,
      "harness-environment"
    );
    cwdEvidence.push("harness-environment");
    if (harnessSessionId !== candidate.sessionId) {
      reasons.push("HARNESS_SESSION_MISMATCH");
    }
  }
  const sameSessionCandidates = (await discoverCursor(requestedCwd)).filter(
    (discovered) => discovered.sessionId === candidate.sessionId
  );
  const distinctPaths = /* @__PURE__ */ new Set();
  for (const discovered of sameSessionCandidates) {
    distinctPaths.add(
      await canonicalPath(discovered.transcriptPath) ?? discovered.transcriptPath
    );
  }
  if (distinctPaths.size > 1) {
    reasons.push("DUPLICATE_SESSION_CANDIDATES");
  }
  const cwdSource = cwdEvidence[0];
  const cwdMatches = canonicalRecordedCwd === canonicalCwd && cwdSource !== "fallback-slug";
  const independentStoreCwd = cwdSource === "store-metadata";
  const exactSessionSignal = expectedSessionId !== void 0 && expectedSessionId === candidate.sessionId || harnessSessionId === candidate.sessionId || independentStoreCwd;
  const hardFailure = reasons.some(
    (reason) => [
      "PATH_OUTSIDE_SUPPORTED_ROOT",
      "CANDIDATE_CWD_MISMATCH",
      "IDENTITY_MISMATCH",
      "HARNESS_SESSION_MISMATCH",
      "DUPLICATE_SESSION_CANDIDATES"
    ].includes(reason)
  );
  let strength;
  if (hardFailure) {
    strength = "ambiguous";
  } else if (cwdMatches && exactSessionSignal) {
    strength = "exact";
  } else {
    strength = "diagnostic";
    if (!cwdMatches) reasons.push("WEAK_CWD_EVIDENCE");
    if (!exactSessionSignal) reasons.push("SESSION_SIGNAL_REQUIRED");
  }
  return {
    runtime: "cursor",
    sessionId: candidate.sessionId,
    projectCwd: canonicalCwd,
    canonicalCwd,
    canonicalTranscriptPath,
    cwdEvidence,
    sessionEvidence,
    strength,
    reasons
  };
}
async function discover(runtime, targetCwd) {
  if (runtime === "claude-code") return discoverClaudeCode(targetCwd);
  if (runtime === "codex") return discoverCodex(targetCwd);
  if (runtime === "cursor") return discoverCursor(targetCwd);
  throw new Error(`Unknown runtime: ${runtime}`);
}
async function findSessionCandidate(runtime, targetCwd, sessionId) {
  const matches = (await discover(runtime, targetCwd)).filter(
    (candidate) => candidate.recordedCwd === targetCwd && candidate.sessionId === sessionId
  );
  return matches.length === 1 ? matches[0] : null;
}
async function findNewerSameCwdCandidates(runtime, targetCwd, watched) {
  const candidates = await discover(runtime, targetCwd);
  return candidates.filter(
    (candidate) => candidate.recordedCwd === targetCwd && candidate.sessionId !== watched.sessionId && candidate.transcriptPath !== watched.transcriptPath && candidate.mtime > watched.mtime
  ).toSorted(
    (left, right) => right.mtime - left.mtime || left.transcriptPath.localeCompare(right.transcriptPath)
  );
}
async function gitWorktrees(cwd) {
  try {
    const { stdout } = await execFileAsync(
      "git",
      ["-C", cwd, "worktree", "list", "--porcelain"],
      {
        timeout: 5e3
      }
    );
    const paths = [];
    for (const line of stdout.split("\n")) {
      if (line.startsWith("worktree ")) {
        paths.push(line.slice("worktree ".length).trim());
      }
    }
    return paths;
  } catch {
    return [];
  }
}
export {
  claudeCodeLookupDiagnostics,
  discover,
  findNewerSameCwdCandidates,
  findSessionCandidate,
  gitWorktrees,
  resolveCursorIdentity
};
