// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/transcript/session-observer/lib/locate.ts
import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import {
  readdir,
  stat,
  mkdir,
  readFile,
  rename,
  open,
  unlink
} from "node:fs/promises";
import { homedir } from "node:os";
import { join, basename } from "node:path";
import { promisify } from "node:util";
import {
  discoverPaths,
  encodeCwdVariants,
  extractMeta,
  extractMetaFromRecords,
  readRecords
} from './runtimes.mjs';
import {
  classifyTranscriptRecords,
  engagementCandidateFields
} from './session-classifier.mjs';
const execFileAsync = promisify(execFile);
const LOOKBACK_DAYS = 7;
const DEFAULT_CLASSIFICATION_CACHE_MAX_ENTRIES = 5e3;
class ClassificationCache {
  maxEntries;
  entries = /* @__PURE__ */ new Map();
  constructor(maxEntries = DEFAULT_CLASSIFICATION_CACHE_MAX_ENTRIES) {
    this.maxEntries = maxEntries;
  }
  get(transcriptPath, mtimeMs, size) {
    const entry = this.entries.get(transcriptPath);
    if (!entry) return void 0;
    if (entry.mtimeMs !== mtimeMs || entry.size !== size) {
      this.entries.delete(transcriptPath);
      return void 0;
    }
    this.entries.delete(transcriptPath);
    this.entries.set(transcriptPath, entry);
    return entry.result;
  }
  set(transcriptPath, mtimeMs, size, result) {
    this.entries.delete(transcriptPath);
    this.entries.set(transcriptPath, { mtimeMs, size, result });
    if (this.entries.size > this.maxEntries) {
      const oldestKey = this.entries.keys().next().value;
      if (oldestKey !== void 0) this.entries.delete(oldestKey);
    }
  }
  get size() {
    return this.entries.size;
  }
}
const UNKNOWN_CLASSIFICATION = {
  status: "unknown",
  engaged: true,
  recordCount: null,
  genuineUserMessages: 0,
  syntheticUserMessages: 0,
  assistantMessages: 0,
  realMessageCount: 0,
  hasAssistantAndUser: false,
  bootstrapRecordIndexes: [],
  bootstrapRecordCount: 0
};
async function candidateDerivedFields(runtime, transcriptPath, signature, cache) {
  const cached = cache.get(transcriptPath, signature.mtimeMs, signature.size);
  if (cached) return cached;
  try {
    const records = await readRecords(transcriptPath);
    const classification = classifyTranscriptRecords(runtime, records);
    const meta = extractMetaFromRecords(runtime, records, transcriptPath);
    const result = { meta, classification };
    cache.set(transcriptPath, signature.mtimeMs, signature.size, result);
    return result;
  } catch {
    return { meta: null, classification: UNKNOWN_CLASSIFICATION };
  }
}
async function candidateEngagementFields(runtime, transcriptPath, signature, cache) {
  const { classification } = await candidateDerivedFields(
    runtime,
    transcriptPath,
    signature,
    cache
  );
  return engagementCandidateFields(classification);
}
function cwdCachePath() {
  const stateDir = process.env.STATE_DIR ?? join(homedir(), ".local", "state", "session-observer");
  return join(stateDir, "codex-cwd-cache.json");
}
async function loadCwdCache() {
  try {
    const raw = await readFile(cwdCachePath(), "utf8");
    return JSON.parse(raw);
  } catch {
    return {};
  }
}
async function saveCwdCache(cache) {
  try {
    const path = cwdCachePath();
    const dir = path.replace(/\/[^/]+$/, "");
    await mkdir(dir, { recursive: true });
    const tmp = join(
      dir,
      `codex-cwd-cache.${process.pid}.${Date.now()}.${randomUUID()}.tmp`
    );
    let fh;
    try {
      fh = await open(tmp, "w");
      await fh.write(JSON.stringify(cache, null, 2));
      await fh.datasync();
      await fh.close();
      fh = null;
      await rename(tmp, path);
    } finally {
      if (fh) {
        try {
          await fh.close();
        } catch {
        }
      }
      try {
        await unlink(tmp);
      } catch {
      }
    }
  } catch {
  }
}
function cwdCacheKey(transcriptPath, mtimeSec) {
  return `${transcriptPath}:${mtimeSec}`;
}
async function discoverClaudeCode(targetCwd, cache) {
  const [projectsRoot] = discoverPaths("claude-code");
  const encodedVariants = encodeCwdVariants("claude-code", targetCwd);
  const now = Date.now() / 1e3;
  const candidates = [];
  const seenTranscripts = /* @__PURE__ */ new Set();
  let directHit = false;
  for (const encoded of encodedVariants) {
    const encodedDir = join(projectsRoot, encoded);
    try {
      const entries = await readdir(encodedDir);
      const jsonlFiles = entries.filter((e) => e.endsWith(".jsonl"));
      for (const file of jsonlFiles) {
        const transcriptPath = join(encodedDir, file);
        if (seenTranscripts.has(transcriptPath)) continue;
        seenTranscripts.add(transcriptPath);
        let fileStat;
        try {
          fileStat = await stat(transcriptPath);
        } catch {
          continue;
        }
        const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
        const ageSec = now - mtime;
        const derived = await candidateDerivedFields(
          "claude-code",
          transcriptPath,
          fileStat,
          cache
        );
        const sessionId = derived.meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
        candidates.push({
          runtime: "claude-code",
          transcriptPath,
          sessionId,
          // Guaranteed exact match: do NOT use decodeCwdDirName (lossy).
          recordedCwd: targetCwd,
          cwdSlug: encoded,
          cwdEvidence: "direct-parent-dir",
          mtime,
          size: fileStat.size,
          ageSec,
          ...engagementCandidateFields(derived.classification)
        });
      }
      directHit = true;
    } catch {
    }
  }
  if (!directHit) {
    let projectDirs = [];
    try {
      projectDirs = await readdir(projectsRoot);
    } catch {
      return candidates;
    }
    for (const dirName of projectDirs) {
      if (encodedVariants.includes(dirName)) continue;
      const projectDir = join(projectsRoot, dirName);
      let dirEntries;
      try {
        dirEntries = await readdir(projectDir);
      } catch {
        continue;
      }
      const jsonlFiles = dirEntries.filter((e) => e.endsWith(".jsonl"));
      for (const file of jsonlFiles) {
        const transcriptPath = join(projectDir, file);
        if (seenTranscripts.has(transcriptPath)) continue;
        seenTranscripts.add(transcriptPath);
        let fileStat;
        try {
          fileStat = await stat(transcriptPath);
        } catch {
          continue;
        }
        const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
        const ageSec = now - mtime;
        const derived = await candidateDerivedFields(
          "claude-code",
          transcriptPath,
          fileStat,
          cache
        );
        const sessionId = derived.meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
        const recordedCwd = derived.meta?.recordedCwd ?? null;
        candidates.push({
          runtime: "claude-code",
          transcriptPath,
          sessionId,
          recordedCwd,
          cwdSlug: dirName,
          cwdEvidence: "decoded-parent-dir",
          mtime,
          size: fileStat.size,
          ageSec,
          ...engagementCandidateFields(derived.classification)
        });
      }
    }
  }
  return candidates;
}
async function claudeCodeLookupDiagnostics(targetCwd) {
  const [projectsRoot] = discoverPaths("claude-code");
  const diagnostics = [];
  for (const encoded of encodeCwdVariants("claude-code", targetCwd)) {
    const path = join(projectsRoot, encoded);
    let exists = false;
    try {
      const s = await stat(path);
      exists = s.isDirectory();
    } catch {
      exists = false;
    }
    diagnostics.push({ encoded, path, exists });
  }
  return diagnostics;
}
async function collectJsonlFiles(dir) {
  const results = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      const nested = await collectJsonlFiles(fullPath);
      results.push(...nested);
    } else if (entry.isFile() && entry.name.endsWith(".jsonl")) {
      results.push(fullPath);
    }
  }
  return results;
}
async function discoverCodex(_targetCwd, classificationCache) {
  const [sessionsRoot] = discoverPaths("codex");
  const now = Date.now() / 1e3;
  const cutoffSec = now - LOOKBACK_DAYS * 86400;
  const allFiles = await collectJsonlFiles(sessionsRoot);
  const cwdCache = await loadCwdCache();
  let cacheModified = false;
  const candidates = [];
  for (const transcriptPath of allFiles) {
    let fileStat;
    try {
      fileStat = await stat(transcriptPath);
    } catch {
      continue;
    }
    const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
    if (mtime < cutoffSec) continue;
    const ageSec = now - mtime;
    const key = cwdCacheKey(transcriptPath, mtime);
    let recordedCwd;
    let sessionId;
    if (cwdCache[key] && cwdCache[key].sessionId !== void 0) {
      recordedCwd = cwdCache[key].recordedCwd;
      sessionId = cwdCache[key].sessionId;
    } else {
      let meta;
      try {
        meta = await extractMeta("codex", transcriptPath);
      } catch {
        meta = null;
      }
      recordedCwd = meta?.recordedCwd ?? null;
      sessionId = meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, "");
      cwdCache[key] = { recordedCwd, sessionId };
      cacheModified = true;
    }
    candidates.push({
      runtime: "codex",
      transcriptPath,
      sessionId,
      recordedCwd,
      mtime,
      size: fileStat.size,
      ageSec,
      ...await candidateEngagementFields(
        "codex",
        transcriptPath,
        fileStat,
        classificationCache
      )
    });
  }
  if (cacheModified) {
    await saveCwdCache(cwdCache);
  }
  return candidates;
}
async function collectCursorAgentTranscripts(transcriptsRoot) {
  const results = [];
  let sessionDirs;
  try {
    sessionDirs = await readdir(transcriptsRoot, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const sessionDir of sessionDirs) {
    if (!sessionDir.isDirectory()) continue;
    const sessionPath = join(transcriptsRoot, sessionDir.name);
    let entries;
    try {
      entries = await readdir(sessionPath, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith(".jsonl")) {
        results.push(join(sessionPath, entry.name));
      }
    }
  }
  return results;
}
async function cursorCandidate(transcriptPath, now, evidence, fileStat, cache) {
  let resolvedStat = fileStat;
  if (!resolvedStat) {
    try {
      resolvedStat = await stat(transcriptPath);
    } catch {
      return null;
    }
  }
  const mtime = Math.floor(resolvedStat.mtime.getTime() / 1e3);
  const ageSec = now - mtime;
  const derived = await candidateDerivedFields(
    "cursor",
    transcriptPath,
    resolvedStat,
    cache
  );
  return {
    runtime: "cursor",
    transcriptPath,
    sessionId: derived.meta?.sessionId ?? basename(transcriptPath).replace(/\.jsonl$/, ""),
    recordedCwd: evidence.recordedCwd,
    cwdSlug: evidence.cwdSlug,
    cwdEvidence: evidence.cwdEvidence,
    mtime,
    size: resolvedStat.size,
    ageSec,
    ...engagementCandidateFields(derived.classification)
  };
}
async function discoverCursor(targetCwd, cache) {
  const [projectsRoot] = discoverPaths("cursor");
  const encodedVariants = encodeCwdVariants("cursor", targetCwd);
  const now = Date.now() / 1e3;
  const cutoffSec = now - LOOKBACK_DAYS * 86400;
  const candidates = [];
  const seenTranscripts = /* @__PURE__ */ new Set();
  let directHit = false;
  for (const encoded of encodedVariants) {
    const transcriptsRoot = join(projectsRoot, encoded, "agent-transcripts");
    const transcriptPaths = await collectCursorAgentTranscripts(transcriptsRoot);
    if (transcriptPaths.length === 0) continue;
    directHit = true;
    for (const transcriptPath of transcriptPaths) {
      if (seenTranscripts.has(transcriptPath)) continue;
      seenTranscripts.add(transcriptPath);
      const candidate = await cursorCandidate(
        transcriptPath,
        now,
        {
          recordedCwd: targetCwd,
          cwdSlug: encoded,
          cwdEvidence: "direct-parent-dir"
        },
        null,
        cache
      );
      if (candidate) candidates.push(candidate);
    }
  }
  if (directHit) return candidates;
  let projectDirs = [];
  try {
    projectDirs = await readdir(projectsRoot, { withFileTypes: true });
  } catch {
    return candidates;
  }
  for (const projectDir of projectDirs) {
    if (!projectDir.isDirectory()) continue;
    if (encodedVariants.includes(projectDir.name)) continue;
    const transcriptsRoot = join(
      projectsRoot,
      projectDir.name,
      "agent-transcripts"
    );
    const transcriptPaths = await collectCursorAgentTranscripts(transcriptsRoot);
    for (const transcriptPath of transcriptPaths) {
      if (seenTranscripts.has(transcriptPath)) continue;
      seenTranscripts.add(transcriptPath);
      let fileStat;
      try {
        fileStat = await stat(transcriptPath);
      } catch {
        continue;
      }
      const mtime = Math.floor(fileStat.mtime.getTime() / 1e3);
      if (mtime < cutoffSec) continue;
      const candidate = await cursorCandidate(
        transcriptPath,
        now,
        {
          recordedCwd: null,
          cwdSlug: projectDir.name,
          cwdEvidence: "project-dir-slug"
        },
        fileStat,
        cache
      );
      if (candidate) candidates.push(candidate);
    }
  }
  return candidates;
}
async function discover(runtime, targetCwd, cache = new ClassificationCache()) {
  if (runtime === "claude-code") return discoverClaudeCode(targetCwd, cache);
  if (runtime === "codex") return discoverCodex(targetCwd, cache);
  if (runtime === "cursor") return discoverCursor(targetCwd, cache);
  throw new Error(`Unknown runtime: ${runtime}`);
}
async function findSessionCandidate(runtime, targetCwd, sessionId) {
  const matches = (await discover(runtime, targetCwd)).filter(
    (candidate) => candidate.recordedCwd === targetCwd && candidate.sessionId === sessionId
  );
  return matches.length === 1 ? matches[0] : null;
}
async function findNewerSameCwdCandidates(runtime, targetCwd, watched, cache = new ClassificationCache()) {
  const candidates = await discover(runtime, targetCwd, cache);
  return candidates.filter(
    (candidate) => candidate.recordedCwd === targetCwd && candidate.sessionId !== watched.sessionId && candidate.transcriptPath !== watched.transcriptPath && candidate.mtime > watched.mtime
  ).toSorted(
    (left, right) => right.mtime - left.mtime || left.transcriptPath.localeCompare(right.transcriptPath)
  );
}
async function gitWorktrees(cwd) {
  try {
    const { stdout } = await execFileAsync(
      "git",
      ["-C", cwd, "worktree", "list", "--porcelain"],
      {
        timeout: 5e3
      }
    );
    const paths = [];
    for (const line of stdout.split("\n")) {
      if (line.startsWith("worktree ")) {
        paths.push(line.slice("worktree ".length).trim());
      }
    }
    return paths;
  } catch {
    return [];
  }
}
export {
  ClassificationCache,
  claudeCodeLookupDiagnostics,
  discover,
  findNewerSameCwdCandidates,
  findSessionCandidate,
  gitWorktrees
};
