// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/transcript/session-observer/lib/rank.ts
import { realpathSync } from "node:fs";
const TIE_WINDOW_SEC = 5;
const ACTIVE_THRESHOLD_SEC = 60;
const CLOSE_REAL_MESSAGE_DELTA = 2;
const CLOSE_SIZE_RATIO = 0.9;
const CLOSE_SIZE_ABS = 4096;
function stripTrailingSlashes(path) {
  if (path === "/") return path;
  return path.replace(/\/+$/u, "");
}
function realpathSafe(path) {
  try {
    return realpathSync.native(path);
  } catch {
    return path;
  }
}
function normalizeCwdPath(path) {
  return stripTrailingSlashes(realpathSafe(path));
}
function tierOf(candidate, targetCwd) {
  const { recordedCwd } = candidate;
  if (!recordedCwd) return "C";
  const normalizedRecordedCwd = normalizeCwdPath(recordedCwd);
  const normalizedTargetCwd = normalizeCwdPath(targetCwd);
  if (normalizedRecordedCwd === normalizedTargetCwd) return "A";
  if (normalizedRecordedCwd.startsWith(normalizedTargetCwd + "/")) return "B";
  if (normalizedTargetCwd.startsWith(normalizedRecordedCwd + "/")) return "B";
  return "C";
}
function cwdSlugVariants(cwd) {
  return [
    .../* @__PURE__ */ new Set([
      cwd.split(/[/.]/u).filter(Boolean).join("-"),
      cwd.replace(/[/.]/g, "-"),
      cwd.replace(/\//g, "-")
    ])
  ];
}
function slugFromTranscriptPath(transcriptPath) {
  const marker = "/.claude/projects/";
  const index = transcriptPath.indexOf(marker);
  if (index === -1) return null;
  const rest = transcriptPath.slice(index + marker.length);
  const slash = rest.indexOf("/");
  return slash === -1 ? rest : rest.slice(0, slash);
}
function parentSlugMatches(candidate, targetCwd) {
  const slug = candidate.cwdSlug ?? slugFromTranscriptPath(candidate.transcriptPath ?? "");
  if (!slug) return false;
  return cwdSlugVariants(targetCwd).includes(slug);
}
function engagementStatus(candidate) {
  const status = candidate.engagementStatus ?? candidate.engagement?.status;
  return status === "unengaged" ? "unengaged" : "engaged";
}
function isEngaged(candidate) {
  return engagementStatus(candidate) !== "unengaged";
}
function metric(candidate, key) {
  const value = candidate[key] ?? candidate.engagement?.[key];
  return Number.isFinite(Number(value)) ? Number(value) : 0;
}
function hasAssistantAndUser(candidate) {
  return Boolean(
    candidate.hasAssistantAndUser ?? candidate.engagement?.hasAssistantAndUser
  );
}
function compareCandidatePreference(a, b) {
  if (isEngaged(a) !== isEngaged(b)) return isEngaged(a) ? -1 : 1;
  if (hasAssistantAndUser(a) !== hasAssistantAndUser(b)) {
    return hasAssistantAndUser(a) ? -1 : 1;
  }
  const realMessageDelta = metric(b, "realMessageCount") - metric(a, "realMessageCount");
  if (realMessageDelta !== 0) return realMessageDelta;
  const userDelta = metric(b, "genuineUserMessages") - metric(a, "genuineUserMessages");
  if (userDelta !== 0) return userDelta;
  const assistantDelta = metric(b, "assistantMessages") - metric(a, "assistantMessages");
  if (assistantDelta !== 0) return assistantDelta;
  const sizeDelta = (b.size ?? 0) - (a.size ?? 0);
  if (sizeDelta !== 0) return sizeDelta;
  return (b.mtime ?? 0) - (a.mtime ?? 0);
}
function sizesClose(a, b) {
  const aSize = Number(a.size ?? 0);
  const bSize = Number(b.size ?? 0);
  const diff = Math.abs(aSize - bSize);
  if (diff <= CLOSE_SIZE_ABS) return true;
  const larger = Math.max(aSize, bSize);
  const smaller = Math.min(aSize, bSize);
  if (larger === 0) return true;
  return smaller / larger >= CLOSE_SIZE_RATIO;
}
function closeEngagedTie(winner, candidate, tieWindowSec) {
  if (!isEngaged(winner) || !isEngaged(candidate)) return false;
  if (hasAssistantAndUser(winner) !== hasAssistantAndUser(candidate))
    return false;
  if (Math.abs(
    metric(winner, "realMessageCount") - metric(candidate, "realMessageCount")
  ) > CLOSE_REAL_MESSAGE_DELTA)
    return false;
  if (!sizesClose(winner, candidate)) return false;
  return Math.abs((winner.mtime ?? 0) - (candidate.mtime ?? 0)) <= tieWindowSec;
}
function rank(candidates, targetCwd, opts = {}) {
  const {
    tieWindowSec = TIE_WINDOW_SEC,
    gitWorktrees = [],
    globalRecentProvider
  } = opts;
  const byTier = { A: [], B: [], C: [] };
  for (const c of candidates) {
    const tier = tierOf(c, targetCwd);
    if (tier === "A" || tier === "B") {
      byTier[tier].push(c);
    } else if (parentSlugMatches(c, targetCwd)) {
      byTier.C.push(c);
    }
  }
  let winningTier = null;
  let winningPool = null;
  if (byTier.A.length > 0) {
    winningTier = "A";
    winningPool = byTier.A;
  } else if (byTier.B.length > 0) {
    winningTier = "B";
    winningPool = byTier.B;
  } else if (byTier.C.length > 0) {
    winningTier = "C";
    winningPool = byTier.C;
  }
  if (!winningTier) {
    const allByMtime = [...candidates].toSorted(
      (a, b) => b.mtime - a.mtime
    );
    const globalRecent = globalRecentProvider ? globalRecentProvider() : allByMtime.slice(0, 5);
    return {
      winner: null,
      noMatch: true,
      sisters: Array.isArray(gitWorktrees) ? gitWorktrees : [],
      globalRecent
    };
  }
  const engagedPool = winningPool.filter(isEngaged);
  const unengagedPool = winningPool.filter(
    (candidate) => !isEngaged(candidate)
  );
  if (engagedPool.length === 0) {
    return {
      winner: null,
      unengagedOnly: true,
      tier: winningTier,
      candidates: [...unengagedPool].toSorted(compareCandidatePreference),
      message: "Only unengaged sessions matched this cwd."
    };
  }
  const sorted = [...engagedPool].toSorted(compareCandidatePreference);
  const winner = sorted[0];
  const annotatedWinner = {
    ...winner,
    active: winner.ageSec < ACTIVE_THRESHOLD_SEC
  };
  const ties = sorted.slice(1).filter((c) => closeEngagedTie(winner, c, tieWindowSec));
  const fallbacks = [
    ...sorted.slice(1),
    ...unengagedPool.toSorted(compareCandidatePreference)
  ];
  return {
    winner: annotatedWinner,
    tier: winningTier,
    ties,
    fallbacks
  };
}
export {
  rank,
  realpathSafe,
  tierOf
};
