// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/transcript/session-observer/lib/state.ts
import {
  access,
  open,
  rename,
  mkdir,
  readFile,
  unlink
} from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import {
  clearCursorState,
  cursorSessionKey,
  loadCursorState,
  mutateCursorState,
  resetAllCursorState,
  resetCursorSessionState
} from './cursor-state.mjs';
const SCHEMA_VERSION = 1;
const LOCK_RETRIES = 100;
const LOCK_INTERVAL_MS = 50;
let migrationBackupSequence = 0;
function isErrnoException(err) {
  return err instanceof Error && "code" in err;
}
function stateDir() {
  return process.env.STATE_DIR ?? join(homedir(), ".local", "state", "session-observer");
}
function statePath(dir) {
  return join(dir, "state.json");
}
function lockPath(dir) {
  return join(dir, "state.json.lock");
}
function tmpPath(dir) {
  return join(dir, `state.json.${process.pid}.tmp`);
}
function bakPath(dir, label) {
  return join(dir, `state.json.${label}-${Date.now()}-${process.pid}.bak`);
}
async function acquireLock(lock) {
  for (let i = 0; i < LOCK_RETRIES; i++) {
    try {
      const fh = await open(lock, "wx");
      await fh.close();
      return;
    } catch (err) {
      if (!isErrnoException(err) || err.code !== "EEXIST") throw err;
      await sleep(LOCK_INTERVAL_MS);
    }
  }
  throw new Error(
    `state.mjs: could not acquire lock after ${LOCK_RETRIES} retries`
  );
}
async function releaseLock(lock) {
  try {
    await unlink(lock);
  } catch {
  }
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function emptyState() {
  return { schemaVersion: SCHEMA_VERSION, sessions: {} };
}
async function writeBackup(dir, label, content) {
  const bak = bakPath(dir, label);
  const tmp = bak + ".tmp";
  let fh;
  try {
    fh = await open(tmp, "w");
    await fh.write(content);
    await fh.datasync();
    await fh.close();
    fh = null;
    await rename(tmp, bak);
  } catch {
  } finally {
    if (fh) {
      try {
        await fh.close();
      } catch {
      }
    }
    try {
      await unlink(tmp);
    } catch {
    }
  }
}
async function readState(dir) {
  const file = statePath(dir);
  let raw;
  try {
    raw = await readFile(file, "utf8");
  } catch (err) {
    if (isErrnoException(err) && err.code === "ENOENT") return emptyState();
    throw err;
  }
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    await writeBackup(dir, "corrupt", raw);
    return emptyState();
  }
  return migrateIfNeeded(parsed, dir, raw);
}
async function migrateIfNeeded(parsed, dir, rawBackup) {
  const state = parsed;
  if (typeof state.schemaVersion === "number" && state.schemaVersion >= SCHEMA_VERSION) {
    return state;
  }
  await writeBackup(dir, "v0", rawBackup ?? JSON.stringify(parsed));
  return {
    schemaVersion: SCHEMA_VERSION,
    sessions: state.sessions ?? {}
  };
}
async function writeState(dir, state) {
  await mkdir(dir, { recursive: true });
  const tmp = tmpPath(dir);
  const dest = statePath(dir);
  let fh;
  try {
    fh = await open(tmp, "w");
    await fh.write(JSON.stringify(state, null, 2));
    await fh.datasync();
    await fh.close();
    fh = null;
    await rename(tmp, dest);
  } finally {
    if (fh) {
      try {
        await fh.close();
      } catch {
      }
    }
    try {
      await unlink(tmp);
    } catch {
    }
  }
}
function sessionKey(runtime, sessionId) {
  return `${runtime}:${sessionId}`;
}
function zeroSession(entry) {
  return {
    ...entry,
    lastRecordIndex: 0,
    lastTotalRecords: 0
  };
}
async function loadLegacyState() {
  const dir = stateDir();
  await mkdir(dir, { recursive: true });
  const lock = lockPath(dir);
  await acquireLock(lock);
  try {
    return await readState(dir);
  } finally {
    await releaseLock(lock);
  }
}
async function notifyMigrationBoundary(options, boundary) {
  await options.onBoundary?.(boundary);
}
function nextMigrationBackupPath(dir) {
  migrationBackupSequence += 1;
  return join(
    dir,
    `state.json.cursor-legacy-${Date.now()}-${process.pid}-${migrationBackupSequence}.bak`
  );
}
async function pathExists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
async function writeMigrationBackup(dir, destination, raw) {
  if (dirname(destination) !== dir) {
    throw new Error("LEGACY_BACKUP_PATH_INVALID");
  }
  if (await pathExists(destination)) return;
  const temporary = `${destination}.${process.pid}.tmp`;
  let handle;
  try {
    handle = await open(temporary, "w", 384);
    await handle.writeFile(raw, "utf8");
    await handle.datasync();
    await handle.close();
    handle = void 0;
    await rename(temporary, destination);
  } finally {
    if (handle) await handle.close();
    try {
      await unlink(temporary);
    } catch {
    }
  }
}
async function removeLegacyCursorForMigration(marker, options) {
  const dir = stateDir();
  if (dirname(marker.backupPath) !== dir) {
    throw new Error("LEGACY_BACKUP_PATH_INVALID");
  }
  await mkdir(dir, { recursive: true });
  const lock = lockPath(dir);
  await acquireLock(lock);
  try {
    const state = await readState(dir);
    const key = sessionKey("cursor", marker.sessionId);
    const entry = state.sessions[key];
    if (!entry) {
      if (!await pathExists(marker.backupPath)) {
        throw new Error("LEGACY_BACKUP_MISSING");
      }
      return;
    }
    if (entry.runtime !== "cursor" || !Number.isSafeInteger(entry.lastRecordIndex) || entry.lastRecordIndex < 0 || entry.lastRecordIndex !== marker.legacyLastRecordIndex) {
      throw new Error("LEGACY_CURSOR_CHANGED");
    }
    const raw = await readFile(statePath(dir), "utf8");
    await writeMigrationBackup(dir, marker.backupPath, raw);
    await notifyMigrationBoundary(options, "backup-written");
    delete state.sessions[key];
    await writeState(dir, state);
    await notifyMigrationBoundary(options, "legacy-removed");
  } finally {
    await releaseLock(lock);
  }
}
async function migrateLegacyCursorState(sessionId, options = {}) {
  const key = cursorSessionKey(sessionId);
  let cursorState = await loadCursorState();
  let marker = cursorState.legacyUnverified[key];
  if (!marker) {
    const legacy = await loadLegacyState();
    const entry = legacy.sessions[sessionKey("cursor", sessionId)];
    if (!entry) return null;
    if (entry.runtime !== "cursor" || !Number.isSafeInteger(entry.lastRecordIndex) || entry.lastRecordIndex < 0) {
      throw new Error("LEGACY_CURSOR_INVALID");
    }
    const proposed = {
      runtime: "cursor",
      sessionId,
      legacyLastRecordIndex: entry.lastRecordIndex,
      backupPath: nextMigrationBackupPath(stateDir()),
      migrationStatus: "marker-written",
      createdAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    cursorState = await mutateCursorState((state) => {
      state.legacyUnverified[key] ??= proposed;
    });
    marker = cursorState.legacyUnverified[key];
    await notifyMigrationBoundary(options, "marker-written");
  }
  await removeLegacyCursorForMigration(marker, options);
  cursorState = await mutateCursorState((state) => {
    const current = state.legacyUnverified[key];
    if (!current) throw new Error("LEGACY_CURSOR_MARKER_MISSING");
    if (current.migrationStatus === "marker-written") {
      current.migrationStatus = "legacy-removed";
    }
  });
  marker = cursorState.legacyUnverified[key];
  await notifyMigrationBoundary(options, "marker-legacy-removed");
  cursorState = await mutateCursorState((state) => {
    const current = state.legacyUnverified[key];
    if (!current) throw new Error("LEGACY_CURSOR_MARKER_MISSING");
    if (current.migrationStatus !== "complete") {
      current.migrationStatus = "complete";
    }
  });
  marker = cursorState.legacyUnverified[key];
  await notifyMigrationBoundary(options, "complete");
  return marker;
}
function cursorRecoveryEntry(marker) {
  return {
    runtime: "cursor",
    sessionId: marker.sessionId,
    lastRecordIndex: 0,
    lastTotalRecords: marker.legacyLastRecordIndex,
    recoveryRequired: true,
    recoveryCode: "LEGACY_CURSOR_UNVERIFIED",
    legacyLastRecordIndex: marker.legacyLastRecordIndex,
    migrationStatus: marker.migrationStatus,
    backupPath: marker.backupPath
  };
}
async function load() {
  let legacy = await loadLegacyState();
  const legacyCursorIds = Object.values(legacy.sessions).filter((entry) => entry.runtime === "cursor").map((entry) => entry.sessionId);
  for (const sessionId of legacyCursorIds) {
    await migrateLegacyCursorState(sessionId);
  }
  legacy = await loadLegacyState();
  const cursor = await loadCursorState();
  const sessions = { ...legacy.sessions };
  for (const entry of Object.values(cursor.sessions)) {
    sessions[cursorSessionKey(entry.sessionId)] = {
      runtime: "cursor",
      sessionId: entry.sessionId,
      lastRecordIndex: entry.lastRecordIndex,
      lastTotalRecords: entry.lastRecordIndex,
      transcriptPath: entry.transcriptPath,
      recordedCwd: entry.canonicalCwd,
      indexBase: entry.indexBase,
      continuity: entry.continuity,
      lastStatus: entry.lastStatus,
      recoveryRequired: false
    };
  }
  for (const marker of Object.values(cursor.legacyUnverified)) {
    sessions[cursorSessionKey(marker.sessionId)] = cursorRecoveryEntry(marker);
  }
  return { schemaVersion: SCHEMA_VERSION, sessions };
}
async function mutate(fn) {
  const dir = stateDir();
  await mkdir(dir, { recursive: true });
  const lock = lockPath(dir);
  await acquireLock(lock);
  try {
    const current = await readState(dir);
    const next = fn(current) ?? current;
    await writeState(dir, next);
    return next;
  } finally {
    await releaseLock(lock);
  }
}
async function getSession(runtime, sessionId) {
  if (runtime === "cursor") {
    const marker = await migrateLegacyCursorState(sessionId);
    if (marker) {
      throw new Error(
        `LEGACY_CURSOR_UNVERIFIED: reset cursor:${sessionId} to replay from frame zero`
      );
    }
    const cursor = await loadCursorState();
    if (cursor.sessions[cursorSessionKey(sessionId)]) {
      throw new Error(
        "CURSOR_STATE_V2_REQUIRES_OBSERVATION_PROJECTION: legacy record-index reads are disabled"
      );
    }
    return null;
  }
  const state = await loadLegacyState();
  const key = sessionKey(runtime, sessionId);
  return state.sessions[key] ?? null;
}
async function markRead(runtime, sessionId, {
  lastRecordIndex,
  lastTotalRecords,
  transcriptPath,
  recordedCwd
}) {
  if (runtime === "cursor") {
    throw new Error(
      "CURSOR_STATE_V2_REQUIRED: legacy record-index Cursor writes are disabled"
    );
  }
  const key = sessionKey(runtime, sessionId);
  await mutate((state) => {
    const existing = state.sessions[key] ?? {};
    state.sessions[key] = {
      ...existing,
      runtime,
      sessionId,
      lastRecordIndex,
      lastTotalRecords,
      lastReadAt: (/* @__PURE__ */ new Date()).toISOString(),
      transcriptPath,
      recordedCwd,
      watchedByPid: existing.watchedByPid ?? null
    };
    return state;
  });
}
async function setWatchedByPid(runtime, sessionId, pid) {
  if (runtime === "cursor") {
    throw new Error(
      "CURSOR_STATE_V2_REQUIRED: legacy Cursor watcher ownership is disabled"
    );
  }
  const key = sessionKey(runtime, sessionId);
  let updated = false;
  await mutate((state) => {
    const existing = state.sessions[key];
    if (!existing) return state;
    state.sessions[key] = {
      ...existing,
      watchedByPid: pid
    };
    updated = true;
    return state;
  });
  return updated;
}
async function clearWatchedByPid(runtime, sessionId, pid) {
  if (runtime === "cursor") {
    throw new Error(
      "CURSOR_STATE_V2_REQUIRED: legacy Cursor watcher ownership is disabled"
    );
  }
  const key = sessionKey(runtime, sessionId);
  let updated = false;
  await mutate((state) => {
    const existing = state.sessions[key];
    if (!existing) return state;
    if (pid !== void 0 && existing.watchedByPid !== pid) return state;
    state.sessions[key] = {
      ...existing,
      watchedByPid: null
    };
    updated = true;
    return state;
  });
  return updated;
}
async function resetByRuntime(runtime) {
  if (runtime === "cursor") {
    const cursor = await loadCursorState();
    const sessionIds = /* @__PURE__ */ new Set([
      ...Object.values(cursor.sessions).map((entry) => entry.sessionId),
      ...Object.values(cursor.legacyUnverified).map(
        (marker) => marker.sessionId
      )
    ]);
    await mutate((state) => {
      for (const [key, entry] of Object.entries(state.sessions)) {
        if (entry.runtime === "cursor") {
          delete state.sessions[key];
          sessionIds.add(entry.sessionId);
        }
      }
    });
    await resetAllCursorState();
    return sessionIds.size;
  }
  let count = 0;
  await mutate((state) => {
    for (const [key, entry] of Object.entries(state.sessions)) {
      if (entry.runtime === runtime) {
        state.sessions[key] = zeroSession(entry);
        count++;
      }
    }
    return state;
  });
  return count;
}
async function resetBySession(runtime, sessionId) {
  if (runtime === "cursor") {
    const key2 = sessionKey(runtime, sessionId);
    await mutate((state) => {
      delete state.sessions[key2];
    });
    await resetCursorSessionState(sessionId);
    return;
  }
  const key = sessionKey(runtime, sessionId);
  await mutate((state) => {
    if (state.sessions[key]) {
      state.sessions[key] = zeroSession(state.sessions[key]);
    }
    return state;
  });
}
async function clear() {
  await mutate((state) => {
    state.sessions = {};
    return state;
  });
  await clearCursorState();
}
export {
  clear,
  clearWatchedByPid,
  getSession,
  load,
  markRead,
  migrateLegacyCursorState,
  mutate,
  resetByRuntime,
  resetBySession,
  setWatchedByPid
};
