// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/consensus/refine/consensus-refine.ts
import { execFile } from "node:child_process";
import { randomBytes } from "node:crypto";
import {
  lstat,
  mkdir,
  open,
  readFile,
  realpath,
  rename,
  stat,
  unlink,
  writeFile
} from "node:fs/promises";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { resolveConsensusComposition } from './consensus-config.mjs';
import {
  callsPerRound,
  ConsensusError,
  consensusProviderCliMissingError,
  EXIT_CODES,
  exitCodeForError,
  hashArtifact,
  invokeConsensusProviderCli,
  invokeProviderCliWithRetry,
  invalidIterationModeError,
  ITERATION_MODES,
  peerSchemaPathForMode,
  providerCliSpawnTarget,
  requireConsensusCliPath,
  runConsensusLoop
} from '../../../scripts/consensus-loop.mjs';
import {
  isJsonRecord,
  asErrorLike,
  asConsensusRecord,
  asConsensusRecords,
  asSectionStatus,
  inside,
  nearestExistingPath,
  syncPathIfAvailable,
  nowIso,
  writeJsonl,
  renderHumanError,
  consensusBlockPattern,
  readInputFile,
  confineWrite,
  atomicWriteFile,
  resolveRunDir,
  resolveOutputPath,
  resolveResumePath,
  readJsonFile,
  readJsonIfPresent,
  readTextIfPresent
} from './refine-shared.mjs';
import {
  INPUT_SIZE_CAP_BYTES,
  createJsonlEvent,
  renderHumanError as renderHumanError2,
  readInputFile as readInputFile2,
  confineWrite as confineWrite2,
  atomicWriteFile as atomicWriteFile2,
  resolveRunDir as resolveRunDir2,
  resolveOutputPath as resolveOutputPath2,
  resolveResumePath as resolveResumePath2
} from './refine-shared.mjs';
import {
  parseWrapperArgs,
  normalizeProviderInventory,
  resolveSynthesizer
} from './refine-args.mjs';
import {
  PROVIDER_ID_PATTERN,
  parseWrapperArgs as parseWrapperArgs2,
  resolvePeers,
  resolveSynthesizer as resolveSynthesizer2
} from './refine-args.mjs';
import {
  parseSections,
  normalizeSequentialOptions,
  sectionRunDirectory,
  sectionLookup,
  sequentialRunSections,
  loopArgvForSection,
  parallelismFor,
  manifestSectionEntry,
  dispatchInstructions
} from './refine-sections.mjs';
import { slugSectionId, parseSections as parseSections2 } from './refine-sections.mjs';
import {
  canonicalJsonBlock,
  latestRevisedOutput,
  fallbackErrorStatus,
  aggregateStatus,
  aggregateParallelStatus,
  renderDeliberationArtifact
} from './refine-render.mjs';
import { renderDeliberationArtifact as renderDeliberationArtifact2 } from './refine-render.mjs';
import { parseDeliberationArtifactForResume } from './refine-resume.mjs';
import { parseDeliberationArtifactForResume as parseDeliberationArtifactForResume2 } from './refine-resume.mjs';
import {
  buildEscalationEvent,
  escalatedSections,
  assertHostDirectionRoutable,
  failingSections
} from './refine-escalation.mjs';
import { buildEscalationEvent as buildEscalationEvent2 } from './refine-escalation.mjs';
import {
  pathConfinementError,
  resolveManifestPathValue,
  assertPathResolvesInside,
  normalizeParallelManifest
} from './refine-manifest.mjs';
const execFileAsync = promisify(execFile);
function asLoopInitialRecords(records) {
  return records ?? [];
}
async function defaultRunCommand(command, args, options = {}) {
  const spawnTarget = providerCliSpawnTarget(command, args);
  const result = await execFileAsync(spawnTarget.command, spawnTarget.args, {
    cwd: options.cwd,
    env: options.env,
    maxBuffer: 2 * 1024 * 1024
  });
  return { stdout: result.stdout, stderr: result.stderr };
}
function detectHost(env = process.env) {
  if (env.CLAUDECODE || env.CLAUDE_CODE || env.CLAUDECODE_SESSION_ID) {
    return "claude";
  }
  if (Object.keys(env).some((key) => key.startsWith("CODEX_"))) {
    return "codex";
  }
  if (Object.keys(env).some((key) => key.startsWith("CURSOR_"))) {
    return "cursor";
  }
  return "unknown";
}
function providerCliLoopInvokers({
  env,
  cwd,
  iteration
}) {
  return {
    invokePeer: (turn) => invokeProviderCliWithRetry(
      {
        provider: turn.provider,
        schemaPath: turn.schemaPath ?? peerSchemaPathForMode(iteration),
        prompt: turn.prompt,
        env,
        cwd
      },
      { mode: iteration }
    ),
    invokeSynthesizer: (call) => invokeConsensusProviderCli({
      provider: call.provider,
      schemaPath: call.schemaPath,
      prompt: call.prompt,
      env,
      cwd
    })
  };
}
async function runSequential(options, runOptions = {}) {
  const normalized = normalizeSequentialOptions(options);
  const cwd = path.resolve(normalized.cwd ?? runOptions.cwd ?? process.cwd());
  const env = normalized.env ?? runOptions.env ?? process.env;
  const inputPathValue = normalized.inputPath;
  const inputPath = path.isAbsolute(inputPathValue) ? inputPathValue : path.resolve(cwd, inputPathValue);
  const startedAt = nowIso();
  const startMs = Date.now();
  const markdown = await readInputFile(inputPath);
  const parsedSections = parseSections(markdown);
  const runDir = await resolveRunDir({ ...normalized, cwd });
  const outputPath = await resolveOutputPath({ ...normalized, cwd }, inputPath);
  const resumePath = await resolveResumePath({ ...normalized, cwd });
  const resumeState = resumePath ? await parseDeliberationArtifactForResume(resumePath, {
    runDir,
    skipCorruptSections: normalized.skipCorruptSections,
    skipAllCorrupt: normalized.skipAllCorrupt,
    yesSkipCorrupt: normalized.yesSkipCorrupt,
    stdin: runOptions.stdin,
    stdout: runOptions.stdout
  }) : null;
  const runWriteRoot = path.resolve(normalized.allowRoot ?? cwd);
  const outputWriteRoot = normalized.output ? path.resolve(normalized.allowRoot ?? cwd) : path.dirname(inputPath);
  const preflight = normalized.preflight === false ? { peers: normalized.peers ?? ["claude", "codex"], warnings: [] } : await (normalized.preflight ?? preflightConsensusProviderCli)({
    ...normalized,
    env,
    cwd
  });
  const peers = normalized.peers ?? preflight.peers;
  const host = preflight.host ?? detectHost(env);
  const { synthesizer } = resolveSynthesizer(
    { ...normalized, peers },
    preflight.providerInventory ?? peers.map((id) => ({ id, available: true }))
  );
  const resumeSections = sectionLookup(resumeState?.sections);
  const runSections = sequentialRunSections(parsedSections, resumeState);
  const sectionResults = [];
  const providerCliInvokers = providerCliLoopInvokers({
    env,
    cwd,
    iteration: normalized.iteration
  });
  for (const section of runSections) {
    const sectionDir = sectionRunDirectory(runDir, section);
    const paths = {
      input: path.join(sectionDir, "section.md"),
      records: path.join(sectionDir, "records.json"),
      output: path.join(sectionDir, "output.md"),
      status: path.join(sectionDir, "status.json")
    };
    const resumeSection = resumeSections.get(`id:${section.id}`) ?? resumeSections.get(`index:${section.original_index}`) ?? null;
    const sectionInput = resumeSection?.resumedArtifact ?? section.markdown;
    await Promise.all([
      confineWrite(paths.records, runWriteRoot),
      confineWrite(paths.output, runWriteRoot),
      confineWrite(paths.status, runWriteRoot)
    ]);
    await atomicWriteFile(paths.input, sectionInput, {
      rootPath: runWriteRoot
    });
    if (resumeSection?.skipped) {
      const status = {
        schema_version: "v1",
        status: "skipped",
        termination_reason: "corrupt_resume_skipped",
        turns: 0,
        rounds: 0,
        final_artifact_hash: hashArtifact(section.markdown),
        resume_errors: resumeSection.corruptErrors
      };
      await Promise.all([
        atomicWriteFile(
          paths.records,
          `${JSON.stringify(resumeSection.records, null, 2)}
`,
          { rootPath: runWriteRoot }
        ),
        atomicWriteFile(paths.output, section.markdown, {
          rootPath: runWriteRoot
        }),
        atomicWriteFile(paths.status, `${JSON.stringify(status, null, 2)}
`, {
          rootPath: runWriteRoot
        })
      ]);
      sectionResults.push({
        ...section,
        paths,
        output: section.markdown,
        status,
        records: resumeSection.records
      });
      continue;
    }
    if (resumeSection?.completed) {
      await Promise.all([
        atomicWriteFile(
          paths.records,
          `${JSON.stringify(resumeSection.records, null, 2)}
`,
          { rootPath: runWriteRoot }
        ),
        atomicWriteFile(paths.output, sectionInput, { rootPath: runWriteRoot }),
        atomicWriteFile(
          paths.status,
          `${JSON.stringify(resumeSection.status, null, 2)}
`,
          { rootPath: runWriteRoot }
        )
      ]);
      sectionResults.push({
        ...section,
        paths,
        output: sectionInput,
        status: resumeSection.status,
        records: resumeSection.records
      });
      continue;
    }
    let hostDirection;
    let hostDecisionKind;
    let escalationTrigger = null;
    if (normalized.hostDirection && resumeSection?.inFlight) {
      const escalation = assertHostDirectionRoutable(resumeSection);
      hostDirection = normalized.hostDirection;
      hostDecisionKind = normalized.hostDecisionKind ?? "direct";
      escalationTrigger = escalation.trigger;
    }
    try {
      const loopRunOptions = {
        env,
        cwd,
        invokePeer: normalized.invokePeer ?? runOptions.invokePeer ?? providerCliInvokers.invokePeer,
        invokeSynthesizer: normalized.invokeSynthesizer ?? runOptions.invokeSynthesizer ?? providerCliInvokers.invokeSynthesizer,
        initialRecords: asLoopInitialRecords(resumeSection?.records),
        initialArtifact: sectionInput,
        userDirection: resumeSection?.inFlight ? normalized.userDirection ?? void 0 : void 0,
        hostDirection,
        hostDecisionKind,
        escalationTrigger
      };
      const result = await runConsensusLoop(
        loopArgvForSection({
          section,
          paths,
          options: normalized,
          peers,
          synthesizer
        }),
        loopRunOptions
      );
      sectionResults.push({
        ...section,
        paths,
        output: result.output,
        status: result.status,
        records: result.records
      });
    } catch (error) {
      const records = await readJsonIfPresent(
        paths.records,
        []
      );
      const persistedStatus = await readJsonIfPresent(
        paths.status,
        null
      );
      const recoveredOutput = await readTextIfPresent(paths.output) ?? latestRevisedOutput(records, section.markdown);
      const status = {
        ...fallbackErrorStatus(error, records, peers.length),
        ...persistedStatus
      };
      if (!status.error) {
        status.error = asErrorLike(error).message;
      }
      sectionResults.push({
        ...section,
        paths,
        output: recoveredOutput,
        status,
        records
      });
    }
  }
  const endedAt = nowIso();
  const runResult = {
    mode: "sequential",
    parallel: false,
    inputPath,
    outputPath,
    resumePath,
    resumeState,
    runDir,
    goal: normalized.goal,
    peers,
    host,
    agency: normalized.agency,
    iteration: normalized.iteration ?? "alternating",
    synthesizer,
    coldStart: normalized.coldStart ?? "shared_input",
    maxRounds: normalized.maxRounds,
    startedAt,
    endedAt,
    wallClockMs: Date.now() - startMs,
    sections: sectionResults
  };
  runResult.status = aggregateStatus(sectionResults);
  const artifact = renderDeliberationArtifact(runResult);
  await atomicWriteFile(outputPath, artifact, { rootPath: outputWriteRoot });
  if (runOptions.stdout) {
    for (const section of escalatedSections(sectionResults)) {
      const event = buildEscalationEvent(section, { artifactPath: outputPath });
      if (event) {
        writeJsonl(runOptions.stdout, "escalation_required", event);
      }
    }
  }
  const failedSections = failingSections(sectionResults);
  if (normalized.failOnSectionError && failedSections.length > 0) {
    throw new ConsensusError(
      `section error or impasse in ${failedSections.length} section(s)`,
      {
        code: "SECTION_ERROR",
        exitCode: EXIT_CODES.SECTION_ERROR,
        details: {
          output_path: outputPath,
          run_dir: runDir,
          failing_sections: failedSections
        }
      }
    );
  }
  return { ...runResult, artifact };
}
async function prepareParallelRun(options, runOptions = {}) {
  const normalized = normalizeSequentialOptions(options);
  const cwd = path.resolve(normalized.cwd ?? runOptions.cwd ?? process.cwd());
  const env = normalized.env ?? runOptions.env ?? process.env;
  const inputPathValue = normalized.inputPath;
  const inputPath = path.isAbsolute(inputPathValue) ? inputPathValue : path.resolve(cwd, inputPathValue);
  const startedAt = nowIso();
  const markdown = await readInputFile(inputPath);
  const parsedSections = parseSections(markdown);
  const runDir = await resolveRunDir({ ...normalized, cwd });
  const outputPath = await resolveOutputPath({ ...normalized, cwd }, inputPath);
  const runWriteRoot = path.resolve(normalized.allowRoot ?? cwd);
  const preflight = normalized.preflight === false ? { peers: normalized.peers ?? ["claude", "codex"], warnings: [] } : await (normalized.preflight ?? preflightConsensusProviderCli)({
    ...normalized,
    env,
    cwd
  });
  const peers = normalized.peers ?? preflight.peers;
  const host = preflight.host ?? detectHost(env);
  const { synthesizer } = resolveSynthesizer(
    { ...normalized, peers },
    preflight.providerInventory ?? normalized.providerInventory ?? []
  );
  const iterationMode = normalized.iteration ?? "alternating";
  const parallelism = parallelismFor(
    parsedSections.length,
    normalized.parallelism
  );
  const sections = [];
  for (const section of parsedSections) {
    const sectionDir = sectionRunDirectory(runDir, section);
    const paths = {
      input: path.join(sectionDir, "section.md"),
      records: path.join(sectionDir, "records.json"),
      output: path.join(sectionDir, "output.md"),
      status: path.join(sectionDir, "status.json")
    };
    const packetPath = path.join(sectionDir, "packet.json");
    const loopArgv = loopArgvForSection({
      section,
      paths,
      options: normalized,
      peers,
      synthesizer
    });
    await Promise.all([
      confineWrite(paths.input, runWriteRoot),
      confineWrite(paths.records, runWriteRoot),
      confineWrite(paths.output, runWriteRoot),
      confineWrite(paths.status, runWriteRoot),
      confineWrite(packetPath, runWriteRoot)
    ]);
    const packet = {
      consensus_schema_version: "v1",
      packet_type: "consensus-section-runner",
      manifest_path: path.join(runDir, "manifest.json"),
      section_id: section.id,
      name: section.name,
      original_index: section.original_index,
      section_file: paths.input,
      goal: normalized.goal ?? "",
      peers,
      max_rounds: normalized.maxRounds,
      agency: normalized.agency,
      iteration_mode: iterationMode,
      synthesizer,
      output_records: paths.records,
      output_section: paths.output,
      output_status: paths.status,
      loop_argv: loopArgv
    };
    await atomicWriteFile(paths.input, section.markdown, {
      rootPath: runWriteRoot
    });
    await atomicWriteFile(packetPath, `${JSON.stringify(packet, null, 2)}
`, {
      rootPath: runWriteRoot
    });
    sections.push(
      manifestSectionEntry({
        section,
        paths,
        packetPath,
        loopArgv,
        iterationMode,
        synthesizer
      })
    );
  }
  const manifestPath = path.join(runDir, "manifest.json");
  await confineWrite(manifestPath, runWriteRoot);
  const manifest = {
    consensus_schema_version: "v1",
    manifest_type: "consensus-parallel-run",
    mode: "parallel",
    status: "prepared",
    created_at: startedAt,
    input_path: inputPath,
    output_path: outputPath,
    run_dir: runDir,
    goal: normalized.goal ?? "",
    peers,
    host,
    max_rounds: normalized.maxRounds,
    agency: normalized.agency,
    iteration_mode: iterationMode,
    synthesizer,
    parallelism,
    sections,
    manifest_path: manifestPath
  };
  await atomicWriteFile(
    manifestPath,
    `${JSON.stringify(manifest, null, 2)}
`,
    { rootPath: runWriteRoot }
  );
  const dispatchEvent = dispatchInstructions(manifest);
  return {
    mode: "prepare_parallel",
    parallel: true,
    status: "prepared",
    inputPath,
    outputPath,
    runDir,
    manifestPath,
    goal: normalized.goal ?? "",
    peers,
    host,
    agency: normalized.agency,
    maxRounds: normalized.maxRounds,
    parallelism,
    sections,
    dispatchEvent
  };
}
async function fanInParallelRun(manifestPath, options = {}) {
  const cwd = path.resolve(options.cwd ?? process.cwd());
  const trustedRoot = path.resolve(options.allowRoot ?? cwd);
  const resolvedManifestPath = resolveManifestPathValue(manifestPath, cwd);
  if (!inside(trustedRoot, resolvedManifestPath)) {
    throw pathConfinementError(
      "manifest_path",
      resolvedManifestPath,
      trustedRoot
    );
  }
  await assertPathResolvesInside(
    trustedRoot,
    resolvedManifestPath,
    "manifest_path",
    pathConfinementError
  );
  const startedAt = nowIso();
  const startMs = Date.now();
  const manifest = await normalizeParallelManifest(
    await readJsonFile(resolvedManifestPath),
    {
      cwd,
      trustedRoot,
      manifestPath: resolvedManifestPath
    }
  );
  const sections = [];
  for (const entry of manifest.sections ?? []) {
    const errors = [];
    let output = null;
    let records = [];
    let status = null;
    try {
      output = await readFile(entry.output_section, "utf8");
    } catch (error) {
      errors.push({
        code: "missing output file",
        path: entry.output_section,
        message: asErrorLike(error).message ?? String(error)
      });
    }
    try {
      const parsedRecords = await readJsonFile(entry.output_records);
      if (!Array.isArray(parsedRecords)) {
        errors.push({
          code: "malformed result JSON",
          path: entry.output_records,
          message: "records file must contain a JSON array"
        });
        records = [];
      } else {
        records = parsedRecords.map(asConsensusRecord);
      }
    } catch (error) {
      errors.push({
        code: "malformed result JSON",
        path: entry.output_records,
        message: asErrorLike(error).message ?? String(error)
      });
      records = [];
    }
    try {
      status = asSectionStatus(await readJsonFile(entry.output_status));
    } catch (error) {
      errors.push({
        code: "malformed result JSON",
        path: entry.output_status,
        message: asErrorLike(error).message ?? String(error)
      });
      status = null;
    }
    if (status?.status === "timeout" || status?.termination_reason === "section_timeout") {
      errors.push({
        code: "section_timeout",
        path: entry.output_status,
        message: "section runner reported timeout"
      });
    }
    if (status?.status === "error") {
      errors.push({
        code: "section_error",
        path: entry.output_status,
        message: status.error ?? status.termination_reason ?? "section runner reported error"
      });
    }
    if (errors.length > 0) {
      const original = await readTextIfPresent(entry.section_file) ?? "";
      const marker = {
        consensus_schema_version: "v1",
        section_id: entry.section_id,
        subagent_id: entry.subagent_id,
        status_path: entry.output_status,
        errors
      };
      output = `${original.replace(/\n*$/u, "\n")}
${canonicalJsonBlock("section-error", marker)}
`;
      status = {
        schema_version: "v1",
        ...status,
        status: "error",
        termination_reason: status?.termination_reason ?? errors[0].code,
        turns: status?.turns ?? records.length,
        rounds: status?.rounds ?? 0,
        error: errors.map((error) => `${error.code}: ${error.message}`).join("; "),
        parallel_errors: errors
      };
    }
    sections.push({
      id: entry.section_id,
      name: entry.name,
      original_index: entry.original_index,
      subagent_id: entry.subagent_id,
      paths: {
        input: entry.section_file,
        records: entry.output_records,
        output: entry.output_section,
        status: entry.output_status,
        packet: entry.packet_path
      },
      output,
      records,
      status
    });
  }
  const endedAt = nowIso();
  const runResult = {
    mode: "parallel",
    parallel: true,
    inputPath: manifest.input_path,
    outputPath: manifest.output_path,
    runDir: manifest.run_dir,
    manifestPath: resolvedManifestPath,
    goal: manifest.goal,
    peers: manifest.peers,
    host: manifest.host ?? "unknown",
    agency: manifest.agency,
    iteration: manifest.iteration_mode ?? "alternating",
    synthesizer: manifest.synthesizer ?? null,
    maxRounds: manifest.max_rounds,
    startedAt,
    endedAt,
    wallClockMs: Date.now() - startMs,
    sections
  };
  runResult.status = aggregateParallelStatus(sections);
  const artifact = renderDeliberationArtifact(runResult);
  await atomicWriteFile(manifest.output_path, artifact, {
    rootPath: manifest.output_write_root
  });
  const failedSections = failingSections(sections);
  if (options.failOnSectionError && failedSections.length > 0) {
    throw new ConsensusError(
      `section error or impasse in ${failedSections.length} section(s)`,
      {
        code: "SECTION_ERROR",
        exitCode: EXIT_CODES.SECTION_ERROR,
        details: {
          output_path: manifest.output_path,
          run_dir: manifest.run_dir,
          manifest_path: resolvedManifestPath,
          failing_sections: failedSections
        }
      }
    );
  }
  return { ...runResult, artifact };
}
function providerCliUnavailableError(providers, selected) {
  const byId = new Map(providers.map((entry) => [entry.id, entry]));
  const details = selected.map((id) => {
    const entry = byId.get(id);
    return {
      id,
      status: String(entry?.status ?? (entry ? "unavailable" : "missing"))
    };
  });
  const summary = details.map((entry) => `${entry.id} (${entry.status})`).join(", ");
  return new ConsensusError(
    `Consensus providers are unavailable: ${summary}. Run "consensus preflight --json --provider <id>" and resolve provider authentication or availability before retrying.`,
    {
      code: "PEER_UNAVAILABLE",
      exitCode: EXIT_CODES.CONFIG,
      details: { providers: details }
    }
  );
}
function resolveProviderCliPeers(options = {}, host = "unknown", providerInventory = []) {
  const defaultPeers = host === "codex" ? ["codex", "claude"] : ["claude", "codex"];
  const peers = options.peers ?? defaultPeers;
  const inventory = normalizeProviderInventory(providerInventory);
  const byId = new Map(inventory.map((entry) => [entry.id, entry]));
  const unavailable = peers.filter(
    (peer) => byId.get(peer)?.available !== true
  );
  if (unavailable.length > 0) {
    throw providerCliUnavailableError(inventory, unavailable);
  }
  return { peers, inventory };
}
function providerInventoryForConsensusConfig(providerInventory) {
  return providerInventory.map((entry) => {
    const status = entry.available === true ? "ready" : typeof entry.status === "string" ? entry.status : "unavailable";
    return { id: entry.id, status };
  });
}
async function resolveConfiguredProviderCliPeers({
  options,
  host,
  env,
  cwd,
  providerInventory
}) {
  if (options.peers) {
    return resolveProviderCliPeers(options, host, providerInventory);
  }
  const composition = await resolveConsensusComposition({
    workflow: "convergence",
    cwd,
    env,
    inventory: providerInventoryForConsensusConfig(providerInventory)
  });
  const peerOptions = composition.source === "built-in" ? {} : { peers: composition.agents.map((agent) => agent.provider) };
  return resolveProviderCliPeers(peerOptions, host, providerInventory);
}
function parseProviderCliEnvelope(stdout, label) {
  let parsed;
  try {
    parsed = JSON.parse(stdout);
  } catch (error) {
    throw new Error(
      `consensus ${label} output was not valid JSON: ${asErrorLike(error).message}`,
      { cause: error }
    );
  }
  if (!isJsonRecord(parsed) || parsed.schema_version !== "v1") {
    throw new Error(`consensus ${label} output was not a v1 JSON envelope`);
  }
  return parsed;
}
async function preflightConsensusProviderCli(options = {}) {
  const runCommand = options.runCommand ?? defaultRunCommand;
  const env = options.env ?? process.env;
  const cwd = options.cwd ?? process.cwd();
  const command = requireConsensusCliPath({ env });
  let inventoryOutput;
  try {
    inventoryOutput = await runCommand(command, ["provider", "ls", "--json"], {
      env,
      cwd
    });
  } catch (error) {
    const details = asErrorLike(error);
    if (details.code === "ENOENT" || /ENOENT|not found/i.test(details.message ?? "")) {
      throw consensusProviderCliMissingError({
        attemptedPaths: [command],
        cause: error
      });
    }
    throw error;
  }
  const inventoryEnvelope = parseProviderCliEnvelope(
    inventoryOutput.stdout,
    "provider inventory"
  );
  const providerInventory = normalizeProviderInventory(
    inventoryEnvelope.providers
  );
  const host = detectHost(env);
  const resolved = await resolveConfiguredProviderCliPeers({
    options,
    host,
    env,
    cwd,
    providerInventory
  });
  const { synthesizer } = resolveSynthesizer(
    {
      iteration: options.iteration ?? "alternating",
      synthesizer: options.synthesizer ?? null,
      peers: resolved.peers
    },
    resolved.inventory
  );
  const providersToPreflight = [
    .../* @__PURE__ */ new Set([...resolved.peers, ...synthesizer ? [synthesizer] : []])
  ];
  for (const peer of providersToPreflight) {
    const preflightOutput = await runCommand(
      command,
      ["preflight", "--json", "--provider", peer],
      { env, cwd }
    );
    const preflightEnvelope = parseProviderCliEnvelope(
      preflightOutput.stdout,
      `${peer} preflight`
    );
    if (preflightEnvelope.usable !== true) {
      throw providerCliUnavailableError(
        normalizeProviderInventory(preflightEnvelope.providers),
        [peer]
      );
    }
  }
  return {
    ok: true,
    version: "provider-cli",
    providerInventory: resolved.inventory,
    host,
    peers: resolved.peers,
    warnings: []
  };
}
async function runWrapperCli(argv, options = {}) {
  const stdout = options.stdout ?? process.stdout;
  const stderr = options.stderr ?? process.stderr;
  const env = options.env ?? process.env;
  const cwd = options.cwd ?? process.cwd();
  try {
    const parsed = parseWrapperArgs(argv);
    writeJsonl(stdout, "run_started", {
      mode: parsed.mode,
      input_path: parsed.inputPath,
      manifest_path: parsed.manifestPath,
      iteration_mode: parsed.iteration ?? "alternating",
      calls_per_round: callsPerRound(
        parsed.iteration ?? "alternating"
      )
    });
    if (parsed.mode === "prepare_parallel") {
      const result2 = await prepareParallelRun({
        ...parsed,
        env,
        cwd,
        preflight: options.preflight
      });
      writeJsonl(stdout, "parallel_dispatch_required", result2.dispatchEvent);
      writeJsonl(stdout, "run_completed", {
        status: result2.status,
        manifest_path: result2.manifestPath,
        run_dir: result2.runDir,
        sections: result2.sections.length
      });
      return 0;
    }
    if (parsed.mode === "fan_in") {
      const result2 = await fanInParallelRun(parsed.manifestPath, {
        env,
        cwd,
        allowRoot: parsed.allowRoot,
        failOnSectionError: parsed.failOnSectionError
      });
      writeJsonl(stdout, "run_completed", {
        status: result2.status,
        output_path: result2.outputPath,
        run_dir: result2.runDir,
        sections: result2.sections.length
      });
      return 0;
    }
    if (parsed.mode !== "sequential") {
      throw new ConsensusError(
        `${parsed.mode} is not implemented in Phase 3 prepare`,
        {
          code: "MODE_NOT_IMPLEMENTED",
          exitCode: EXIT_CODES.CONFIG
        }
      );
    }
    const result = await runSequential(
      { ...parsed, env, cwd, preflight: options.preflight },
      { stdin: options.stdin ?? process.stdin, stdout }
    );
    writeJsonl(stdout, "run_completed", {
      status: result.status,
      output_path: result.outputPath,
      run_dir: result.runDir,
      sections: result.sections.length,
      sections_escalated: result.sections.filter(
        (section) => section.status?.status === "escalation"
      ).length
    });
    return 0;
  } catch (error) {
    const exitCode = exitCodeForError(error);
    const details = asErrorLike(error);
    writeJsonl(stdout, "error", {
      code: details.code ?? "ERROR",
      exit_code: exitCode,
      message: details.message ?? String(error),
      ...details.details === void 0 ? {} : { details: details.details }
    });
    stderr.write(`${renderHumanError(error, env)}
`);
    return exitCode;
  }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  runWrapperCli(process.argv.slice(2)).then((exitCode) => {
    process.exitCode = exitCode;
  });
}
export {
  INPUT_SIZE_CAP_BYTES,
  PROVIDER_ID_PATTERN,
  atomicWriteFile2 as atomicWriteFile,
  buildEscalationEvent2 as buildEscalationEvent,
  confineWrite2 as confineWrite,
  createJsonlEvent,
  detectHost,
  fanInParallelRun,
  parseDeliberationArtifactForResume2 as parseDeliberationArtifactForResume,
  parseSections2 as parseSections,
  parseWrapperArgs2 as parseWrapperArgs,
  preflightConsensusProviderCli,
  prepareParallelRun,
  readInputFile2 as readInputFile,
  renderDeliberationArtifact2 as renderDeliberationArtifact,
  renderHumanError2 as renderHumanError,
  resolveOutputPath2 as resolveOutputPath,
  resolvePeers,
  resolveResumePath2 as resolveResumePath,
  resolveRunDir2 as resolveRunDir,
  resolveSynthesizer2 as resolveSynthesizer,
  runSequential,
  runWrapperCli,
  slugSectionId
};
