// GENERATED by scripts/build-generated.mjs. Do not edit directly.
// Source: src/consensus/refine/refine-shared.ts
import { randomBytes } from "node:crypto";
import {
  lstat,
  mkdir,
  open,
  readFile,
  realpath,
  rename,
  stat,
  unlink,
  writeFile
} from "node:fs/promises";
import path from "node:path";
const INPUT_SIZE_CAP_BYTES = 1024 * 1024;
function isJsonRecord(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}
function asErrorLike(error) {
  return isJsonRecord(error) ? error : {};
}
function asConsensusRecord(value) {
  return isJsonRecord(value) ? value : {};
}
function asConsensusRecords(value) {
  return Array.isArray(value) ? value.map(asConsensusRecord) : [];
}
function asSectionStatus(value) {
  return isJsonRecord(value) ? value : {};
}
function inside(root, target) {
  const relative = path.relative(root, target);
  return relative === "" || !relative.startsWith("..") && !path.isAbsolute(relative);
}
async function pathExists(targetPath) {
  try {
    await lstat(targetPath);
    return true;
  } catch (error) {
    if (asErrorLike(error).code === "ENOENT") return false;
    throw error;
  }
}
async function nearestExistingPath(targetPath) {
  let current = path.resolve(targetPath);
  while (!await pathExists(current)) {
    const parent = path.dirname(current);
    if (parent === current) return current;
    current = parent;
  }
  return current;
}
async function syncPathIfAvailable(targetPath) {
  let handle;
  try {
    handle = await open(targetPath, "r");
    await handle.sync();
  } finally {
    await handle?.close();
  }
}
function nowIso() {
  return (/* @__PURE__ */ new Date()).toISOString();
}
function createJsonlEvent(event, payload = {}, options = {}) {
  return {
    consensus_schema_version: "v1",
    event,
    timestamp: options.now?.() ?? nowIso(),
    ...payload
  };
}
function writeJsonl(stream, event, payload = {}, options = {}) {
  const entry = createJsonlEvent(event, payload, options);
  stream.write(`${JSON.stringify(entry)}
`);
  return entry;
}
function renderHumanError(error, env = process.env) {
  const details = asErrorLike(error);
  if (env.CONSENSUS_LOG === "trace" && details.stack) {
    return details.stack;
  }
  return details.message ?? String(error);
}
function consensusBlockPattern(label) {
  return new RegExp(`<!-- consensus:${label}\\n([\\s\\S]*?)\\n-->`, "g");
}
async function readJsonFile(filePath) {
  return JSON.parse(await readFile(filePath, "utf8"));
}
async function readJsonIfPresent(filePath, fallback) {
  try {
    return await readJsonFile(filePath);
  } catch (error) {
    if (asErrorLike(error).code === "ENOENT") return fallback;
    return fallback;
  }
}
async function readTextIfPresent(filePath) {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (asErrorLike(error).code === "ENOENT") return null;
    return null;
  }
}
async function readInputFile(inputPath, options = {}) {
  const capBytes = options.sizeCapBytes ?? INPUT_SIZE_CAP_BYTES;
  const fileStat = await stat(inputPath);
  if (fileStat.size > capBytes) {
    throw new Error(`input exceeds size cap of ${capBytes} bytes`);
  }
  const contents = await readFile(inputPath, "utf8");
  if (Buffer.byteLength(contents, "utf8") > capBytes) {
    throw new Error(`input exceeds size cap of ${capBytes} bytes`);
  }
  return contents;
}
async function confineWrite(targetPath, rootPath) {
  const root = path.resolve(rootPath);
  const target = path.isAbsolute(targetPath) ? path.resolve(targetPath) : path.resolve(root, targetPath);
  if (!inside(root, target)) {
    throw new Error(`write path is outside allowed root: ${target}`);
  }
  if (await pathExists(target)) {
    const targetStat = await lstat(target);
    if (targetStat.isSymbolicLink()) {
      throw new Error(`write target may not be a symlink: ${target}`);
    }
  }
  const realRoot = await realpath(root);
  const parent = path.dirname(target);
  const existing = await nearestExistingPath(parent);
  const realExisting = await realpath(existing);
  const realParent = path.resolve(
    realExisting,
    path.relative(existing, parent)
  );
  if (!inside(realRoot, realParent)) {
    throw new Error(`write path resolves outside allowed root: ${target}`);
  }
  return target;
}
async function atomicWriteFile(targetPath, contents, options = {}) {
  const writePath = options.rootPath ? await confineWrite(targetPath, options.rootPath) : path.resolve(targetPath);
  if (await pathExists(writePath)) {
    const targetStat = await lstat(writePath);
    if (targetStat.isSymbolicLink()) {
      throw new Error(`write target may not be a symlink: ${writePath}`);
    }
  }
  await mkdir(path.dirname(writePath), { recursive: true });
  const tempPath = path.join(
    path.dirname(writePath),
    `.${path.basename(writePath)}.tmp-${process.pid}-${randomBytes(8).toString("hex")}`
  );
  try {
    await writeFile(tempPath, contents);
    await syncPathIfAvailable(tempPath);
    await rename(tempPath, writePath);
    await syncPathIfAvailable(path.dirname(writePath));
  } catch (error) {
    const annotatedError = error;
    try {
      await unlink(tempPath);
    } catch (cleanupError) {
      if (asErrorLike(cleanupError).code !== "ENOENT") {
        annotatedError.cleanupError = cleanupError;
      }
    }
    throw annotatedError;
  }
  return writePath;
}
let defaultRunDirCounter = 0;
function defaultRunDirName() {
  return `run-${Date.now()}-${process.pid}-${defaultRunDirCounter++}`;
}
async function resolveRunDir(options = {}) {
  const cwd = path.resolve(options.cwd ?? process.cwd());
  const root = path.resolve(options.allowRoot ?? cwd);
  const target = options.runDir ? path.isAbsolute(options.runDir) ? options.runDir : path.resolve(cwd, options.runDir) : path.resolve(cwd, ".consensus", defaultRunDirName());
  return await confineWrite(target, root);
}
async function resolveOutputPath(options = {}, inputPath) {
  if (options.output) {
    const cwd = path.resolve(options.cwd ?? process.cwd());
    const root = path.resolve(options.allowRoot ?? cwd);
    const target2 = path.isAbsolute(options.output) ? options.output : path.resolve(cwd, options.output);
    return await confineWrite(target2, root);
  }
  const target = path.resolve(`${inputPath}.consensus.md`);
  return await confineWrite(target, path.dirname(path.resolve(inputPath)));
}
async function resolveResumePath(options = {}) {
  if (!options.resume) return null;
  const cwd = path.resolve(options.cwd ?? process.cwd());
  const root = path.resolve(options.allowRoot ?? cwd);
  const target = path.isAbsolute(options.resume) ? options.resume : path.resolve(cwd, options.resume);
  return await confineWrite(target, root);
}
export {
  INPUT_SIZE_CAP_BYTES,
  asConsensusRecord,
  asConsensusRecords,
  asErrorLike,
  asSectionStatus,
  atomicWriteFile,
  confineWrite,
  consensusBlockPattern,
  createJsonlEvent,
  defaultRunDirName,
  inside,
  isJsonRecord,
  nearestExistingPath,
  nowIso,
  pathExists,
  readInputFile,
  readJsonFile,
  readJsonIfPresent,
  readTextIfPresent,
  renderHumanError,
  resolveOutputPath,
  resolveResumePath,
  resolveRunDir,
  syncPathIfAvailable,
  writeJsonl
};
