import { mkdtemp, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { expect, it } from 'vitest';

// @ts-expect-error The generated runtime is intentionally declaration-free; this test exercises the shipped artifact.
import * as consensusRefine from '../../../plugins/consensus/skills/refine/scripts/consensus-refine.mjs';
import { extractJsonBlock } from '../../helpers/consensus.js';
import {
  captureWriter,
  makeProviderCliEnv,
  parseJsonl,
  repoRoot,
  runNodeScript,
  sampleInput,
} from '../../helpers/process.mjs';

const { runWrapperCli } = consensusRefine;

type JsonRecord = Record<string, any>;

const loopScript = path.join(
  repoRoot,
  'plugins/consensus/skills/refine/scripts/consensus-loop.mjs',
);

it('parallel section runner target is the generated consensus-loop runtime', async () => {
  expect(loopScript).toBe(
    path.join(
      repoRoot,
      'plugins/consensus/skills/refine/scripts/consensus-loop.mjs',
    ),
  );
  const loopSource = await readFile(loopScript, 'utf8');
  expect(loopSource).toMatch(
    /^\/\/ GENERATED by scripts\/build-generated\.mjs\. Do not edit directly\./,
  );
});

it('prepare, simulated host section loops, and fan-in work end-to-end', async () => {
  const tempRoot = await mkdtemp(
    path.join(os.tmpdir(), 'consensus-parallel-integration-'),
  );
  const outputPath = path.join(tempRoot, 'sample.consensus.md');
  const runDir = path.join(tempRoot, '.consensus/run');
  const prepareStdout = captureWriter();
  const prepareStderr = captureWriter();

  const prepareExit = await runWrapperCli(
    [
      sampleInput,
      '--prepare-parallel',
      '--output',
      outputPath,
      '--run-dir',
      runDir,
      '--allow-root',
      tempRoot,
      '--goal',
      'Exercise host-mediated parallel dispatch.',
      '--peers',
      'claude,codex',
      '--max-rounds',
      '2',
    ],
    {
      stdout: prepareStdout.stream,
      stderr: prepareStderr.stream,
      cwd: tempRoot,
      preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
    },
  );

  expect(prepareExit, prepareStderr.value()).toBe(0);
  const dispatch = parseJsonl<JsonRecord>(prepareStdout.value()).find(
    (event) => event.phase === 'parallel_dispatch_required',
  ) as JsonRecord;
  expect(dispatch).toBeTruthy();

  const manifest = JSON.parse(await readFile(dispatch.manifest, 'utf8'));
  const completionOrder = [
    manifest.sections[2],
    manifest.sections[0],
    manifest.sections[1],
  ];
  expect(
    completionOrder.map((section: JsonRecord) => section.original_index),
  ).toEqual([2, 0, 1]);

  for (const section of completionOrder) {
    const env =
      section.original_index === 2
        ? makeProviderCliEnv({
            CONSENSUS_STUB_VERDICT: 'IMPASSE',
          })
        : makeProviderCliEnv();
    await runNodeScript(loopScript, section.loop_argv, { cwd: tempRoot, env });
  }

  const fanInStdout = captureWriter();
  const fanInStderr = captureWriter();
  const fanInExit = await runWrapperCli(['--fan-in', dispatch.manifest], {
    stdout: fanInStdout.stream,
    stderr: fanInStderr.stream,
    cwd: tempRoot,
  });

  expect(fanInExit, fanInStderr.value()).toBe(0);
  const artifact = await readFile(outputPath, 'utf8');
  expect(
    artifact.indexOf('# Intro') < artifact.indexOf('## Details'),
  ).toBeTruthy();
  expect(
    artifact.indexOf('## Details') < artifact.indexOf('## Close'),
  ).toBeTruthy();
  expect(artifact).toMatch(/fixture impasse/);

  const resolution = extractJsonBlock(artifact, 'consensus-resolution');
  expect(resolution.status).toBe('partial');
  expect(resolution.parallel).toBe(true);
  expect(resolution.sections.converged).toBe(2);
  expect(resolution.sections.impasse).toBe(1);

  const fanInEvents = parseJsonl<JsonRecord>(fanInStdout.value());
  const finalFanInEvent = fanInEvents.at(-1) as JsonRecord;
  expect(finalFanInEvent.event).toBe('run_completed');
  expect(finalFanInEvent.status).toBe('partial');
});

// p05-t04: the prepared mode/synthesizer metadata must drive the real section
// runner subprocess. A parallel_revision dispatch converges every section via the
// stub and the fan-in artifact records the mode end-to-end.
it('parallel_revision mode threads through prepare, section runners, and fan-in', async () => {
  const tempRoot = await mkdtemp(
    path.join(os.tmpdir(), 'consensus-parallel-mode-integration-'),
  );
  const outputPath = path.join(tempRoot, 'sample.consensus.md');
  const runDir = path.join(tempRoot, '.consensus/run');
  const prepareStdout = captureWriter();
  const prepareStderr = captureWriter();

  const prepareExit = await runWrapperCli(
    [
      sampleInput,
      '--prepare-parallel',
      '--iteration',
      'parallel_revision',
      '--output',
      outputPath,
      '--run-dir',
      runDir,
      '--allow-root',
      tempRoot,
      '--goal',
      'Exercise parallel-mode host dispatch.',
      '--peers',
      'claude,codex',
      '--max-rounds',
      '3',
    ],
    {
      stdout: prepareStdout.stream,
      stderr: prepareStderr.stream,
      cwd: tempRoot,
      preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
    },
  );

  expect(prepareExit, prepareStderr.value()).toBe(0);
  const dispatch = parseJsonl<JsonRecord>(prepareStdout.value()).find(
    (event) => event.phase === 'parallel_dispatch_required',
  ) as JsonRecord;
  expect(dispatch.iteration_mode).toBe('parallel_revision');

  const manifest = JSON.parse(await readFile(dispatch.manifest, 'utf8'));
  expect(manifest.iteration_mode).toBe('parallel_revision');

  for (const section of manifest.sections) {
    expect(section.iteration_mode).toBe('parallel_revision');
    await runNodeScript(loopScript, section.loop_argv, {
      cwd: tempRoot,
      env: makeProviderCliEnv({ CONSENSUS_STUB_VERDICT: 'CONVERGED' }),
    });
  }

  const fanInStdout = captureWriter();
  const fanInStderr = captureWriter();
  const fanInExit = await runWrapperCli(['--fan-in', dispatch.manifest], {
    stdout: fanInStdout.stream,
    stderr: fanInStderr.stream,
    cwd: tempRoot,
  });

  expect(fanInExit, fanInStderr.value()).toBe(0);
  const artifact = await readFile(outputPath, 'utf8');
  const resolution = extractJsonBlock(artifact, 'consensus-resolution');
  expect(resolution.status).toBe('converged');
  expect(resolution.iteration).toBe('parallel_revision');
  expect(resolution.sections.converged).toBe(3);

  const fanInEvents = parseJsonl<JsonRecord>(fanInStdout.value());
  const finalFanInEvent = fanInEvents.at(-1) as JsonRecord;
  expect(finalFanInEvent.status).toBe('converged');
});
