import { mkdtemp, readFile, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { expect, it } from 'vitest';

// @ts-expect-error The generated runtime is intentionally declaration-free; this test exercises the shipped artifact.
import * as consensusLoop from '../../../plugins/consensus/skills/refine/scripts/consensus-loop.mjs';
// @ts-expect-error The generated runtime is intentionally declaration-free; this test exercises the shipped artifact.
import * as consensusRefine from '../../../plugins/consensus/skills/refine/scripts/consensus-refine.mjs';
import { extractJsonBlock } from '../../helpers/consensus.js';
import {
  fixtureBin,
  makeStubEnv,
  repoRoot,
  sampleInput,
} from '../../helpers/process.mjs';

const { hashArtifact } = consensusLoop;
const { renderDeliberationArtifact, runSequential, runWrapperCli } =
  consensusRefine;

type JsonRecord = Record<string, any>;

// JSONL-event capturer: buffers streaming writes and parses each line as JSON.
function captureStdout() {
  const lines: string[] = [];
  return {
    write(chunk: unknown) {
      lines.push(String(chunk));
      return true;
    },
    events() {
      return lines
        .join('')
        .split('\n')
        .filter(Boolean)
        .map((line) => JSON.parse(line));
    },
  };
}

const refineScript = path.join(
  repoRoot,
  'plugins/consensus/skills/refine/scripts/consensus-refine.mjs',
);
const generatedLoopScript = path.join(
  repoRoot,
  'plugins/consensus/skills/refine/scripts/consensus-loop.mjs',
);

function consensusBlock(label: string, value: unknown) {
  return `<!-- consensus:${label}\n${JSON.stringify(value, null, 2)}\n-->`;
}

function completedResumeArtifact(sections: JsonRecord[]) {
  return [
    '---',
    'consensus_schema_version: v1',
    'status: converged',
    'mode: sequential',
    '---',
    '',
    '# Consensus Refine Artifact',
    '',
    '## Final Output',
    '',
    sections
      .map((section: JsonRecord) => section.output)
      .join('\n\n')
      .replace(/\n*$/u, '\n'),
    '## Resolution',
    '',
    consensusBlock('consensus-resolution', {
      consensus_schema_version: 'v1',
      status: 'converged',
      mode: 'sequential',
      parallel: false,
      peers: ['claude', 'codex'],
    }),
    '',
    '## Section States',
    '',
    consensusBlock(
      'consensus-section-states',
      sections.map((section: JsonRecord, index: number) => ({
        id: section.id,
        name: section.name,
        original_index: index,
        status: 'converged',
        turns: 2,
        rounds: 1,
        final_artifact_hash: hashArtifact(section.output),
        final_output: section.output,
      })),
    ),
    '',
    '## Deliberation Log',
    '',
    ...sections.flatMap((section: JsonRecord, index: number) => [
      `### ${index + 1}. ${section.name} (converged)`,
      '',
      consensusBlock('consensus-section-status', {
        schema_version: 'v0',
        status: 'converged',
        termination_reason: 'accept_twice',
        turns: 2,
        rounds: 1,
        final_artifact_hash: hashArtifact(section.output),
      }),
      '',
      consensusBlock('consensus-verdict', {
        schema_version: 'v0',
        verdict: 'ACCEPT',
        reasoning: 'Stable.',
      }),
      '',
      consensusBlock('consensus-verdict', {
        schema_version: 'v0',
        verdict: 'ACCEPT',
        reasoning: 'Still stable.',
      }),
      '',
    ]),
  ].join('\n');
}

it('consensus-refine imports the generated consensus-loop runtime path', async () => {
  const wrapperSource = await readFile(refineScript, 'utf8');
  const generatedLoop = await readFile(generatedLoopScript, 'utf8');

  expect(
    wrapperSource,
    'wrapper should import the committed generated runtime path',
  ).toMatch(/from '\.\/consensus-loop\.mjs';/);
  expect(wrapperSource).not.toMatch(/src\/consensus-loop\.ts/);
  expect(generatedLoop).toMatch(
    /^\/\/ GENERATED by scripts\/build-generated\.mjs\. Do not edit directly\./,
  );
});

it('runSequential refines sections, creates run files, and writes an artifact', async () => {
  const tempRoot = await mkdtemp(
    path.join(os.tmpdir(), 'consensus-sequential-'),
  );
  const outputPath = path.join(tempRoot, 'sample.consensus.md');
  const runDir = path.join(tempRoot, '.consensus/run');
  const env = {
    PATH: `${fixtureBin}${path.delimiter}${process.env.PATH}`,
    CURSOR_TRACE_ID: 'artifact-host-test',
  };
  const result = await runSequential({
    inputPath: sampleInput,
    output: outputPath,
    runDir,
    allowRoot: tempRoot,
    cwd: tempRoot,
    goal: 'Make each section clearer.',
    peers: ['claude', 'codex'],
    maxRounds: 2,
    agency: 'moderate',
    preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
    env,
  });

  expect(result.sections.length).toBe(3);
  expect(result.status).toBe('converged');
  expect((await stat(outputPath)).isFile()).toBe(true);

  for (const section of result.sections) {
    expect((await stat(section.paths.records)).isFile()).toBe(true);
    expect((await stat(section.paths.status)).isFile()).toBe(true);
    expect((await stat(section.paths.output)).isFile()).toBe(true);
  }

  const artifact = await readFile(outputPath, 'utf8');
  expect(artifact).toMatch(/^---\nconsensus_schema_version: v1\n/m);
  expect(artifact).toMatch(/^iteration: alternating$/m);
  expect(artifact).toMatch(/^cold_start: shared_input$/m);
  expect(artifact).toMatch(/^peers: \["claude","codex"\]$/m);
  expect(artifact).toMatch(/^host: cursor$/m);
  expect(artifact).toMatch(/^total_turns: [1-9]\d*$/m);
  expect(artifact).toMatch(/^total_rounds: [1-9]\d*$/m);
  expect(artifact).toMatch(/^wall_clock_ms: \d+$/m);
  expect(artifact).toMatch(/^cost_source: unavailable$/m);
  expect(artifact).toMatch(/^approximate_cost_usd: null$/m);
  expect(artifact).toMatch(
    new RegExp(
      `^input_path: ${JSON.stringify(sampleInput).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`,
      'm',
    ),
  );
  expect(artifact).toMatch(/^run_id: run$/m);
  expect(artifact).toMatch(/\n---\n\n# Consensus Refine Artifact/m);
  expect(artifact).toMatch(/## Final Output/);
  expect(artifact).toMatch(/# Intro/);
  expect(artifact).toMatch(/## Details/);
  expect(artifact).toMatch(/## Resolution/);
  expect(artifact).toMatch(/Make each section clearer\./);
  expect(artifact).toMatch(/## Deliberation Log/);
  expect(artifact).not.toMatch(/```json consensus-resolution/);
  expect(artifact).toMatch(/<!-- consensus:consensus-resolution\n/);

  const resolution = extractJsonBlock(artifact, 'consensus-resolution');
  expect(resolution.consensus_schema_version).toBe('v1');
  expect(resolution.mode).toBe('sequential');
  expect(resolution.host).toBe('cursor');
  expect(resolution.sections.total).toBe(3);
  expect(resolution.sections.converged).toBe(3);

  const sectionStates = extractJsonBlock(artifact, 'consensus-section-states');
  expect(sectionStates.length).toBe(3);
  expect(
    sectionStates.every(
      (section: JsonRecord) =>
        typeof section.final_output === 'string' &&
        section.final_output.length > 0,
    ),
  ).toBeTruthy();
  expect(
    sectionStates.map((section: JsonRecord) => section.original_index),
  ).toEqual([0, 1, 2]);
});

it('run_started discloses iteration mode and per-round call multiplier', async () => {
  const alternating = captureStdout();
  await runWrapperCli([sampleInput, '--peers', 'claude,codex'], {
    stdout: alternating,
    env: makeStubEnv(),
    preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
  });
  const altStart = alternating
    .events()
    .find((event) => event.event === 'run_started');
  expect(altStart, 'expected run_started event').toBeTruthy();
  expect(altStart.iteration_mode).toBe('alternating');
  expect(altStart.calls_per_round).toEqual({ peer: 1, synthesis: 0 });

  const parallel = captureStdout();
  await runWrapperCli(
    [
      sampleInput,
      '--peers',
      'claude,codex',
      '--iteration',
      'parallel_revision',
    ],
    {
      stdout: parallel,
      env: makeStubEnv({
        PASEO_STUB_RESPONSE_JSON: JSON.stringify({
          schema_version: 'v1',
          verdict: 'CONVERGED',
          reasoning: 'agreed',
          critique: { own_previous: 'o', peer_previous: 'p' },
        }),
      }),
      preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
    },
  );
  const parStart = parallel
    .events()
    .find((event) => event.event === 'run_started');
  expect(parStart.iteration_mode).toBe('parallel_revision');
  expect(parStart.calls_per_round).toEqual({ peer: 2, synthesis: 0 });
});

it('parallel-revision artifact resolution reports peer_calls totals', async () => {
  const tempRoot = await mkdtemp(
    path.join(os.tmpdir(), 'consensus-peer-calls-'),
  );
  const outputPath = path.join(tempRoot, 'out.consensus.md');
  const runDir = path.join(tempRoot, '.consensus/run');
  const converged = JSON.stringify({
    schema_version: 'v1',
    verdict: 'CONVERGED',
    reasoning: 'agreed',
    critique: { own_previous: 'o', peer_previous: 'p' },
  });

  const result = await runSequential({
    inputPath: sampleInput,
    output: outputPath,
    runDir,
    allowRoot: tempRoot,
    cwd: tempRoot,
    peers: ['claude', 'codex'],
    iteration: 'parallel_revision',
    maxRounds: 2,
    agency: 'moderate',
    preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
    env: makeStubEnv({ PASEO_STUB_RESPONSE_JSON: converged }),
  });

  const artifact = await readFile(outputPath, 'utf8');
  const resolution = extractJsonBlock(artifact, 'consensus-resolution');
  expect(resolution.iteration).toBe('parallel_revision');
  expect(
    Number.isInteger(resolution.peer_calls),
    'expected integer peer_calls',
  ).toBeTruthy();
  expect(
    resolution.peer_calls >= 2,
    'expected at least one round of two peer calls',
  ).toBeTruthy();
  // peer_calls equals the total peer turns across sections.
  const totalTurns = result.sections.reduce(
    (sum: number, section: JsonRecord) => sum + (section.status?.turns ?? 0),
    0,
  );
  expect(resolution.peer_calls).toBe(totalTurns);
});

it('runSequential preserves completed resume section output when source input changes', async () => {
  const tempRoot = await mkdtemp(
    path.join(os.tmpdir(), 'consensus-resume-completed-'),
  );
  const inputPath = path.join(tempRoot, 'draft.md');
  const resumePath = path.join(tempRoot, 'draft.old.consensus.md');
  const outputPath = path.join(tempRoot, 'draft.new.consensus.md');
  const runDir = path.join(tempRoot, '.consensus/run');
  const oldIntro = '# Intro\n\nOld stable text.\n';
  const oldDetails = '## Details\n\nOld stable details.\n';

  await writeFile(
    resumePath,
    completedResumeArtifact([
      { id: 'intro-0', name: 'Intro', output: oldIntro },
      { id: 'details-1', name: 'Details', output: oldDetails },
    ]),
  );
  await writeFile(
    inputPath,
    '# Intro\n\nCHANGED INPUT SHOULD NOT BE RESUME STATE.\n\n## Details\n\nChanged details.\n',
  );

  const result = await runSequential({
    inputPath,
    resume: resumePath,
    output: outputPath,
    runDir,
    allowRoot: tempRoot,
    cwd: tempRoot,
    peers: ['claude', 'codex'],
    preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
    env: makeStubEnv(),
  });

  const artifact = await readFile(outputPath, 'utf8');
  expect(result.sections[0].output).toBe(oldIntro);
  expect(result.sections[1].output).toBe(oldDetails);
  expect(artifact).toMatch(/Old stable text\./);
  expect(artifact).toMatch(/Old stable details\./);
  expect(artifact).not.toMatch(/CHANGED INPUT SHOULD NOT BE RESUME STATE/);
  expect(artifact).not.toMatch(/Changed details\./);
});

it('runSequential preserves artifact section inventory when source headings drift', async () => {
  const tempRoot = await mkdtemp(
    path.join(os.tmpdir(), 'consensus-resume-inventory-'),
  );
  const inputPath = path.join(tempRoot, 'draft.md');
  const resumePath = path.join(tempRoot, 'draft.old.consensus.md');
  const outputPath = path.join(tempRoot, 'draft.new.consensus.md');
  const runDir = path.join(tempRoot, '.consensus/run');
  const oldIntro = '# Intro\n\nOld stable text.\n';
  const oldDetails = '## Details\n\nOld stable details.\n';

  await writeFile(
    resumePath,
    completedResumeArtifact([
      { id: 'intro-0', name: 'Intro', output: oldIntro },
      { id: 'details-1', name: 'Details', output: oldDetails },
    ]),
  );
  await writeFile(
    inputPath,
    '# Renamed Intro\n\nThe current source no longer has Details.\n',
  );

  const result = await runSequential({
    inputPath,
    resume: resumePath,
    output: outputPath,
    runDir,
    allowRoot: tempRoot,
    cwd: tempRoot,
    peers: ['claude', 'codex'],
    preflight: async () => ({ peers: ['claude', 'codex'], warnings: [] }),
    env: makeStubEnv(),
  });

  const artifact = await readFile(outputPath, 'utf8');
  const sectionStates = extractJsonBlock(artifact, 'consensus-section-states');

  expect(result.sections.length).toBe(2);
  expect(result.sections.map((section: JsonRecord) => section.name)).toEqual([
    'Intro',
    'Details',
  ]);
  expect(sectionStates.map((section: JsonRecord) => section.id)).toEqual([
    'intro-0',
    'details-1',
  ]);
  expect(artifact).toMatch(/Old stable text\./);
  expect(artifact).toMatch(/Old stable details\./);
  expect(artifact).not.toMatch(/The current source no longer has Details/);
});

it('renderDeliberationArtifact uses canonical containers and contains prose headings', () => {
  const artifact = renderDeliberationArtifact({
    goal: 'Review tricky text.',
    mode: 'sequential',
    parallel: false,
    peers: ['claude', 'codex'],
    agency: 'moderate',
    maxRounds: 2,
    startedAt: '2026-05-04T02:00:00.000Z',
    endedAt: '2026-05-04T02:00:01.000Z',
    wallClockMs: 1000,
    sections: [
      {
        id: 'tricky-0',
        name: 'Tricky',
        original_index: 0,
        output: 'Final with ``` fenced content.\n',
        status: {
          status: 'converged',
          termination_reason: 'hash_match',
          turns: 2,
          rounds: 1,
        },
        records: [
          {
            round_index: 1,
            agent: 'claude',
            verdict: 'REVISE',
            reasoning:
              '# Unexpected Heading\nRemove <script>alert(1)</script> from prose.',
            proposed_artifact: 'Draft with ``` fence.\n',
          },
        ],
      },
    ],
  });

  expect(artifact).toMatch(/````markdown\nDraft with ``` fence\.\n````/);
  expect(artifact).not.toMatch(/Reasoning:\nRemove <script>/);
  expect(artifact).toMatch(
    /Reasoning:\n\\# Unexpected Heading\nRemove \[removed\] from prose\./,
  );
  expect(artifact).toMatch(/<!-- consensus:consensus-verdict\n/);
  expect(artifact).toMatch(/"proposed_artifact": "Draft with ``` fence\.\\n"/);
});

// --- p04-t04: escalation_required JSONL event -----------------------------

function persistentSynthesizedStubs() {
  let peerCall = 0;
  const invokePeer = async () => {
    peerCall += 1;
    return {
      json: {
        schema_version: 'v1',
        verdict: 'REVISE',
        reasoning: `r${peerCall}`,
        critique: { own_previous: 'o', peer_previous: 'p' },
        proposed_artifact: `peer revision ${peerCall}.\n`,
      },
      stdout: '{"id":"peer"}',
    };
  };
  let synthCall = 0;
  const invokeSynthesizer = async () => {
    synthCall += 1;
    return {
      json: {
        schema_version: 'v1',
        synthesized_artifact: `merged ${synthCall}.\n`,
        synthesis_reasoning: 'merged favoring stronger reasoning',
        unresolved_disagreements: ['heading style unresolved'],
      },
      stdout: '{"id":"synth"}',
    };
  };
  return { invokePeer, invokeSynthesizer };
}

it('escalation_required event resolves divergent full text and resume vector, emitted before run end', async () => {
  const tempRoot = await mkdtemp(
    path.join(os.tmpdir(), 'consensus-escalation-event-'),
  );
  const inputPath = path.join(tempRoot, 'draft.md');
  const outputPath = path.join(tempRoot, 'out.consensus.md');
  const runDir = path.join(tempRoot, '.consensus/run');
  await writeFile(inputPath, '# Intro\n\nSeed.\n');

  const { invokePeer, invokeSynthesizer } = persistentSynthesizedStubs();
  const stdout = captureStdout();
  const result = await runSequential(
    {
      inputPath,
      output: outputPath,
      runDir,
      allowRoot: tempRoot,
      cwd: tempRoot,
      goal: 'Tighten it.',
      peers: ['claude', 'codex'],
      iteration: 'parallel_synthesized',
      synthesizer: 'claude',
      maxRounds: 8,
      agency: 'moderate',
      preflight: async () => ({
        peers: ['claude', 'codex'],
        providerInventory: [
          { id: 'claude', available: true },
          { id: 'codex', available: true },
        ],
        warnings: [],
      }),
      invokePeer,
      invokeSynthesizer,
    },
    { stdout },
  );

  expect(result.sections[0].status.status).toBe('escalation');

  const events = stdout.events();
  const escalation = events.find(
    (event) => event.event === 'escalation_required',
  );
  expect(escalation, 'expected escalation_required event').toBeTruthy();
  expect(escalation.trigger).toBe('persistent_disagreement');
  expect(escalation.decide_via).toBe('host');
  expect(Array.isArray(escalation.decision_kinds)).toBeTruthy();
  // Full divergent text resolved into the event (both revisions + synthesis).
  expect(typeof escalation.divergent.a.text).toBe('string');
  expect(typeof escalation.divergent.b.text).toBe('string');
  expect(escalation.divergent.a.text.length > 0).toBeTruthy();
  expect(
    escalation.divergent.synthesis,
    'synthesis text present in synthesized mode',
  ).toBeTruthy();
  expect(escalation.divergent.synthesis.text).toMatch(/merged/);
  expect(escalation.divergent.synthesis.unresolved_disagreements).toEqual([
    'heading style unresolved',
  ]);
  // Resume vector names the artifact path and the host flag.
  expect(escalation.resume.artifact_path).toBe(outputPath);
  expect(escalation.resume.flag).toBe('--host-direction');
  expect(escalation.section_id).toBe(result.sections[0].id);
});
